### ISSUE TITLE
Fehler bei w50-Klasse

### ISSUE THREAD

**Issue by dazzle89** [contao/contao#1024]
Bei der Verwendung der CSS-Klasse **w50** habe ich schon öfters das Problem gehabt, dass zum einen der Abstand der beidenden floatenden Container zur nächsten Überschrift darunter viel zu gering ist. Es ist quasi gar kein Abstand vorhanden. Zum anderen lässt sich das input-Feld der beiden w50-Container nicht anklicken. Ich kann nur über die TAB-Taste dahin gelangen und die Felder ausfüllen.

Das Problem habe momentan mit Metamodels, hatte es früher aber auch schon bei den Rocksolid Custom Elements. Daher könnte es vielleicht ein genereller Contao-Fehler sein?

Ich verwende Contao 4.8.5., der Fehler trat aber auch bei älteren Versionen schon auf. Getestet in sämtlichen Browsern auf dem Mac.

**Comment by fritzmg** [comment]
Wenn du Felder, die `w50` verwenden, gemeinsam mit Feldern verwendest, die _kein_ `w50` haben, dann musst du `clr` verwenden.

**Comment by dazzle89** [comment]
Danke und sorry, ich dachte es sei ein Fehler. Vielleicht könnte man hier irgendwann ja trotzdem eine automatische Lösung für das Clearen anstreben.

**Comment by fritzmg** [comment]
Mja, das ganze Backend auf `flex` umbauen 😁

**Comment by m-vo** [comment]
Grid!

**Comment by aschempp** [comment]
Grid wär aus meinem Verständnis falsch, flex wär richtig 🤓

**Comment by Tastaturberuf** [comment]
Manchmal wünsch ich mir schon so 3-4 Felder in einer Reihe zu haben, vorallem bei "kleinen" Widget-Values.

**Comment by zonky2** [comment]
@Tastaturberuf siehe https://github.com/contao/contao/issues/1119

**Comment by Tastaturberuf** [comment]
Oh nice. Ich nutze ich OM-Backend eh relativ oft.

**Comment by zoglo** [comment]
Kinda wanna re-discuss this issue and propose using CSS-Flex due to having the possibility of the new classes in 5.x such as:
``.w25, .w33, .w50, .w66, .w75``

In common cases, you'd want to use different layouts based on logic like we did here for improved UX
_(Yes, this example also uses .w20 🙃)_
![image](https://github.com/contao/contao/assets/55794780/463e26f2-9dfc-46b4-a53e-4f0b94b515c7)

I don't see #2053 as a good solution when trying to display it based on the mentioned example above.
Sometimes it's not about visuals but about the UX aspect.

Flex would be BC compatible and devs could still use the classes that they were used to... tho I'd want to think further and would like to introduce col-classes based on the 12 column system.

Meaning we'd be able to use:
| BC class | New class | Columns | % |
| - | - | - | - |
| - | .col-1 | 1/12 | 8.33 |
| - | .col-2 | 2/12 | 16.66 |
| .w25 | .col-3 | 3/12 | 25.00 |
| .w33 | .col-4 | 4/12 | 33.33 |
| - | .col-5 | 5/12 | 41.66 |
| .w50 | .col-6 | 6/12 | 50.00 |
| .w66 | .col-8 | 8/12 | 66.66 |
| .w75 | .col-9 | 9/12 | 75.00 |
| - | .col-10 | 10/12 | 83.33 |
| - | .col-11 | 11/12 | 91.66 |
| .w100 | .col-12 | 12/12 | 100.00 |

Having ``.w50, .col-6 { width... }`` together in the css won't be as big and make sure that you could still use the new classes.
Maybe the width-classes could be removed in Contao 7 🤔 .

(We could also introduce breakpoint specific classes as well...)

Either way, rewriting current float to flexbox should happen long-term and would also work with the current width classes.

Wdyt @leofeyer @ausi ?

**Comment by aschempp** [comment]
I would like to see a flex-implementation as well. Not sure we really need columns, a static mix of the existing classes makes most sense to me. But we sure do need responsive classes… because .w25 on a mobile is unusable :D

**Comment by ausi** [comment]
> But we sure do need responsive classes… because .w25 on a mobile is unusable :D

What do you mean by that? Why is `.w25` unusable on mobile?
`.w25` is set to 25%, 50% and 100% at screen min-widths of 1280px, 767px and 0px respectively.

> tho I'd want to think further and would like to introduce col-classes based on the 12 column system.

I’m +1 for using flexbox, but im not sure about the `.col-x` classes. I’d just add some more `wXX` classes like `w20`, `w40` and `w80`.

**Comment by fritzmg** [comment]
I'd still prefer https://github.com/contao/contao/pull/2053

**Comment by leofeyer** [comment]
As discussed in the Contao call, we probably have to use grid because we need float clearing (aka `column-start: 1`). However, we would prefer flex if we can solve the float clearing problem.

**Comment by ausi** [comment]
> we would prefer flex if we can solve the float clearing problem.

I was not able to find a clean (CSS-only) solution to implement `clear: left` inside a wrapping flexbox layout.
We’d need to insert an extra HTML element before every `.clr` widget.

**Comment by leofeyer** [comment]
That's not an option, I guess.
