### ISSUE TITLE
Replace ramsey/uuid with symfony/polyfill-uuid?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1049]
**Description**  

In #985, we have introduced a new dependency on `ramsey/uuid`, which is required to generate a UUID. Since Symfony has introduced a [UUID polyfill](https://symfony.com/blog/introducing-the-new-symfony-uuid-polyfill) a couple of days ago, I wonder whether we want to use this one instead?

We could also use the polyfill instead of our current `Database::getUuid()` method. Or we could use the `Database::getUuid()` method to generate the UUID for the crawler, so we do not need an additional dependency at all?

@contao/developers WDYT?

**Comment by Toflar** [comment]
Using `Database::getUuid()` would suddenly make the crawl command dependent on a database which doesn't make sense to me.
I chose `ramsey/uuid` because it's used in so many projects (1636 dependents as of right now), it's very likely that it's already installed on several systems. E.g. if you use Sentry, you already have it installed ;-)

**Comment by leofeyer** [comment]
Valid point. I just brought it up because Symfony claims that their polyfill is faster. 😄

**Comment by Toflar** [comment]
True, I guess we can live with 1.30x slower though :) It's one dependency more anyway. Whether it's the polyfill or `ramsey/uuid` doesn't really matter to me 😄 But if we can get rid of one, why not!

**Comment by leofeyer** [comment]
No, I'm fine either way, too.
