### ISSUE TITLE
Use/support `public/` folder for Contao Managed Edition

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1088]
Since Symfony 4.4, in a regular Symfony application you would have support for the following structure:

| App | Bundle |
| --- | --- |
| `config/` | `config/` |
| `public/` | `public/` |
| `src/` | `src/` |
| `templates/` | `templates/` |
| `translations/` | `translations/` |

Basically, everything in the bundle is consistent with the application itself.

After [this PR](https://github.com/contao/contao/pull/1085) is merged, the Contao Managed Edition would support the following:

| App | Bundle |
| --- | --- |
| `config/` | `config/` |
| `contao/` | `contao/` |
| **`web/`** | `public/` |
| `src/` | `src/` |
| `templates/` | `templates/` |
| `translations/` | `translations/` |

So only the `web/` folder would be inconsistent with the regular Symfony application _and_ bundle structure.

I know this has been discussed in the past and it was decided against it - mostly to not cause more confusion within the community (I think?). But due to the recent PR I would like to bring it up and discuss it again :)

**Comment by aschempp** [comment]
As far as I know, you can use a different folder and configure the application accordingly? There should be a property in the `contao` bundle config.

**Comment by fritzmg** [comment]
Yep, there is.
```
contao:
  web_dir: %kernel.project_dir%/web
```
However, the question is, if the default should be changed to `public/`, for consistency with current Symfony best-practices and standards.

**Comment by contaoacademy** [comment]
Does this mean that the domain root would have to be set to `/mypath/public`?

**Comment by leofeyer** [comment]
I am up for renaming the `web/` folder to `public/` in Contao 4.9. Not sure about the upgrade path though - how would you upgrade from Contao 4.4 to 4.9 then?

@contao/developers /cc

**Comment by Toflar** [comment]
We can't. It would require to change the DirectoryIndex of your server configuration. I don't see any value. At all.

**Comment by leofeyer** [comment]
Renaming the directory has the same benefit as deprecating the `/app/Resources/config` directory in favour of the `/config` directory. We did not have to do this, either, however we wanted to adjust to the Symfony standards. 🤷‍♂

**Comment by Toflar** [comment]
What? We're talking `web/index.php` to `public/index.php` here, right? How is that related to `/app/Resources`?

**Comment by leofeyer** [comment]
Both are non-required changes that do not have to be done, because the "old" way works just fine. Still we now support the `config/` directory and we have deprecated `app/Resources/config/`, which has no benefit except adjusting to the Symfony standards.

But switching from `web/` to `public/` suddenly needs more benefits than that?

**Comment by Toflar** [comment]
`app/Resources/config` to `config` can be migrated automatically. The DirectoryIndex of the webserver cannot.

**Comment by leofeyer** [comment]
That's true. Still we should think of an upgrade path so we can change this in a future version, don't you think?

**Comment by Toflar** [comment]
I don't think we can. The only way that would work would be to have the `public` directory alongside the `web` directory and that again would mean we have to map everything that's generated into `web`  or `public` vice-versa.

The only option for me here is a hard break. Either we do that in 4.9 LTS or 4.10.

Also note that we cannot just rename a config value because unfortunately there's still quite a few places where `web` is hardcoded. Examples include:

* `Calendar::generateFeed()`
* `News::generateFiles()`

**Comment by aschempp** [comment]
This cannot be changed in 4.9 because of lots of (potential) BC breaks. We can discuss this for 4.10 imho, maybe someone can come up with a clever way (like symlinking `web` to `public` 😉 )

**Comment by contaoacademy** [comment]
Is this change really strategically so great? A lot of blog posts, videos and forum posts would no longer fit.

Especially for inexperienced users there will be a lot of confusion...

**Comment by leofeyer** [comment]
+1 for a hard break in Contao 4.10 then.

**Comment by m-vo** [comment]
I'd rather be able to configure it. So for new projects it would be `public` to be in line with the symfony docs but `web` for existing ones. I don't see any benefit in the BC break. :man_shrugging: 

If we want to change the default, I'd still vote for a config option so that noone is forced to change their server and deployment settings.

**Comment by Toflar** [comment]
You can configure it already. Fixing the mentioned hardcoded ones should be an easy-pick.

**Comment by leofeyer** [comment]
I have removed the hardcoded paths in #1116.

**Comment by kroerig** [comment]
> 
> 
> I'd rather be able to configure it. So for new projects it would be `public` to be in line with the symfony docs but `web` for existing ones. I don't see any benefit in the BC break. 🤷‍♂
> 
> If we want to change the default, I'd still vote for a config option so that noone is forced to change their server and deployment settings.

Perhaps you could implement a migration tool in Contao-Manager.

**Comment by leofeyer** [comment]
As discussed in Mumble on March, 12th, the Contao Manager knows how the user has named its parent directory and could store this in the container. Then it would make no difference how the users name their public directory, as it would be set correctly by the Manager (similar to how it is set to `web` in the current Symfony Flex recipe).

The default in Contao 4.10 should be `public`. If a `web` folder exists, `public` should be a symlink to `web`.
