### ISSUE TITLE
Chosen bei CE Elementtyp sucht nicht auf Optgroup

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1300]
Chosen bei CE Elementtyp sucht nicht auf Optgroup - das hat zur Folge, dass z. B. "slid" nicht den "Slider" findet... man müsste "Umschlag" eingeben, was eher unlogisch ist...

btw: die Bezeichnungen, die im Select zu sehen sind, dürften für den "Gelegenheitsredakteur" nicht besonders aussagekräftig sein - "Umschlag Anfang" gibt es sowohl für Slider als auch für Akkordeon. Ggf. ändert sich das ja mit https://github.com/contao/contao/issues/721

**Comment by aschempp** [comment]
Ich fände es auch gut, die Namen entsprechend anzupassen. Z.B. "Slider – Umschlag Anfang" und "Slider – Umschlag Ende".

**Comment by zoglo** [comment]
_The names have changed for Contao 5.x anyways so it says Slider since it's in the legacy group_

Implemented in #7824  with the new fuzzy search 🙃 will look for the value as well so with the legacy elements with the new translations soonish:
![image](https://github.com/user-attachments/assets/24b019bc-e6f8-4752-8ecb-03719122d81c)

and without:

![image](https://github.com/user-attachments/assets/be778e2a-e3c9-489d-a7ce-5a4b3d117d06)
