### ISSUE TITLE
Allow second user switch

### ISSUE THREAD

**Issue by aschempp** [contao/contao#1409]
As assumed in https://github.com/contao/contao/issues/314, Symfony has fixed the ability to switch to another user a _second_ time in https://github.com/symfony/symfony/pull/35839

We should therefore revert https://github.com/contao/contao/pull/345 in Contao 4.9 (and raise the minimum requirement)

**Comment by leofeyer** [comment]
The fix has not yet been merged upstream, so we still have to wait. And there is yet another problem which the fix does not solve:

1. In the COD, make "h.lewis" a second administrator.
2. Log in as "k.jones" and switch to "h.lewis".
3. Go to the user module and switch to "k.jones".
4. Now the back end top menu says "Go back to k.jones" instead of "Log out". 🤷‍♂

**Comment by aschempp** [comment]
That's correct, you're switching back to the user that initially logged in. I'd say we should just disable the second user switch to the original user.

**Comment by leofeyer** [comment]
As discussed in Mumble on March, 12th, we want to disable the impersonate button that would take the user back to themselves.
