### ISSUE TITLE
Preview bar is scrolled if height: 100%

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1428]
**Affected version(s)**

4.9

**Description**

If the HTML and BODY elements have a height of 100% assigned via CSS, the new preview bar will be scrolled out of the viewport. Tested in Chrome, Safari and Firefox on Mac OS.

**How to reproduce**

```css
html, body {
    height: 100%
}
```

Open a long site of the COD (e.g. Applications) and scroll down.

@richardhj /cc

**Comment by bennyborn** [comment]
I don't see any possibility to fix this but an opportunity. Use a Shadow DOM to encapsulate the preview bar since this will make it's styling independend from the rest of the page and prevent any further problems with any loose selectors the page might come up with ;)

**Comment by aschempp** [comment]
I don't think a Shadow DOM will help. SD is only useful for pre-rendering, but as soon as the element is placed on the site it should still be affected. But I might be wrong here 🤷‍♂ 

However, how does the Symfony toolbar fix this? I'm pretty sure it works in that case too?

**Comment by richardhj** [comment]
Since the Contao toolbar uses `position:sticky`, the toolbar sticks on top as long as it is within the boundaries of the parent element. `html, body { height: 100% }` limits the height of the body to 100vh rather than the true height. 
BTW using `body { height: 100% }` or `html, body { min-height: 100% }` should fix this behaviour.

The Symfony toolbar uses fixed positioning that is not influenced by any parent element.
Sticky positioning is a hybrid of relative and fixed positioning. If we use fixed positioning for our toolbar, the toolbar would overlap the website, until we add a margin-top to #wrapper.

If Shadow DOM helps to encapsulate the styling of the toolbar, I would like to consider changing to it. However, this would not fix positioning the toolbar itself.

**Comment by bennyborn** [comment]
> [...] but as soon as the element is placed on the site it should still be affected

Nope. In a nutsheel the shadow DOM behaves more or less like an iFrame and is perfect for isolating styles ;) That's why it's mostly used for Web Components.

**Comment by leofeyer** [comment]
Neither `html, body { min-height: 100% }` nor `body { height: 100% }` has the same effect as `html, body { height: 100% }` though. Maybe @ausi can help?

**Comment by bennyborn** [comment]
> Neither `html, body { min-height: 100% }` nor `body { height: 100% }` has the same effect as `html, body { height: 100% }` though

Whats the point in changing the problem? The original problem was
```html
html, body {
    height: 100%
}
```
Of course changing the styling to something different solves the problem but I don't think that was your intention ;) Long story short, There is no fix in THIS case as long as the preview bar is sticky. `position: fixed` solves it but intruduces the problem of overlapping the content.

**Comment by leofeyer** [comment]
Yes, but we could fix the overlapping like this:

```css
.cto-toolbar {
    position: fixed;
}

.cto-toolbar--visible {
    width: 100%;
}

.cto-toolbar--visible + #wrapper {
    margin-top: 40px;
}
```

**Comment by bennyborn** [comment]
That would be one solution, but this way you'd alter any `margin-top` that might be given to the wrapper by the theme. IMHO tinkering with the styling of the users theme in any way, shape, or form seems like a bad idea :\

**Comment by aschempp** [comment]
I actually don't think we need that solution. The Sf toolbar overlaps the content as well. Just close the toolbar if you _need_ to see what's behind it?

**Comment by ausi** [comment]
Symfony uses a `<div class="sf-toolbar-clearer">` to add the space of the toolbar to the bottom of the page. I think we should use the same technique.
