### ISSUE TITLE
Remove rememberme hashing with Symfony 5.2

### ISSUE THREAD

**Issue by aschempp** [contao/contao#1515]
Once we support Symfony 5.2 only, we can remove our custom rememberme hashing: https://github.com/symfony/symfony/pull/35960

**Comment by leofeyer** [comment]
@bytehead Is this something you want to work on?

**Comment by bytehead** [comment]
Yes, why not 👍

**Comment by bytehead** [comment]
I don't think we can remove our custom rememberme hashing as the hashing method is private in Symfony 5.2:
https://github.com/symfony/symfony/blob/7fa617d4175e08a3d8e1cb5d67aa4523ad034dd8/src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php#L132

And this service is deprecated since Symfony 5.4 I don't know how much sense this change would make? I would rather replace it by the `PersistentRememberMeHandler` instead (we use Symfony 5.4 in 4.13 anyway). WDYT?

**Comment by leofeyer** [comment]
That would be even better. 👍

**Comment by bytehead** [comment]
As discussed with @aschempp today, we won't update this in 4.13 as there is no benefit. I will exchange our custom RememberMe solution for Contao 5.0. 

Note: Support for parallel requests (e.g. for our ESI requests) was added in 5.3: https://github.com/symfony/symfony/pull/41175

**Comment by leofeyer** [comment]
We are now using the `PersistentRememberMeHandler`.
