### ISSUE TITLE
Anchor for pagination links

### ISSUE THREAD

**Issue by eki89** [contao/contao#1594]
List modules are not always included at the top of a page. But using a pagination link always takes you to the top of the page. What do you think about the possibility to add the id of a list module to links of the pagination as an anchor? The behaviour could be controlled via an additionall checkbox in list modules.

**Comment by bennyborn** [comment]
Since this seems highly dependant on the theme / layout you're using I'm not sure if this justifies an extra setting in the backend. But what about making the pagination template aware about the module it is used in? This way you could alter the template depending on the module type or id to add the anchors yourself accordingly.

**Comment by asaage** [comment]
I usually load some js like 
```javascript
$(window).on('load', function(){
	if (window.location.search.indexOf('page_')>0) {
		$('html, body').animate({scrollTop: $('nav.pagination').first().parent().offset().top - 70}, 600, 'swing');
	}
});
```
which scrolls me to the parent of the (first) pagination if ther is a page_* queryparameter present.
This could be refined to work without jquery and with multiple pagiations on one page.
There is already something similar for form-validation-errors in the ```js_autofocus``` template.

**Comment by leofeyer** [comment]
@eki89 Did @asaage's suggestion solve your problem? If so, please close the issue.
