### ISSUE TITLE
Consider dropping or modifying doctrine schema filter

### ISSUE THREAD

**Issue by m-vo** [contao/contao#1664]
In 22ebe459273a85843be441cc43c614f48224fba6 we added a schema filter to the installer so that only tables starting with `tl_` are processed. I'd like to discuss that decision again or vote for the implementation of configurable exceptions. 

**Consider this scenario:**

There is a Symfony bundle that brings along some entities and a Contao extension wrapping this bundle so that users can easily install and use it (providing a ContaoManagerPlugin, configuration + so on). 

Now the table for the bundle's entities won't get created when calling `contao:migrate` or using the InstallTool. So in order to get things working for Contao users the only way (I can currently think of) is to manipulate the entities name in a `loadClassMetadata` event to include the prefix. This is imo too hacky and could possibly break references.

**Possible solutions**

1. Remove the filter again and simply handle all tables.
2. Allow defining exceptions (e.g. via prepended config) - as the filter can be a function (and not only regex like pre version 2.9) this shouldn't be too hard.

**Comment by m-vo** [comment]
... in the meantime - if anyone is interested. This actually works:

```php
// tagged with { name: 'doctrine.event_listener', event: 'loadClassMetadata' }
class RenameEntityListener
{
    public function __invoke(LoadClassMetadataEventArgs $args): void
    {
        $classMetadata = $args->getClassMetadata();

        if (MyEntity::class !== $classMetadata->getName()) {
            return;
        }

        $classMetadata->setPrimaryTable(['name' => 'tl_my_entity']);
    }
}
```

**Comment by aschempp** [comment]
I think it's a long time since running Contao in the same database as any other tool is a valid use case. I'm all-in for dropping this in Contao 4.10, so anyone with that _deprecated_ requirement can still run 4.9 for another 4 years…

**Comment by ausi** [comment]
Can we detect that case and trigger a deprecation warning in 4.9?

**Comment by m-vo** [comment]
The only thing I can think of is people that *do* want to use doctrine migrations (commited to the repo, with up and down actions) because they are more powerful. In this case Contao should probably not interfere?  (I'm all for dropping in the case of 'Contao as an application'.)

Edit: But in this case you wouldn't use contao:migrate would you? :-)

**Comment by m-vo** [comment]
> Can we detect that case and trigger a deprecation warning in 4.9?

Easiest would probably be to trigger a deprecation from inside the filter callback whenever the filter is applied (or setting a flag).

**Comment by aschempp** [comment]
> Edit: But in this case you wouldn't use contao:migrate would you? :-)

Absolutely not, there's no reason to use both. Also, the Contao tables would show up in your migrations, so it does not work both ways atm anyway.

**Comment by leofeyer** [comment]
As discussed in Mumble on May 7th, we want to remove the filter in Contao 4.10 and not add a deprecation warning in Contao 4.9.

**Comment by m-vo** [comment]
So, we want to drop the part where we overwrite the schema filter in the `Installer` but we want to keep the filtering in our custom schema provider (`DcaProvider`), right?

What we didn't discuss (IIRC): Would this cause a problem with extensions that rely on the fact that tables without the `tl_` prefix are ignored? (I don't think this should be a supported design pattern but it's something that we might want to care for.)

**Comment by aschempp** [comment]
> Would this cause a problem with extensions that rely on the fact that tables without the tl_ prefix are ignored? 

Very good question! I think that was the reason we actually kept this. Maybe people from the metamodels team can answer it?

**Comment by zonky2** [comment]
we'll talk about it tomorrow at the MM call...

**Comment by discordier** [comment]
I do not know if I get this correct now.
You plan on removing the filter and therefore the install tool will offer all third party tables and views for deletion?

If so, I would be happy to register my custom schema in the Schema provider but have some problems then.
As you might know, MetaModels does neither provide DCA files (as they are not needed due to the dynamic nature) nor does it use classes for entities.
We are some third kind, which would make it necessary to register a custom schema provider (or we would be forced to decorate the `contao.doctrine.schema_provider`).

However, IMO such a change is a BC, as the system would now offer to delete tables and views it was previously happy to live alongside with, and therefore should maybe be configurable as "opt out" (with a mention and emphasis in the upgrade instructions) to restore the original behaviour.

Please also bear in mind that there are not only tables like `tl_` (Contao tables) and even `mm_` (MetaModels tables) but also views by third parties.
for example, I know off extensions by @frontendschlampe which use views named `hoff_` which would also break that way, as there is neither a way in DCA to define views nor does doctrine ORM help here using classes.

Therefore there is need for a collective schema building infrastructure, which could consist of a class like the following:
```php
namespace Contao\CoreBundle\Doctrine\Schema;

use Doctrine\DBAL\Schema\Schema;

interface SchemaGeneratorInterface
{
    public function addToSchema(Schema $schema): void;
}

class SchemaProvider
{
    private DcaSchemaProvider $dcaSchemaProvider;

    /** @var SchemaGeneratorInterface[] */
    private array $schemaProvider;

    public function createSchema(): Schema;
    {
        // Call legacy dca provider first.
        $schema = $this->dcaSchemaProvider->createSchema();
        foreach ($this->schemaProvider as $schemaProvider) {
            $schemaProvider->addToSchema($schema);
        }
        return $schema;
    }
}
```
This class would then be called from the installer to generate the correct schema.

We could then adapt to this in extensions and provide the correct schema. Furthermore, we could also tie the minimum dependency on Contao 4.10 and drop our custom schema manipulation routines.

**Comment by aschempp** [comment]
There are already two ways to hook into the schema:
1: the „old“ way using SQL hooks
2: the same procedure Contao uses to add schema information to doctrine. Any extension can do that however they please 

I don‘t see a point in adding yet another (Contao specific) way?

**Comment by Toflar** [comment]
I like the proposal by @discordier. 

> 1: the „old“ way using SQL hooks

That's not really something we want to endorse, right? :) Also, a lot of stuff cannot be done using the old hooks (views, foreign keys...).

> 2: the same procedure Contao uses to add schema information to doctrine. Any extension can do that however they please

That doesn't really work. The problem is that we're asking our own `Installer` class for the schema (`Installer::createSchema()`) to which we inject our own `contao.doctrine.schema_provider`.
@discordier wants to abstract that so we do inject our `contao.doctrine.schema_provider` but this is bascially a chained provider that asks all the tagged providers to work on the schema the way they want.
Sure, every extension developer could decorate `contao.doctrine.schema_provider` but then we end up in decorating hell (which is debugging hell, believe me, I've seen that in e.g. API Platform for the serializer).

I'll mark this `up for discussion` again so that we can get this sorted soon. Maybe we can get Chris to provide a PR if things are clarified ;)

**Comment by leofeyer** [comment]
As discussed in Mumble on June 4th, we want to directly execute the Doctrine schema generator instead of our own, so all bundles listening to the events are notified (currently our schema listener is not applied in the install tool).

**Comment by leofeyer** [comment]
See #2049
