### ISSUE TITLE
Maintenance mode with Multi Domain

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#1705]
I wish the Maintenance mode could be configured for a multi domain environment -
so per domain. ..

**Comment by m-vo** [comment]
This imo would not work with `LexikMaintenanceBundle`.

**Comment by leofeyer** [comment]
AFAIR, @aschempp wants to get rid of the LexikMaintenanceBundle anyway. 😄

**Comment by aschempp** [comment]
Yeah, imho there are different maintenance-types. We've released an extension to htaccess-protect individual root pages yesterday: https://packagist.org/packages/terminal42/contao-root-protection

I think we also need a "maintenance because installation does not work", but that can't rely on a working Symfony application (e.g. during a composer update).

**Comment by m-vo** [comment]
>I think we also need a "maintenance because installation does not work",

IMO that's something that should rather be solved on the deployment/hosting side (or maybe also by the manager by putting an index file in the webroot or replacing the entrypoints or sth like that).

**Comment by leofeyer** [comment]
See #3729
