### ISSUE TITLE
No more blank option in template select menu

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1734]
The ticket got hijacked for a partly related discussion. The new one is here: #1758 🤷‍♂️

**Comment by timgatzky** [comment]
Hi, wo ist definiert, dass "ce_text" das Standard-Template vom Inhaltselement-Typ "Text" ist, ausser in der Element-Klasse ContentText? Oder ist das wirklich noch ce_ + $GLOBALS['TL_CTE'] KEY?

Von dieser Änderung sind ja quasi alle Erweiterungen betroffen deren Template-Name sich nicht aus dem Definitions-Schlüssel in TL_CTE bzw. FE_MOD bildet. (wahrscheinlich Formularfelder auch)

Wäre hier nicht ein Mapping sinnvoll (und auch für das generelle Überschreiben der Standard-Templates) ala: $GLOBALS['TL_TEMPLATES']['CTE']['ce_text'] = 'ce_text_neu';

**Comment by dmolineus** [comment]
@timgatzky Das ist seit Contao 4 per Konvention so vorgegeben:

> Generally, we now require the template names to match the content element or module keys, so if your module has the key taskList, the corresponding template should be named mod_taskList.html5.

https://github.com/contao/contao/blob/master/UPGRADE.md#template-name-changes

**Comment by timgatzky** [comment]
Yup, I know. But this is up for discussion. And now a whole list of extensions break apart with their template names and it fills the database with unneeded information with no fallback to what is the real template (the database only stores ce_text. Empty was a clear state). 
In my opinion this is an outdated behavior with an unneeded restriction to file names or registration keys. Using one template for two almost identical elements is now also not possible anymore. Limitations like this always should have an open back door for fallbacks, backwards compatibility and overwrites.

Using the DCA 'default' setting for a field cannot be applied also, because default only triggers when the field has been saved empty or the record has not been saved yet. But when switching element types the submitOnChange saves the wrong template name (because now there is no blank option but the first template alphabetically applied). And a possible load_callback with regard to the new element type comes too late.
-> In regard to compatibility I would recommand giving the field the blank option back when no matching template file has been found.

**Comment by ausi** [comment]
> I would recommand giving the field the blank option back

The blank option is still there, only the label for the blank option has changed.

**Comment by timgatzky** [comment]
Where is the blank option? (Leos screenhots have no blank option either)
How do I apply it? 

Contao 4.9.3 (raw)
![screenshot_5684](https://user-images.githubusercontent.com/970730/82295954-c82e6900-99b0-11ea-9146-51f6fb860ce9.jpg)
---
The blank option should be applied automatically when no matching template is in the system. Any extension coming with a content element / module or a record based custom content element / module now applies the first template alphabetically with no fallback. 
![screenshot_5682](https://user-images.githubusercontent.com/970730/82296098-f7dd7100-99b0-11ea-9af2-4cc4baee2acb.jpg)

**Comment by timgatzky** [comment]
> > I would recommand giving the field the blank option back
> 
> The blank option is still there, only the label for the blank option has changed.

I would recommand giving the field the blank option back -> when no matching template file has been found.

**Comment by fritzmg** [comment]
@timgatzky this is due to an extension you are using. According to the screenshot, you are not using the default `text` content element, but rather something custom.

When using the default `text` element of the Contao Core, only `ce_text_*` templates will get listed in the template selection.

**Comment by fritzmg** [comment]
> I would recommand giving the field the blank option back

As already said, the blank option is still there, it is just labelled differently now.

**Comment by timgatzky** [comment]
> > I would recommand giving the field the blank option back
> 
> As already said, the blank option is still there, it is just labelled differently now.

Ok. I must be blind. Where is it?

**Comment by fritzmg** [comment]
In Leo's screenshot the first option (`ce_text (Theme 2)` & `ce_text (Bundle, Theme 2)`).

**Comment by fritzmg** [comment]
Another example:

<img src="https://user-images.githubusercontent.com/4970961/82297824-1d677c00-99ab-11ea-8208-840972b1f40c.png" width="375" alt="ce_text">

```html
<select name="customTpl" id="ctrl_customTpl" class="tl_select tl_chosen" onfocus="Backend.getScrollOffset()">
  <option value="">ce_text</option> <!-- « blank option -->
  <option value="ce_text_foo">ce_text_foo (global)</option>
</select>
```

**Comment by timgatzky** [comment]
Got it. This is one of the most unintuitive solutions I've ever seen. With no back door and fallbacks. Changes like this should not be applied in a bugfix version!

Now basically all extensions (not just ours) fall apart when registrations keys differ to the template names. The 'default' DCA setting is obsolete also due to submitOnChange.

Thanks for your time and clearing this.

**Comment by fritzmg** [comment]
> Now basically all extensions (not just ours) fall apart when registrations keys differ to the template names.

No, why should they? Only the label of the empty selection has changed. In your screenshot however, you see _all_ content element templates, not just the templates belonging to that content element. Which means you are using a custom options callback for the `customTpl` field. You need to remove or adjust your own callback.

**Comment by fritzmg** [comment]
Btw. there is one other improvement we could do. Say you have a content element like this:

```php
<?php

/**
 * @ContentElement(category="texts", template="ce_foo")
 */
class ExampleElementController extends AbstractContentElementController
{
    protected function getResponse(Template $template, ContentModel $model, Request $request): ?Response
    {
        // …
    }
}
```

i.e. with a template defined within the service tag, the template selection still looks like this:

<img src="https://user-images.githubusercontent.com/4970961/82298787-8a2f4600-99ac-11ea-8607-85bf4a385832.png" width="375" alt="example_element">

i.e. the blank option is still called `ce_example_element`, instead of `ce_foo`. Since in this case we _know_ the default template name, couldn't we also show that for the blank option here?

**Comment by leofeyer** [comment]
> Since in this case we know the default template name, couldn't we also show that for the blank option here?

@fritzmg Can you create a separate issue (or preferably PR) hereto? Then we can close this issue.

**Comment by fritzmg** [comment]
@leofeyer done: https://github.com/contao/contao/issues/1819

**Comment by leofeyer** [comment]
Thank you. 👍
