### ISSUE TITLE
Frontend-Vorschau für Redakteure funktioniert nicht richtig

### ISSUE THREAD

**Issue by Schmidty2** [contao/contao#1786]
Betroffene Version: Contao 4.9.3

Wenn ein Benutzer mit eingeschränkten Rechten (z.B.: Redakteur) die Frontendvorschau anzeigen lässt, wird diese wie gewünscht angezeigt, inkl. der Vorschauleiste. Wenn der Redakteur die Vorschaltleiste mit einem Klick auf das X am rechen Rand ausblendet, wir die Vorschau beendet, die Vorschauleiste kann nicht mehr eingeblendet werden.

Ich habe folgenden Workaround gefunden:
Wenn man der Backend-Gruppe Redakteur bei den "Erlaubten Mitgliedergruppen" eine Frontend-Mitgliedergruppe zuweist, funktioniert die Frontend-Vorschau auch beim Redakteur wie gewünscht.

Das Ganze lässt sich in der Contao-Demo nachvollziehen.

**Comment by fritzmg** [comment]
Seems to be caused by a JavaScript error here:

https://github.com/contao/contao/blob/7def0fef3327c81c431d42cac11675accad3bb32/core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig#L247

Which will then stop the JavaScript execution and the event listener for the close button later on is never registered. When a non-admin user uses the preview, the user input field will not be present.
