### ISSUE TITLE
Überschreiben des Seitenlayouts an Kindseiten verhindern

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1797]
Überschreiben des Seitenlayouts an Kindseiten verhindern - es wäre schön, wenn es bei gesetzter Checkbox "Ein Layout zuweisen" eine weitere Checkbox gäbe wie "Layout nicht Kindseiten vererben".

Damit könnte man gezielt einzelne "Parentseiten" mit einem anderen Seitenlayout versehen - aktuell müssen alle Kindseiten z.B. auf ein "allgemeines Layout" zurück gestellt werden, wenn eine Zwischenseite in der Hierarchie mal ein anderes Layout bekommen soll.

**Comment by pressi** [comment]
Ein alter Post von mir, etwas ähnliches: 

https://github.com/contao/core/issues/4868#issue-7114711

**Comment by SeverinGloeckle** [comment]
This feature has been implemented by #3419 in a basic way. While you may not explicitly skip a page from the layout inheritance, you can select a custom template for the subpages of each page (as noted in the [Contao manual](https://docs.contao.org/manual/en/layout/site-structure/configure-pages/#layout-settings)).

This way, you can select a custom layout for a page and explicitly select the previous layout of the parent page as the layout for the subpages.

The issue is probably resolved.
