### ISSUE TITLE
Crawler Problem

### ISSUE THREAD

**Issue by dp-designpilot** [contao/contao#1808]
![Bildschirmfoto 2020-06-10 um 16 06 23](https://user-images.githubusercontent.com/57160987/84278815-7f904880-ab35-11ea-804e-432ff83a4ad4.png)
**Betroffene Version**
Contao 4.9.3

**Beschreibung**
Nach 1-2 Stunden warten ist der Crawler immer noch bei 0% und das bei einer frischen Installation von Contao 4.9.3

Ich habe ein paar Module/Erweiterungen installiert, die Seitenstruktur angelegt, die Templates die ich benötige kopiert und das Seitenlayout angelegt und sonst habe ich noch nichts konfiguriert.

Würde mir da jemand freundlicherweise Helfen ?

**Comment by netzarbeiter** [comment]
Für Fragen wende dich bitte an die Community und manchmal kann eine [Antwort](https://community.contao.org/de/showthread.php?77356-Crawler-bricht-nach-kurzer-Zeit-(auch)-in-der-Konsole-ab) auf sich warten lassen.

**Comment by dp-designpilot** [comment]
Spooky hat mir gesagt das ich ein GitHub Issues machen soll und nach dem ich fast 4 Tage im Forum gewartet habe und sich nix getan hat.

Hoster ist : metanet.ch

**Comment by fritzmg** [comment]
You were supposed to give more detailed information about the error you are experiencing in regards to the temp directory. The reason why I suggested to create an issue is because there were other users experiencing an issue with the temp directory when running the crawler, which might be worth looking into. And I assumed you are also experiencing said problem. So far, no one has actually reported this problem in detail as an issue on GitHub.

**Comment by dp-designpilot** [comment]
Ich habe die genau gleichen Probleme wie hier schon erwähnt
[HIER](https://community.contao.org/de/showthread.php?77356-Crawler-bricht-nach-kurzer-Zeit-(auch)-in-der-Konsole-ab)
