### ISSUE TITLE
Seitengenerierung ohne automatischer Artikelerstellung

### ISSUE THREAD

**Issue by planepix** [contao/contao#1994]
**Affected version(s)**

Contao 4.10-RC2

**Description**

Eine neue 4.9.4 installiert. Dann im Manager auf die 4.10.*@RC umgestellt und das Update auf die 4.10-RC-2 ausgeführt.
Nach der Basiseinrichtung wie Theme, Layout und Seiten fiel mir auf, dass beim Erstellen von Seiten nicht mehr gleichnamige Artikel dazu erstellt werden.

**Comment by ausi** [comment]
I can confirm the issue.

I think this can be fixed by changing the line https://github.com/contao/contao/blob/1933140d88d134e0e38a690ea13016c8ed996f16/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php#L135 to:

```php
$pageModel->setRow($dc->activeRecord instanceof Result ? $dc->activeRecord->row() : (array) $dc->activeRecord);
```

**Comment by aschempp** [comment]
In Contao 4.10, articles for the current page are only created if
 1: the page type allows for content composition (= can have articles and content, e.g. a redirect page does not)
 2: the assigned or inherited page layout allows for an article in the module configuration.

If the layout has articles in the `main` section, it will be added to that, otherwise to the first one found in the page layout.

@planepix did you assign a page layout to the page or root page?

**Comment by xchs** [comment]
> did you assign a page layout to the page or root page?

I did that, yes. Doesn't change anything, though.

**Comment by ausi** [comment]
@aschempp the issue is that the array cast `(array) $dc->activeRecord` doesn’t work on `Result` objects, see my fix from above.

**Comment by planepix** [comment]
@aschempp to the root page
