### ISSUE TITLE
Non-existent service "contao.search.indexer"

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#2162]
**Affected version(s)**

Contao 4.10.0

**Description**

I've deactivated the search indexer in my Contao 4.9.5 Installation via `config.yml`:

```html
contao:
    search:
        default_indexer:
            enable: false
```

After update to 4.10.0 with Contao Manager the following error occurs:

```html
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:

The service "Contao\CoreBundle\EventListener\DataContainer\PageUrlListener" 
has a dependency on a non-existent service "contao.search.indexer". 
```

After making a repair via Contao Manager I'm back on 4.9.5.

I activate the search indexer in my `config.yml` and run the update to 4.10 again without any problems.

**Comment by frontendschlampe** [comment]
After update I try to deactivate the search again and the same error occurs after rebuilding the cache. So I can't deactivate the search.

**Comment by leofeyer** [comment]
@aschempp I guess the `$searchIndexer` argument of the `PageUrlListener` should be nullable.

**Comment by aschempp** [comment]
> I guess the `$searchIndexer` argument of the `PageUrlListener` should be nullable.

I investigated this, but I find that rather confusing. The `contao.search.indexer` is an alias to the delegating indexer, which is supposed to forward the content to multiple indexers. If the default indexer is disabled, the respective service is removed. Which results in _no indexers available_ so the `contao.search.indexer` alias is not created.

I think it would be better to always have the `contao.search.indexer` and simply have it not do anything (it does not delegate to any actual indexers) instead of null-checking the service in all places (there are a lot more than just here).

@Toflar @ausi wdyt?

**Comment by Toflar** [comment]
Nope. We've explicitly removed it. It's just possible to not have an indexer at all if search is disabled. That's very normal in Symfony.
You should make the dependency optional.

**Comment by Toflar** [comment]
If you want the service to always exist, we have to introduce a `NullIndexer` that fulfills the interface to which we can alias.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2265 (and https://github.com/contao/contao/pull/2264)
