### ISSUE TITLE
User::setUserFromDb() called multiple times

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#219]
**Affected version(s)**

Contao 4.6+

**Description**  

The `$user->setUserFromDb()` is meant to be called only once per user instance, because it it a rather "heavy" method. However, the `User::loadUserByUsername()` method, which calls `$user->setUserFromDb()`, is executed multiple times now that we are using Symfony security.

**How to reproduce** 

Add `dump($this->username);` in the `BackendUser` class at the end of the `setUserFromDb()` method and log into the back end with a regular user in dev mode.

**Possible fix**

```php
abstract class User
{
	/**
	 * @var User[]
	 */
	protected static $arrInstances = array();

	public static function loadUserByUsername($username)
	{
		if (isset(static::$arrInstances[$username]))
		{
			return static::$arrInstances[$username];
		}

		// existing logic

		static::$arrInstances[$username] = $user;

		return $user;
	}
}
```

This would mean that the `loadUserByUsername()` method would always return the same object instead of creating a new object upon every call.

@contao/developers Do you see any drawbacks in the proposed change?

**Comment by m-vo** [comment]
Why is ``setUserFromDb`` "heavy"? Shouldn't the model calls in there be cached already?

**Comment by leofeyer** [comment]
It still makes no sense at all to execute the same logic four times or more if the result never changes, does it?

**Comment by aschempp** [comment]
This code will not work if a member and user has the same username. I would rather want to find out why the code is called 4 times than just ignore subsequent calls…

**Comment by Toflar** [comment]
I've tracked down this issue and it's because of `BackendUser::getInstance()` which is not a singleton anymore but calls `static::loadUserByUsername()` on every call. Of course there are many places in the back end (same applies for FE btw) where `BackendUser::getInstance()` is called to get the currently logged in user. I think it was done on purpose because if it was a singleton and would store the user object internally we could not track changes done in the security component. Idon't know how to fix this though. /cc @aschempp @bytehead

**Comment by aschempp** [comment]
I'm pretty sure this is wrong. I remember my implementation actually fetched the object from token storage if a user is logged in, which is the correct way to do imho. If token storage is not set or not the correct firewall context, we should still store the singleton.

**Comment by leofeyer** [comment]
See #344.
