### ISSUE TITLE
Time control wrong / counter-intuitive

### ISSUE THREAD

**Issue by AndreasMuellerLiving** [contao/contao#2231]
**Affected version(s)**
Contao 4.4.24 (maybe other versions too)

**Description**
Time control of the elements to the minute is counter-intuitive. The value in the "From" field is OK, the value in the "To" field is intuitively "-2 minutes".

**What I've found out:**
If you want to show elements to the second, the system behaves strangely. E.g. if you want to display an element from "10:00:00" to "10:00:59", you have to add "10:00" in the field "From", but the value "10:02" in the field "To". Even if you argue that the "To"-field contains the first second of the minute the element should not be visible anymore, the value described does not make much sense. Same behaviour, if you define time-strings to contain seconds - the seconds seem to be ignored.

**Comment by fritzmg** [comment]
As already mentioned on the forum, you first need to update to the most recent Contao version, e.g. Contao **4.4.51** in your case at the time of writing.

**Comment by leofeyer** [comment]
> the seconds seem to be ignored

That is correct and intended. The input field accepts the time in the HH:MM format and rounds timestamps to the full minute:

https://github.com/contao/contao/blob/e09d6df8b7ab00c63a80f21dcd906e073e70bb01/core-bundle/src/Resources/contao/library/Contao/Date.php#L625-L633

**Comment by AndreasMuellerLiving** [comment]
OK, understood, thanks @leofeyer.

Still, was able to repoduce the behaviour of the system for the value in the "To" field for Contao 4.4.51.
Adding "03.09.2020 13:38" results in not showing the content as from "03.09.2020 13:37:00" on.

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
> The input field accepts the time in the HH:MM format and rounds timestamps to the full minute:

The input field is not limited to minutes, you can set the time format to HH:MM:SS and enter seconds too. The `start` and `stop` columns of `tl_content` do not get rounded to the minute.

There are two checks in place for the published/unpublished logic. The first one is in https://github.com/contao/contao/blob/1bfa560b95d8d6e5402e9d8c5cc0575cec1c6e34/core-bundle/src/Resources/contao/models/ContentModel.php#L428 this one is rounded to the minute. The second one is in https://github.com/contao/contao/blob/1bfa560b95d8d6e5402e9d8c5cc0575cec1c6e34/core-bundle/src/Resources/contao/elements/ContentElement.php#L290 and this one handles seconds too.

The error occurs because in the `ContentModel` the check `$t.stop>'" . ($time + 60) . "'` is incorrect and should instead be `$t.stop>'$time'`.

**Comment by leofeyer** [comment]
> you can set the time format to HH:MM:SS and enter seconds too. The `start` and `stop` columns of `tl_content` do not get rounded to the minute.

Well that is a bug then. We have agreed on rounding to minutes (see 9d1073a03aebd5f8ca9e15f44417a3310b2bb9bc), so we should do this for content elements, too.

**Comment by ausi** [comment]
> We have agreed on rounding to minutes

AFAIK we are rounding to minutes only for database queries (so that the queries don’t change every second). But we are not rounding to minues for storing time values or for other checks that don’t involve the database.

**Comment by leofeyer** [comment]
> AFAIK we are rounding to minutes only for database queries (so that the queries don’t change every second).

Ok, but that implies that the code in the `ContentModel` class is correct, doesn't it?

**Comment by ausi** [comment]
No, regardless of where we want to round to minutes the code in `ContentModel` is wrong, as written in https://github.com/contao/contao/issues/2231#issuecomment-687428831 :

> The error occurs because in the `ContentModel` the check `$t.stop>'" . ($time + 60) . "'` is incorrect and should instead be `$t.stop>'$time'`.

`$time` is already rounded to minutes there, but the addition of 60 seconds is wrong.

**Comment by leofeyer** [comment]
Sorry if I am missing the point, but the code looks exactly like everywhere else, e.g. here:

https://github.com/contao/contao/blob/426f156f0b871adfbe1c560da44771dde6fceab6/core-bundle/src/Resources/contao/models/PageModel.php#L644-L645

`Date::floorToMinute()` strips the seconds, so the query is "where start is less than minute or stop is more than minute + 60 seconds". It is intended to use `$time + 60` for the stop time.

**Comment by ausi** [comment]
If we go with a simplified example:

1. Start is at 60s
2. Stop is at 180s

As soon as the current time passes 60 seconds the start condition `60 <= 60` matches. When the current time reaches 179 it is floored to 120 and the stop condition `180 > 120` still matches so at 179 it would still be visible. In the next second 180 is floored to 180 and the stop condition `180 > 180` doesn’t match anymore. This is the desired result I think.

If you would use `($time + 60)` the element would already be invisible as soon as the time reaches 120 because the stop condition `180 > 120 + 60` doesn’t match.

> but the code looks exactly like everywhere else

Yes, we would have to change all queries that currently use `($time + 60)`

**Comment by leofeyer** [comment]
Hm, `$time + 60` really does not make sense. But why did we add it then?

**Comment by leofeyer** [comment]
Found this: https://github.com/contao/core/issues/7450#issuecomment-85677446

**Comment by ausi** [comment]
If you would want an element with a stop time of 12:30 to be shown until the end of 12:30 (meaning 12:30:59) you would use `($time - 60)` (minus instead of plus).
