### ISSUE TITLE
Use version strategy for contao-components assets

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2258]
When updating to Contao 4.10 a lot of users and editors stumble over the problem that they still have old assets cached in their browser and thus they need to clear their browser cache in order to get the TinyMCE working again for example.

Since the `be_tinyMCE` template for example uses `$this->asset` anyway, wouldn't it make sense to define a version strategy for these assets, so that the cache can be automatically busted if necessary?

**Comment by fritzmg** [comment]
Though the same problem applies when there are any changes to the back end layout or JavaScript - but for that the version strategy would have no effect.

**Comment by leofeyer** [comment]
Using `$this->asset()` ensures that the `js/tinymce.min.js` file has a version parameter, however, the different `plugin.min.js` files are loaded by TinyMCE itself and I doubt that we can influence that.

**Comment by fritzmg** [comment]
True, I haven't thought of that.

**Comment by aschempp** [comment]
We already use cache busting for assets (I think that's what @leofeyer meant). But yeah, the loaded scripts are the issue, maybe we should adjust them in the `contao-components/tinymce` repo?

**Comment by leofeyer** [comment]
That will not help, because this repo is also one of ours. If at all, you should report it to the TinyMCE devs.

**Comment by aschempp** [comment]
> because this repo is also one of ours

Thats what I mean. We could patch our files.

**Comment by leofeyer** [comment]
We cannot, because `contao-components/tinymce` is simply a distribution repository. The existing `.min.js` files are copied, some resources are removed and some are added. No code is changed.

I am not interested in increasing the effort by fetching the source files, patching them and then running the Grunt task to rebuild the minified files. I used to do this in the past when we added our stripnbsp plugin and it was a PITA.
