### ISSUE TITLE
Icon in preview bar missing

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#2390]
**Affected version(s)**

Contao 4.9 and Contao 4.10

**Description**

Since the latest update on 4.9 and 4.10 the Contao-Icon is missing if the preview bar is closed.

![image](https://user-images.githubusercontent.com/226890/94900505-6705be80-0495-11eb-961b-570fd1fd519b.png)
_Left side pre-update, right side post-update_

The problem seems to be this selector:
```css
.cto-toolbar, .cto-toolbar * {
    all: unset;
}
```

**Comment by fritzmg** [comment]
I am unable to reproduce this in Contao 4.9.7 and 4.10.2.

**Comment by bennyborn** [comment]
It is easily reproducible in the online demo:

![image](https://user-images.githubusercontent.com/226890/94902122-fc09b700-0497-11eb-8343-b9be75572b68.png)

PS: This does not happen in Safari since Safari is the new IE and does not understand any "modern" CSS attributes ;)

**Comment by fritzmg** [comment]
Ah, I am able to reproduce this in Chrome, but I am not able to reproduce it in Firefox 81.0.

The question is: why does Chrome behave this way?

**Comment by bennyborn** [comment]
Because of
```css
.cto-toolbar, .cto-toolbar * {
    all: unset;
}
```
which forces the browser to unset all attributes (except unicode-bidi and direction) on the toolbar itself as well as all of its children? (see [MDN](https://developer.mozilla.org/de/docs/Web/CSS/all))

**Comment by fritzmg** [comment]
And why would that hide the icon?

**Comment by bennyborn** [comment]
Because it unsets the width and height of the svg as well as the fill of its path.

**Comment by fritzmg** [comment]
> Because it unsets the width and height of the svg as well as the fill of its path.

Actually it is not because of `width` and `height`. `unset` simply resets everything to the inherited value, if applicable, or the default value. Thus width and height will remain at 22px as that is the default value for this particular element.

However, Chrome handles `all: unset;` differently than other browser. It seems to regard it as a higher specifity than the attributes it resets.

So if you have:

```css
.foobar * {
    all: unset;
}

.foobar #svg {
    fill: #fff;
}
```

then Chrome will ignore the second directive - even though it has a higher specifity and even though it does not display it as being overridden in the inspector. Thus I think this is a bug in Chrome which we unfortunately will have to work around.

**Comment by m-vo** [comment]
Is this related to this https://stackoverflow.com/questions/46758871/css-reset-via-all-unset-breaks-inline-svg?

**Comment by bennyborn** [comment]
Just a quick update: `all: unset` also does not seem to fix the initial problems.
I have a page where the common styling still effects the preview bar:

![image](https://user-images.githubusercontent.com/226890/95298781-e8d25f00-087c-11eb-9f6d-fef5718e7855.png)


So maybe it would be best to try a different approach all together.
