### ISSUE TITLE
unify backend preview image tumbnail sizes

### ISSUE THREAD

**Issue by Metis77** [contao/contao#246]
In the backend generated image thumbs have lots of different sizes.

max height 50px -> in the filetree
75x50px -> inside ce_image/gallery
dynamic -> for the preview the ce_gallery it depends on the images per row setting.
max width 320px -> for the preview of ce_image

This results in lots of wait time while working in the backend.
- Going into an article can take very long. 
- Going into a content element can also take some time
- in ce_gallery the file picker lags, as the thumbs have to be generated before the selection of several images is accepted.

Therefor I suggest to unify the backen thumbnail sizes, so the have to be generated at least only once and not for each view (ce, ce previe, filetree)

- Maybe setting all preview images to a height of 75px, while keeping the width dynamic would be a good idea.
- this way we have always rows of the same height, what is important in ce_gallery or filetree.
- I would also prefer the slightly increased size form 50px height to 75px height.
- the image cache would stay smaller
- the entire cache could be manually rebuild by expanding the filetree

**Comment by ausi** [comment]
As discussed on Mumble: We should set the size to 100x75 with mode `box` everywhere. For the gallery we can use `img { width: 100px; height: 75px; object-fit: contain; }`

**Comment by leofeyer** [comment]
I have tried to implement this today and here are my findings:

**1. max width 320px**

This does not seem to apply to Contao 4 anymore. The back end preview images are generated in the same height as in the front end, so we do not have to generate two different images.

**2. Cache size**

Actually there has been no improvement regarding the cache size; the number of generated images stayed exactly the same. Only the thumbnails are bigger now with 100x75 instead of 75x50, which of course makes it a little easier to see what is on each image.

**3. object-fit**

`object-fit: contain` generates some pretty ugly results:

<img width="329" alt="" src="https://user-images.githubusercontent.com/1192057/50599409-49fe1f00-0eae-11e9-9f9b-43bdd725b8aa.png">

`object-fit: none` seems to fix these issues:

<img width="332" alt="" src="https://user-images.githubusercontent.com/1192057/50599482-8762ac80-0eae-11e9-9f75-0f431cb18f99.png">

So I guess we should not use `object-fit` at all.

**Comment by Metis77** [comment]
what about `object-fit: cover`?

Will visually crop if necessary and therefore match the way it is now.
The `object-position` is center by default.

**Comment by leofeyer** [comment]
> - the entire cache could be manually rebuild by expanding the filetree

That is not true. The entire **back end cache** could be rebuilt, however, the front end cache would stay completely empty! Right now, previewing an article in the back end generates the image cache for both the back end and the front end, which means that your back end users might have to wait a few seconds longer but your front end users do not have to wait at all. And that is good, isn't it?

**Comment by leofeyer** [comment]
Implemented in 6fff23aa4099e0d75f8896e285f86f54ef1446fb.
