### ISSUE TITLE
Adding "page number" to "Page title" in pagination

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#2523]
For SEO reason, it's better to add page number to Page title in pagination. Because, currently, all pagination pages has same Title.

for example:
https://contao.org/en/news.html                         -> Read the official Contao announcements - Contao
https://contao.org/en/news.html?page_a104=2 -> Read the official Contao announcements - Contao 
be "Read the official Contao announcements - Page 2 of 37 - Contao"

**Comment by asaage** [comment]
You might be right but it's also a little bit problematic.
There could be multiple pageable modules on one page.
For example a news-list with 20 pages of news and an event-list with 30 pages of events...
That would be very cumbersome to give each combination a distinct title since it would be "Page 2 of 600" then if my math is correct.
Maybe you do not want the pure listing-pages to be indexed at all and focus on your detail-pages?
