### ISSUE TITLE
Problem bei zu langen Dateinamen in der Dateiverwaltung 

### ISSUE THREAD

**Issue by herrweiss77** [contao/contao#2575]
Bei sehr langen Dateinamen wird in der Dateiverwaltung (Modal/Iframe) der Radio-Button für die Auswahl verdrängt, d.h. es ist dann unmöglich die Datei auszuwählen. Wäre es möglich die Ausgabe des Dateinamens zu kürzen, damit das Auswahl-Feld immer sichtbar bleibt?

**Comment by fritzmg** [comment]
Can you provide a screenshot to see what you mean?

**Comment by herrweiss77** [comment]
![Bildschirmfoto 2020-12-16 um 10 03 03](https://user-images.githubusercontent.com/44664907/102327458-0eb76680-3f86-11eb-93ee-dbd6b372ea5e.png)

**Comment by ausi** [comment]
Can possibly be fixed by:

```css
.tl_left {
    overflow: hidden;
    text-overflow: ellipsis;
}
```

**Comment by fritzmg** [comment]
@ausi + an additional `white-space: nowrap`, otherwise it would look like this:

![Screenshot_2020-12-16 Dateiverwaltung c49 local](https://user-images.githubusercontent.com/4970961/102329680-969a7200-3f80-11eb-8387-afa5cefe6c99.png)

![Screenshot_2020-12-16 Artikel › Home › Inhaltselemente › Inhaltselement ID 11 bearbeiten c49 local](https://user-images.githubusercontent.com/4970961/102329777-b2057d00-3f80-11eb-8c2d-94c2ec0d4c96.png)

Though unfortunately that makes the file type icon and image size invisible :(

![Screenshot_2020-12-16 Artikel › Home › Inhaltselemente › Inhaltselement ID 11 bearbeiten c49 local(1)](https://user-images.githubusercontent.com/4970961/102330043-001a8080-3f81-11eb-8f1b-e882924fdcb5.png)

**Comment by herrweiss77** [comment]
```
.tl_left {
    word-break: break-all;
}
```

![Bildschirmfoto 2020-12-16 um 10 31 57](https://user-images.githubusercontent.com/44664907/102330586-05c89400-3f8a-11eb-8bb9-2094fc8fd032.png)

**Comment by fritzmg** [comment]
Yeah, I guess we have to go with `word-break: break-all`.

**Comment by ausi** [comment]
`break-all` would break inside words even if there are spaces and hyphens that can be used for better line breaks. I think we should go with:

```css
.tl_left {
  word-break: break-word; /* BC */
  overflow-wrap: anywhere;
}
```

**Comment by fritzmg** [comment]
`overflow-wrap: anywhere` also wraps the file name to the next line though:

![Screenshot_2020-12-16 Dateiverwaltung c49 local(1)](https://user-images.githubusercontent.com/4970961/102333503-6e614200-3f85-11eb-97e3-fe60d988d83f.png)
