### ISSUE TITLE
No root pages with port numbers

### ISSUE THREAD

**Issue by akroii** [contao/contao#2598]
**Affected version(s)**

Contao 4.10.5 (not testet in earlier versions of 4.10. branch)

**Description**
It is not possible to open the website if you enter a port number:
<img width="1168" alt="Bildschirmfoto 2020-12-28 um 11 38 00" src="https://user-images.githubusercontent.com/8830861/103208554-35b85580-4901-11eb-9a6d-1de6c9207f5e.png">
If you add an port number in url field it will be stripped. I'm using https (:8890) under a local environment.

If you enter `sub.test.local:8890` it appears:
<img width="681" alt="Bildschirmfoto 2020-12-28 um 11 32 31" src="https://user-images.githubusercontent.com/8830861/103208406-e2460780-4900-11eb-9c91-2b5aad263539.png">

If you enter `sub.test.local` it appears:
<img width="1305" alt="Bildschirmfoto 2020-12-28 um 10 53 19" src="https://user-images.githubusercontent.com/8830861/103208461-f984f500-4900-11eb-99f4-6d2a4638e911.png">

No error logs will produced
PHP 7.4.9

My mamp config:
<img width="296" alt="Bildschirmfoto 2020-12-28 um 11 44 58" src="https://user-images.githubusercontent.com/8830861/103208950-1ec63300-4902-11eb-82d7-85e1f49a9b94.png">

See discussion here:
[https://contao.slack.com/archives/CJT61P8R1/p1609147484351900](https://contao.slack.com/archives/CJT61P8R1/p1609147484351900)

Composer.json:
```
{
    "type": "project",
    "require": {
        "alnv/catalog-manager": "^1.31",
        "bugbuster/contao-statistic_group-bundle": "^1.0",
        "bugbuster/contao-visitors-bundle": "^1.6",
        "comolo/contao-supertheme": "^3.3",
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "^4.9",
        "fritzmg/contao-lazy-load-element": "^1.0",
        "fritzmg/contao-swiper": "^3.3",
        "heimrichhannot/contao-speed-bundle": "^1.9",
        "inspiredminds/contao-wowjs": "^1.0",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "martin-kozianka/contao-timetags": "^1.0",
        "nerdlichter/contao-image-optimizer-bundle": "^1.0",
        "richardhj/contao-childlayouts": "^1.1",
        "terminal42/contao-inserttags": "^1.9",
        "terminal42/contao-node": "^1.3",
        "zmyslny/contao-wrapper_tags": "^2.1"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}

```

**Comment by frontendschlampe** [comment]
Maybe related https://github.com/contao/contao/issues/2214

**Comment by leofeyer** [comment]
I can confirm the issue:

Domain name (root page)

```
127.0.0.1
```

URL

```
URL: https://127.0.0.1:8001
```

debug:router

```
tl_page.2.fallback   ANY   https   127.0.0.1   /                                                           
tl_page.1.fallback   ANY   https   127.0.0.1   /                   
```

Error message

```
None of the routers in the chain matched this request GET / 
```

Note that the issue does not occur if I leave the "Domain name" field blank.

**Comment by aschempp** [comment]
The first problem is this:

https://github.com/contao/contao/blob/master/core-bundle/src/Routing/Matcher/UrlMatcher.php#L40

`$context->setHost($request->getHttpHost());` needs to be removed because we modified Symfony this way to apply our root page port settings.

Now that Symfony routing works, we need to fix https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/controllers/FrontendIndex.php#L256 because `Environment::get('host`)` returns the host including port, but that no longer matches our root page.

**Comment by aschempp** [comment]
My suggestion would be to add `Environment::get('hostName')` to only get the host without port. We need both, sometimes to generate an URL with port, sometimes to match the root page against the current host. More places I could find quickly:
- https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/classes/Backend.php#L1227
- https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/classes/Backend.php#L1265

**Comment by bezin** [comment]
~~The same happens in 4.9. Applying the change in~~ ~~https://github.com/contao/contao/pull/2673 fixes that.~~
~~The reason why I just realised this now, is that I had entered dns with port in the back-end before we started stripping the port. So only now after I edited the root page and saved it, the port got stripped.~~

My issue had the same effect, but was caused by a different commit, see https://github.com/contao/contao/issues/3783
