### ISSUE TITLE
parse_url() behavior change in PHP 7.4.14 and 8.0.1

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2631]
**Affected version(s)**

Contao 4.10

**Description**

<img width="684" alt="" src="https://user-images.githubusercontent.com/1192057/104328215-e753ab00-54eb-11eb-9a87-269f9fed004e.png">

See https://3v4l.org/pbTGF. This breaks our unit tests:

https://github.com/contao/contao/blob/f850734aa06d2a5941d63c353190dc216d78c499/manager-bundle/tests/ContaoManager/PluginTest.php#L750-L753

I suppose this is the related PHP bug report: https://bugs.php.net/bug.php?id=77423 

@fritzmg /cc

**Comment by fritzmg** [comment]
Having

```
MAILER_URL=smtp://foo@bar.com@127.0.0.1:25
```

is wrong anyway, since the username needs to be urlencoded, i.e.

```
MAILER_URL=smtp://foo%40bar.com@127.0.0.1:25
```

I'll make a PR changing the test accordingly.

**Comment by fritzmg** [comment]
Hm, but this behavior change seems odd to me. So `smtp://foo@bar.com@127.0.0.1:25` now returns a different result for the username and host than `smtp://foo@bar.com:foobar@127.0.0.1:25`?

**Comment by m-vo** [comment]
Yeah, it feels very odd to me as well that host can contain `@` symbols, now, instead of just failing with `false` or (context sensitive splitting, that would include that part to the username instead).

But the docs really say that the function only "tries its best to parse" not that it follows any specification (and parsing URLs is super hard btw).

**Comment by leofeyer** [comment]
I am reopening this issue in case we want to improve the situation beyond #2633. I would stick to `parse_url()` though.
