### ISSUE TITLE
Differ the setting "disable request tokens" in BE/FE behaviour

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#2644]
Some customers working in their backend has big problems with tokens there, because they have some problems with their internet connect (many disconnects) or they have Browser problems or they often make double-clicks - I really don't know exactly what the reasons are.

We can't disable the request tokens in the frontend, because it is a big security risk. 

**Our wish for the new year:** Please enable a new settings field in the contao settings to differ between frontend and backend. Perhaps you can change the current checkbox to a selectbox with the following options:

BlankOption: Enable all tokens
- No tokens (BE & FE)
- No Frontend tokens
- No Backend tokens

This would be great. Thank you a lot.

![request-tokens](https://user-images.githubusercontent.com/5235894/104760961-710cae00-5762-11eb-8ac3-48ce79d73f16.PNG)

**Comment by aschempp** [comment]
Please be aware that request tokens are not related to internet connection issues. This was previously the case (until Contao 4.4) because of the IP Adress. There was a setting to disable IP Address checks up until Contao 4.4, but that is obsolete. 

The request token is stored in a cookie, so maybe a cookie blocker is the problem of your client?
