### ISSUE TITLE
Hide unsaved content elements in the front end

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#2708]
**Affected version(s)**

Contao 4.9 (maybe later)

**Description**

**Folgender Sachverhalt:**
Kopiert man ein Inhaltselement im Backend und fügt es an gewünschter Stelle im Backend wieder ein, dann öffnet sich ja wie gewünscht die Bearbeitungsmaske. In diesem Moment wird das kopierte Element auch schon in der Datenbank angelegt, allerdings mit tstamp=0.
Speichert man das Element aber **NICHT** und klickt beispielsweise dann, weil mach sich vielleicht umentschieden hat :-), auf die Dateiveraltung oder ähnliches, dann ist das Element **ONLINE**! Das Element ist dann solange ONLINE bis man wieder auf irgendeinen Artikel/Modul im Backend in die Detailansicht (childTable tl_content) klickt. Hier wird dann wohl eine Query gestartet und alle Elemente mit tstamp=0 gelöscht!

Ich weiss nicht ob es wirklich ein Bug ist aber wenn der Kunde das Frontend anschaut ist das kopierte Element da und will er es dann im Backend löschen ist es weg! Ist irgendwie inkonsistent.

Meine Meinung:
Wenn das Element im Frontend erscheint sollte es dann auch im Backend da sein ohne das man es gespeichert hat **oder** es sollte im Frontend gar nicht erscheinen...!

Danke und Grüße

**Comment by m-vo** [comment]
I think this is, unfortunately, a limitation of the DC concept. It's always creating a record, then updating it. There is never a non-persisted version/copy.

 The 'revise table' strategy kicks in to clean up unwanted records. But this can only happen for BE requests.

(btw: It's the same if you start editing something without saving it or editing in multiple browser windows.)

**Comment by m-vo** [comment]
We could maybe prevent rendering fragments in the FE if the timestamp is 0, though. 🤔

**Comment by xprojects-de** [comment]
i do not really understand why this has to be a temporary entry in the DB. If you do "copy all" the tstamo is set! So why not if one is copied!?

**Comment by fritzmg** [comment]
If you copy just one element Contao provides you with the opportunity to edit the element directly after copying. Only if you save that element then a `tstamp` is set. If you do not save the element then the element will be removed from the database once you navigate back to the overview of the article's content elements, since its `tstamp` is not set.

**Comment by m-vo** [comment]
> i do not really understand why this has to be a temporary entry in the DB

As I said, that's how the DC currently works. :man_shrugging:  There is no session storage (client or server side). That the element's state is tied to the `tstamp` field is unfortunate. It still works if you consider entries with a `0` in as being exclusively owned by the DC. 

That's why we should IMHO only render FE elements for non-zero values.

**Comment by xprojects-de** [comment]
ok :-)

**Comment by leofeyer** [comment]
> That's why we should IMHO only render FE elements for non-zero values.

Good point.

**Comment by leofeyer** [comment]
As discussed in Mumble on April 8th, we should skip FE elements without a timestamp that do not have a `published` field (e.g. content elements or other elements that have an `invisible` field or no visibility control at all).
