### ISSUE TITLE
Stylesheet media-query missing after css import

### ISSUE THREAD

**Issue by Dancger** [contao/contao#273]
**Affected version(s)**
Noticed in contao 4.6 

**Description** 
Stylesheet media-queries are missing if css is imported

**How to reproduce**
- Create a new stylesheet with media query => (max-width: 979px)
- Export stylesheet
- Delete stylesheet
- Import previous exported stylesheet
- Media-query gone

**Comment by mktcode** [comment]
Confirmed. The exported file is lacking the `@media` keyword in the beginning. This is what the export gave me:

```
screen and (max-width: 979px) {
h1 {
    margin:15px;
    font-size:35px;
    line-height:2rem;
    font-weight:bold;
    font-style:italic;
    text-decoration:underline;
}
}
```

Should be easy to fix. I'll give it a try...

**Comment by mktcode** [comment]
Also, if I manually add the `@media`, the import does not recognize it properly, putting all the css in one format definition, instead of adding all the definitions separately and setting the media query as the global setting for all definitions.

![image](https://user-images.githubusercontent.com/6792578/51305538-7a5fc480-1a3b-11e9-9d81-61628b804ead.png)

![image](https://user-images.githubusercontent.com/6792578/51305558-88ade080-1a3b-11e9-804f-913a4a9db1c2.png)

**Comment by mktcode** [comment]
See: https://github.com/contao/core/issues/7560 and https://github.com/contao/core/commit/a5427f7709826d93b5ad7dcc741ebfdfa8016104

This didn't really fix the issue, if it was expected to enter the media query without the @media keyword back then, as it is the case now.

https://github.com/contao/contao/pull/281 should fix that part of the problem... now to the import.

btw @leofeyer shall I submit PRs for each branch or will you merge that later?

**Comment by mktcode** [comment]
https://github.com/contao/contao/pull/281

**Comment by leofeyer** [comment]
@mktcode Thank you for your contribution! 👍 

> shall I submit PRs for each branch or will you merge that later?

No, the changes will be merged upstream.

> now to the import

I am undecided whether importing the media query is a new feature or a bug fix, because if it was a new feature, we would not add it, as the internal CSS editor is deprecated and does not receive new features anymore.

**Comment by mktcode** [comment]
Furthermore it is a bit more complicated to do... so I'll focus on other things.

**Comment by leofeyer** [comment]
This is complicated indeed, because we would have to distinct the following cases:

**Case A**

```css
/* The media query wraps the entire CSS -> store in tl_style_sheet.mediaQuery */
@media screen {
    body {}
    div {}
}
```

**Case B**

```css
/* The media query wraps only the first CSS definitions -> import as usual */
@media screen {
    body {}
    div {}
}

h1 {}
p {}
```

Therefore – and because of the internal style sheet editor being deprecated – I consider this a known limitation. See 58e17e7451341dde90c6a8683fdb75ce39040bea.
