### ISSUE TITLE
Searching requires a lot of PHP memory

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3045]
**Affected version(s)**

Contao 4.9+

**Description**

If there is a large number of records in the search index, searching for a keyword that occurs often (such as `contao` on contao.org) will require a lot of PHP memory limit.

<img width="332" alt="" src="https://user-images.githubusercontent.com/1192057/120299138-07cda780-c2cb-11eb-8e58-9f7aa26d7bfa.png">

@ausi Maybe we can optimize the query?

**Comment by ausi** [comment]
Made a quick test with the database from contao.org, changing the search query from `SELECT *, …` to `SELECT id, …` brought it down from 580 MB memory and 1.70 seconds to just 2 MB memory and 0.17 seconds.

I would defer loading the rest of the data until it is actually needed as only 10 of the 4534 results get displayed on the page. But this is not really possible while keeping BC, so I would introduce a new method to the search class for Contao 4.12 that returns an object sturcture instead of the result array.

**Comment by leofeyer** [comment]
I have changed the milestone accordingly.
