### ISSUE TITLE
Externe Weiterleitung mit News-Inserttag funktioniert nicht (mehr?)

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#3065]
**Affected version(s)**

Contao 4.9

**Description**

Hallo,

wir haben gerade von einem Kunden die Info bekommen, dass die Weiterleitungen auf Nachrichten (bspw.) als externe Weiterleitung nicht mehr funktionieren. Dieses System ist 4.4, ich kann es aber auch lokal reproduzieren mit 4.9. In der Online-Demo ließ es sich auch reproduzieren.

Im Feld "url" steht `{{news_url::11}}`. Damit landet man bei `/de/de/news-alias` (doppeltes locale). Setzt man ein Slash davor (/`{{news_url::11}}`), geht es und man landet bei `/de/news-alias`. Laut Kunde war das bisher nicht nötig. Wurde diesbzgl. etwas verändert in letzter Zeit (könnte auch ca. 1 Jahr betreffen)?

Das wäre grundsätzlich nicht problematisch, aber in Contao 4.9 können Redakteure ja per DCA Picker News dort auswählen und da landet automatisch kein Slash davor, was zum Fehler führt.

Ciao Defcon0

**Comment by leofeyer** [comment]
Ich kann das Problem mit einem Link-Element und dem Picker nicht reproduzieren. Was genau muss ich machen?

**Comment by Defcon0** [comment]
Wenn du schnell bist, bevor sich die Contao Demo selbst bereinigt :-) : Ruf bitte mal in der aktuellen Contao Demo folgende URL auf:

https://demo.contao.org/extern.html

Was ich gemacht habe:

Neue Seite, Typ "Externe Weiterleitung" und dann in das url-Feld {{event_url::6}} eintragen. Dann https://demo.contao.org/extern.html aufrufen.

Das Ergebnis ist dann:

https://demo.contao.org/en/en/event-detail/contao-north-day.html (doppelte locale "en") -> 404

**Comment by fritzmg** [comment]
This is because these kinds of insert tags return a relative URL without a `/` at the beginning, resulting in the following response header: 

```
Location: en/event-detail/contao-north-day.html
```

This URL is then interpreted relative to the current URL by the client, so if the requested URL is

https://demo.contao.org/en/extern.html

then the resulting URL will be

https://demo.contao.org/en/en/event-detail/contao-north-day.html

@aschempp [fixed this for `terminal42/contao-shortlink`](https://github.com/terminal42/contao-shortlink/commit/0e42f7e95a4804bcb735d5ec2f8d3abdf9833907) by adding `|absolute` to any `{{link` insert tag. However - this would not fix it for event URLs for example.

May be we should discuss using URLs with `/` again? i.e. not removing them from the generated routes from Symfony. Or we make sure that any `RedirectResponse` URL is always absolute (either with Scheme and Host or with a prepending `/`).

**Comment by aschempp** [comment]
> May be we should discuss using URLs with / again? i.e. not removing them from the generated routes from Symfony.

(still) absolutely agree

**Comment by leofeyer** [comment]
At least when redirecting (Location header), URLs should begin with `/` or be absolute.

**Comment by Defcon0** [comment]
Post to avoid staling.

**Comment by fritzmg** [comment]
I have implemented a possible solution in #3468.
