### ISSUE TITLE
Invalid token for a new comment via email link

### ISSUE THREAD

**Issue by 108g** [contao/contao#3069]
**Affected version(s)**

Contao 4.9.15

**Description**

When you get an email notification of a new comment and you click the link (https://www.example.com/contao?do=comments&act=edit&id=1) after the text "Klicken Sie hier, um den Kommentar zu bearbeiten oder zu beantworten" the message Invalid Token always appears.

**Comment by asaage** [comment]
That should only work if you open the link in a browser which is currently logged into the BE.

**Comment by 108g** [comment]
Even if you use a browser in which you are currently logged into the BE the same message comes up. I think the query string rt = ... is missing.

**Comment by fritzmg** [comment]
This is probably a known limitation, since no valid request token for the back end can be generated when the link is created. To solve this, the whole request token check for the back end would need to be reworked, so that it only checks the request token, when it is actually necessary, i.e. when a request changes a data record. Unfortunately since the back end uses `GET` for some of these operations, it is no straight forward.

**Comment by 108g** [comment]
@fritzmg thank you for the detailed information

**Comment by contaoacademy** [comment]
See also: https://github.com/contao/contao/issues/2310
