### ISSUE TITLE
4.11 runs into 310 too many redirects

### ISSUE THREAD

**Issue by ACCakut** [contao/contao#3122]
When installing fresh Contao 4.11 on netcup oder uberspace i run into a 310 "too many redirects" hopping from domain.tld/index.php to it self, flipping from HTTP 2 to 1.1 each time (nginx + apache?) when I install any template (Optimist, MATE, official demo package***)

I did the supposed changes in (the so far untouched) .htaccess and tried changing things in nginx, apache, PHP and Symfony's TRUSTED_PROXIES.

More details in a thread created by me: [https://community.contao.org/de/showthread.php?81161-Frische-4-11-5-Too-many-redirects-Netcup-nginx-Proxy-htaccess-template-HTTPS&p=545880#post545880](https://community.contao.org/de/showthread.php?81161-Frische-4-11-5-Too-many-redirects-Netcup-nginx-Proxy-htaccess-template-HTTPS&p=545880#post545880)

4.9 LTS works fine right from the start without any changes.

***)
SUB-BUG: When installing the official demo package into a minimal installation the SQL-import fails due to the packages missing in minimal. They should be dependencies for the package.

**Comment by ausi** [comment]
Did you set the protocol in the root page of the site structure to `https://`?

**Comment by ACCakut** [comment]
Thanks, that helped! Did not even know that it can be changed there.

I will let this open for a while and someone more experienced decide if it should be closed or somehow fixed (code or the solution is written in the official documentation e.g.)

**Comment by ausi** [comment]
Since Contao 4.11.3 (#2991) the protocol gets set automatically to the correct value if you create the root page via the backend.

But if you import an SQL website template the value stored in the sql file is used. I’m not sure if we can fix this. We could change the protocol of all root pages after the import, but that would probably be unexpected by the user and might cause other issues.

I think the best would be to change the templates to use `https://`, because the risk of an endless redirect is very very low this way IMO.
