### ISSUE TITLE
Rebuilding the search index does not clear search cache

### ISSUE THREAD

**Issue by aschempp** [contao/contao#3127]
**Affected version(s)**

Contao 4.9+

**Description**

Even though I did rebuild the search index in the back end, the front end search for a keyword previously search did lookup the search cache and not show up-to-date results.

Side note: how long are the search results cached for?

**Comment by ausi** [comment]
Side note: Contao 4.12 should not be affected because of #2917

**Comment by leofeyer** [comment]
If you clear the search tables before starting the crawler, the search cache is purged automatically. Otherwise, you have to purge the search cache in the maintenance module after the crawler is finished.

Of course, you could add an Escargot subscriber that purges the search cache when the crawler is started. Not sure if that is worth the effort, though.
