### ISSUE TITLE
Fragments are double encoded

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#321]
**Affected version(s)**

Contao 4.4+

**Description**  

The changes from d13b832578ba9826fce7a0d9970786d7b79d8f3e (see #7829) cause problems. We first urldecode here:

https://github.com/contao/contao/blob/a52821a8bb760a2e4a77fe51ac4dc6f294294aed/core-bundle/src/Resources/contao/classes/Frontend.php#L70-L71

And then again here:

https://github.com/contao/contao/blob/a52821a8bb760a2e4a77fe51ac4dc6f294294aed/core-bundle/src/Resources/contao/classes/Frontend.php#L266

**Correct**: path: `/foo/email/a+b@example.com` -> Input::get('email'): `a b@example.com`
**Wrong**: path: `/foo/email/a%2Bb@example.com` -> Input::get('email'): `a b@example.com`
**Wrong**: path: `/foo/email/a%252Bb@example.com` -> Input::get('email'): `a+b@example.com`

@aschempp @ausi @backbone87 /cc

**Comment by aschempp** [comment]
It looks like `rawurldecode` was added first (in https://github.com/contao/core/issues/6232) and that fix actually removed `urldecode` from the fragments (https://github.com/contao/core/commit/33cee3ba76df184217f7e9c04cb3e055c65bbeb1). So not sure why https://github.com/contao/core/pull/7829 was ever necessary/relevant 🤔

**Comment by ausi** [comment]
As discussed on Mumble this should work correctly:

1. Split the request into fragments by `/`
2. `urldecode()` all fragments
3. when building the alias replace `/` by `%2F` for the affected fragments

**Comment by aschempp** [comment]
Unfortunately, it's a little more complicated. Symfony apparently fixed a similar issue a while ago (https://github.com/symfony/symfony/blame/master/src/Symfony/Component/Routing/CHANGELOG.md#L234) and use `rawurldecode`. They also do decode slashes in the path.

In regards to Contao, this means changing this in Contao 4.4 is not really useful, because in Contao 4.7 we use Symfony and therefore can't fix it the same way. I guess we need to discuss this again.

**Comment by ausi** [comment]
Couldn’t we use the fix from #330 and replace `urldecode` with `rawurldecode`?
Not supporting the `+` char as a replacement for space shouldn’t be a problem if we use `rawurlencode` when outputting the URL IMO. And in Contao 4.7 we cannot support the `+` anyways because of Symfony, right?

**Comment by aschempp** [comment]
Not really. Symfony decodes the whole path, which means we should keep the first `rawurldecode` and remove it from the `Input::setGet`. It will also mean that an encoded slash will become a slash (and therefore a fragment), but that's how Symfony behaves… although it is also how Contao always behaved (since that line was added)

**Comment by leofeyer** [comment]
Fixed in 3327de1a49f617df48a887ffe1c4c81d3c31592e then.
