### ISSUE TITLE
Predefined user rights/user groups

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#3280]
Some predefined user rights/user groups with default rights for e.g. news, events, newsletters etc. would be helpful/timesaving/self-explanatory.

**Comment by fritzmg** [comment]
👎 on this. If you need this for your business, then I think you should create a base setup for yourself, where every thing is set up the way you want it to be by default.

Otherwise I am more in favour of exporting/importing database content via config files (see https://github.com/contao/contao/issues/402).

**Comment by fkaminski** [comment]
> Otherwise I am more in favour of exporting/importing database content via config files (see #402).

Makes sense
