### ISSUE TITLE
Folder names with "." not possible in templates folder

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#3354]
**Affected version(s)**

Contao 4.12

**Description**

After updating from 4.11.x to 4.12 I got an error in Contao Manager and after access to install tool:

```html
Twig\Error\LoaderError:
Tried to register an invalid Contao namespace 'Contao_Theme_XXX.XX_DEFAULT_DE'.

  at /htdocs/vendor/contao/core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php:108
  at Contao\CoreBundle\Twig\Loader\ContaoFilesystemLoader->addPath('/htdocs/templates/XXX.XX_DEFAULT_DE', 'Contao_Theme_XXX.XX_DEFAULT_DE', true)
```

I renamed the folder `templates/XXX.XX_DEFAULT_DE` to `templates/XXX_XX_DEFAULT_DE` and it works. I think there's a problem with `.` in folder names.

**Comment by m-vo** [comment]
We could solve this in multiple ways:

1. Convert all special chars in the path like `.`, `_` to `-` (and the separators to `_`) when creating the theme slug. This has the downside that paths could be ambiguous: `/template/foo/bar.baz` vs `/template/foo/bar-baz`. But slugs remain readable and the file extension in a logical name will always remain distinguishable. [:smile: ]

1. Basically the opposite: Also allow the `.` when parsing names (`'%^@(Contao(?:_[a-zA-Z0-9_-]+)?)(?:/(.*))?$%'`) and filtering out themes (`'%^@Contao_Theme_([a-zA-Z0-9_-]+)/%'`). [:tada:]

1. Disallow special chars in theme paths, or rather, do not find theme paths with these characters in the template locator. Then they won't be added to the loader (and subsequently the template hierarchy). Although this would only be noticeable for Twig (for now), this should IMHO read as "not supported anymore" because I think we might want to reuse the template hierarchy for all of Contao's template discovery/selection in the BE later on. [:rocket:]

All three variants are straightforward to implement I think. It's more of a strategic question. :slightly_smiling_face:

In case you want to vote for any of these suggestions I added emojis in brackets behind the options:  [ :smile: / :tada: / :rocket: ]

**Comment by m-vo** [comment]
We should also consider #3271 when implementing a fix.

**Comment by m-vo** [comment]
Judging by the vote, I'd go ahead and implement this:

> Disallow special chars in theme paths, or rather, do not find theme paths with these characters in the template locator. Then they won't be added to the loader (and subsequently the template hierarchy). Although this would only be noticeable for Twig (for now), this should IMHO read as "not supported anymore" because I think we might want to reuse the template hierarchy for all of Contao's template discovery/selection in the BE later on. 

Should we try to trigger a deprecation warning that will be converted to an exception in the future if a path contains any disallowed characters or should we just ignore it?

**Comment by ausi** [comment]
> Should we try to trigger a deprecation warning that will be converted to an exception in the future if a path contains any disallowed characters or should we just ignore it?

+1 for deprecation.

**Comment by m-vo** [comment]
closing in favor of #3414
