### ISSUE TITLE
Two title attribute in <a> tag on image.html5

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#3385]
**Affected version(s)**

Contao 4.11 and 4.12

**Description**

"image.html5" template produce 2 title toghther in <a> tag. (I used news_latest.html5 in News Archive module that use image.html5.)

`<a href="<?= $this->imageHref ?: $this->href ?>"<?php if ($this->linkTitle): ?> title="<?= $this->linkTitle ?>"<?php endif; ?><?= $this->attributes ?>>`

After removing `<?php if ($this->linkTitle): ?> title="<?= $this->linkTitle ?>"<?php endif; ?>`, still a title remains.

I could not produce it in demo.contao.org (v4.9).

**Comment by fritzmg** [comment]
I could not reproduce this. How did you set the title? In the news itself or in the file manager?

**Comment by hamidpeywasti** [comment]
See this: https://pmtcookware.com/blog

**Comment by fritzmg** [comment]
Yes, but how did you set the title? Did you set it directly in the news' settings or in the file manager?

**Comment by hamidpeywasti** [comment]
I did not set any title to image anyway.
I will examine this further.

**Comment by fritzmg** [comment]
Ah, I see. Yes, I can reproduce it this way (not setting any title anywhere).

**Comment by fritzmg** [comment]
@m-vo I think we need to remove `->setLinkAttribute('title', $linkTitle)` here:

https://github.com/contao/contao/blob/9a1fc0be4cb0530e9fc5ac7ed22341f89f8835d5/news-bundle/src/Resources/contao/modules/ModuleNews.php#L196-L197

Setting both will cause two title attributes to be generated. One via `<?php if ($this->linkTitle): ?> title="<?= $this->linkTitle ?>"<?php endif; ?>` and one via `<?= $this->attributes ?>` in the `image.html5` template.

**Comment by m-vo** [comment]
IMHO it is correct to set `$figureBuilder->setLinkAttribute('title', $linkTitle)`. The problem is the BC layer, or rather, the old templates outputting both `$this->attributes` *and* the title attribute. 

To solve the problem keeping BC we would need to…

1. build the figure once (without adding the `title` link attribute)
2. apply the legacy template data
3. add the `title` link attribute and build again
4. set `$this->Template->figure` to the new one

… both in `ModuleNews` and `ModuleEventList`.

If you agree, I'll provide a PR with the suggested changes.

**Comment by leofeyer** [comment]
Is it really necessary to build twice? Can we not unset `$this->attributes['title']` if there is a link title?

**Comment by fritzmg** [comment]
Yeah, the figure builder generally needs to not populate any attributes for the `image.html5` template, if they are already present in the template itself. i.e. it also should not set `$this->attributes['href']` for example.

**Comment by m-vo** [comment]
We definitely only want to do this for the legacy parts.

 The whole `Figure#getLegacyTemplateData()` method is a BC layer that aims to replicate the old  `Controller::addImageToTemplate` behavior. In there only the following attributes were set: `data-lightbox`, `target`, `rel`. 

So we could also restrict the attributes that get combined into the `attributes` string to the above. But then you won't be able to add more arbitrary attributes (basically a new feature since 4.10). OR we could remove certain attributes from the string like `href` and `title` that were used in the old templates.

**Comment by leofeyer** [comment]
> OR we could remove certain attributes from the string like href and title that were used in the old templates.

👍

**Comment by m-vo** [comment]
> @m-vo I think we need to remove ->setLinkAttribute('title', $linkTitle) here:

I guess you're right :smile:. It was way easier to remove the arbitrary option and (hopefully) fix the BC layer. See #3536.
