### ISSUE TITLE
Twig Templates

### ISSUE THREAD

**Issue by Fruchuxs** [contao/contao#3387]
In alten Feature-Requests und Co habe ich des öfteren gelesen, dass es wohl geplant ist, die Templates mit Twig zu realisieren. Zurück in der Zukunft bei Contao 4, sehe ich immer noch diese "ätzenden" PHP-Templates.
Ist das noch geplant, oder eher nicht?

**Comment by m-vo** [comment]
@leofeyer Shouldn't this issue be closed or which are the 'incompatible features' that are missing? :upside_down_face:

**Comment by leofeyer** [comment]
I figured we would replace all `.html5` templates with `.html.twig` templates in Contao 5. 🙈

**Comment by m-vo** [comment]
Ah yes. We could actually do this once some yet missing BE features are implemented. :+1:

**Comment by leofeyer** [comment]
What exactly is missing?

**Comment by m-vo** [comment]
Most important for the BE is…

* showing the template in the selects if the base template is a Twig template (#3274)
* allow to create new templates in the BE
* better support for editing templates (ideally with support for blocks) and appropriate cache invalidation when saving

We probably still need to allow users to overwrite/extend core templates with `.html5` templates in Contao 5. There are two ways we could achieve this: either by enhancing the old template engine, so that extending Twig templates is possible<sup>*)</sup> - we could go fully Twig then. Or by getting it to work that both variants can be provided - we would then need to maintain both for some time.

<sup>*)</sup> I thought this wasn't feasible but I just had another idea. I'll look into this in the upcoming weeks.

**Comment by ausi** [comment]
> Or by getting it to work that both variants can be provided - we would then need to maintain both for some time.

I’d vote for this solution. Maintaining the html5 templates is not needed for most cases I think, because they are only present for BC and are not used in a new setup.

Also, this would force users to use twig for extending new templates (because there is no BC html5 version). This would be a strong signal to every Contao user that they have to switch to Twig at some point.

**Comment by leofeyer** [comment]
Twig templates will be the default in Contao 5, even though `.html5` templates are still supported.
