### ISSUE TITLE
Standardise the edit icons

### ISSUE THREAD

**Issue by agoat** [contao/contao#3388]
We should standardise the use of all edit icons. Currently they are used in different case.

For example the use of the pencil icon in the **site structure** and **articles**:
![site](https://user-images.githubusercontent.com/1402434/29267800-985efece-80ea-11e7-84e4-881d9fc1ec12.jpg)
![articles](https://user-images.githubusercontent.com/1402434/29267802-9adb8f32-80ea-11e7-9ed6-d5787d802fa9.jpg)

Sometimes the pencil is for **editing the element itself** and sometimes for **editing child elements**. That's confusing. 

We should add a icon for editing child elements or consistently use the _header_ icon for editing elements itself.

I would like to see a new icon for editing child elements, despite I don't know how it should look like.

**Comment by leofeyer** [comment]
> I would like to see a new icon for editing child elements, despite I don't know how it should look like.

I fully agree, however, I have no idea how such an icon should look. It is essential that we find one, though, otherwise I cannot continue to work on contao/contao#5391 and contao/core#4371. So @contao/developers and everyone else: how should an "edit child records" icon look like?

<img width="255" alt="" src="https://user-images.githubusercontent.com/1192057/170532320-59e6d40c-f855-48c6-8d78-9a5e4c83ec06.png">

**Comment by asaage** [comment]
I'd probably use the [parent.svg](https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/themes/flexible/icons/parent.svg) icon and change the colors to grey (top/parent) and yellow (for editing/child-items)

**Comment by aschempp** [comment]
I don't like to think about how an icon should look like, but look at it from UX perspective. If you look at a page tree to edit records, you use the edit icon. If I look at an article tree, 95% of the time I want to edit _the article content_ and therefore click the edit icon. It's not only a matter of icon but also of position. Moving the _edit child records_ operation to the second position would certainly be worse UX.

So _if_ we really have to change this, maybe we should use the parent.svg as the first one, and move the pencil to the second operation?

**Comment by ausi** [comment]
Something in this direction maybe?
![Bildschirmfoto 2022-05-27 um 10 41 00](https://user-images.githubusercontent.com/367169/170664095-63144844-232b-48d4-bd9f-c861ca20f014.png)

**Comment by fritzmg** [comment]
imho this icon does not need an "edit pen" - because the action never brings you into an "edit view". It primarily _lists_ entries (which you then can edit individually). I think I would prefer something like <img src="https://www.hps-training.com/bundles/srhinowthemecontent/icons/combo_boxes.png" width="16"> / <img src="https://user-images.githubusercontent.com/4970961/170719773-9722d140-65cc-4dba-a145-4d951176aa0b.svg" width="16">

**Comment by asaage** [comment]
![This is an image](https://gist.githubusercontent.com/asaage/04a39a3101f8bc8e739b2aeeff74f7d4/raw/15a367e2bbe2c186d88606f3b545547ae03e4e8d/childedit.svg)

**Comment by aschempp** [comment]
Well it *is* editing the content of the article. The operation title(s) also reflect that. Also the _Save & Edit_ button would need to be adjusted.
