### ISSUE TITLE
Missing default values result in exception with strict mode enabled

### ISSUE THREAD

**Issue by ausi** [contao/contao#3399]
**Affected version(s)**

Contao 4.9

**Description**

DCA fields that don’t have a default value and use `NOT NULL` result in an exception when creating a new row. But this only happens in strict mode.

Steps to reproduce:

1. `$GLOBALS['TL_DCA']['tl_content']['fields']['text']['sql'] = 'text NOT NULL';`
2. Update database
3. Create a new content element in the backend
4. ``An exception occurred while executing 'INSERT INTO tl_content (`pid`, `sorting`, `ptable`, `tstamp`) VALUES (1, 1, 'tl_article', 0)': SQLSTATE[HY000]: General error: 1364 Field 'text' doesn't have a default value``

I’m not sure if this should be fixed at all. As @fritzmg [pointed out in Slack](https://contao.slack.com/archives/CK4J0KNDB/p1630326649080600?thread_ts=1630314166.063900&cid=CK4J0KNDB) this is a misconfiguration which can be easily fixed by setting `$GLOBALS['TL_DCA']['tl_content']['fields']['text']['default'] = '';`.

But because it works without errors in non-strict mode, it might be a good idea to fix this in DC_Table and trigger a deprecation so that it keeps working as before.

@contao/developers WDYT?

/cc @rabauss

**Comment by leofeyer** [comment]
> I’m not sure if this should be fixed at all.

It should not. It is a misconfiguration and not a Contao or MySQL bug.

> But because it works without errors in non-strict mode, it might be a good idea to fix this in DC_Table and trigger a deprecation so that it keeps working as before.

The issue is not only caused by DC_Table. There might be a form that stores its submitted data in the DB. And every front end module that writes to the DB is affected as well.

I think the BC solution is to temporarily disable the strict mode in the settings until the code has been fixed.

**Comment by m-vo** [comment]
> But because it works without errors in non-strict mode

There had always been a huge amount of inconsistency about default values for blob/text columns (= columns, where data isn't stored directly in the record) in the past. It was never supported but worked on some systems and versions. I remember that people were even suggesting to set the sql mode to something like `MYSQL40` to get it to work :facepalm:. We need to leave this behind, now. :slightly_smiling_face: 

For Contao, we could maybe improve the DX by directly throwing exceptions if the config is wrong (validation) instead of letting the DB operation fail. Not sure this is easy with all the listeners, hooks and callbacks that can alter the config, though.

**Comment by ausi** [comment]
I think we can close this then. 👍

For future visitors of this issue: If you get an error like  

```
SQLSTATE[HY000]: General error: 1364 Field '…' doesn't have a default value
```

please make sure to set a default value in the DCA config:

```php
$GLOBALS['TL_DCA']['…']['fields']['…']['default'] = '';
```
