### ISSUE TITLE
HTML attributes - case sensitivity

### ISSUE THREAD

**Issue by Pellinger** [contao/contao#3409]
The registration of _allowed HTML attributes_ allows lowercase and uppercase input. The output ist just lowercase. Trying to use the HTML attribute _viewBox_ (contains the upper case letter _B_) was confusing, because it wasn't found in the output.

Or the other way round, the HTML attributes should only be entered and saved in lower case in the settings, because the HTML Attributes are case-insensitive as @ausi  mentioned.

**Comment by m-vo** [comment]
HTML attributes are case insensitive: http://w3c.github.io/html-reference/documents.html#case-insensitivity

IMHO the current behavior is fine.

**Comment by ausi** [comment]
> The HTML attribute viewBox contains the upper case letter B. Not sure if this is interpreted incorrectly somehow.

In the HTML context all attributes are case-insensitive, even attributes inside `<svg>`.
So `<svg viewbox="">` and `<svg VIEWBOX="">` are both valid HTML and the same according to the standard.

> Or the other way round, the HTML attributes should only be entered and saved in lower case in the settings

Agree, we should improve the settings in the back end: If you enter `viewBox` it should be automatically converted to `viewbox` so that it works as expected.

**Comment by Pellinger** [comment]
Both of you were faster than me - I just edited the issue to @ausi statement

**Comment by ausi** [comment]
> If you enter `viewBox` it should be automatically converted to `viewbox`

Done in #3423
