### ISSUE TITLE
Support Directory Structure in Namespaced Twig Paths

### ISSUE THREAD

**Issue by richardhj** [contao/contao#3487]
Currently, the registered Twig templates do not support hierarchy. For example:

| File                                              | Fully-Qualified Twig Path                    |
|---------------------------------------------------|----------------------------------------------|
| `/templates/FooBar/fe_page.html.twig`             | `@Contao_Theme_FooBar/fe_page.html.twig`     |
| `/templates/FooBar/partial/headline.html.twig`    | `@Contao_Theme_FooBar/headline.html.twig`    |
| `/templates/FooBar/partial/container/w33.html.twig`    | `@Contao_Theme_FooBar/w33.html.twig`    |
| `/templates/FooBar/modules/mod_article.html.twig` | `@Contao_Theme_FooBar/mod_article.html.twig` |

While this was always the case for HTML5-Templates (that did not know about hierarchy), we must acknowledge that this behavior might be cumbersome in current practice.

Current practice IMHO involves using "atomic" templates (I borrowed the term from "Atomic Design"). To organize the bulk of templates, we need to support structure in Twig paths. Further, we should make the Twig experience in Contao as seamless as possible for existing Twig developers.

**Comment by fritzmg** [comment]
iirc this was already discussed - but @m-vo will know for sure :)

**Comment by richardhj** [comment]
I think it was voted out. My idea was to simultaneously register the hierarchical and flat template path, but in fact, there are problems of ambiguity.

I first noticed that this will be an issue when I wanted to continue work on #2697. Let's say, I create a template called `contao/templates/Backend/Layout/sidebar.html.twig`. You can only reference it as `@Contao/sidebar.html.twig`, which is super ambiguous. Also, I cannot use the Twig folder (`src/Resources/views`) because those templates won't be extendable by any bundle.

**Comment by m-vo** [comment]
> I think it was voted out.

>  Also, I cannot use the Twig folder

Yes, this was discussed in a call while I was midway implementing it. Initially the design looked like this: You would put your Twig templates where you would normally put them in Symfony land. Then, there is a way to mark them as being "managed" either by moving them in a special directory (like `bundles`, so e.g. `contao`) or by config. The templates would then include the full name with sub directories.

Downside of this is: If you want to extend/overwrite templates, you'll inherit the directory structure. This works kind of well in Symfony where there is no dynamic inheritance and every template change just lives in the application under its bundle's name: `templates/bundles/FooBundle/my/special/structure/base.html.twig`. In our case (where there is no discrimination by the bundle name) you could end up with a lot of different structures. One extension would create a `templates/Module/special_nav.html.twig` template, another might choose `templates/Navigation/Special/navigation.html.twig` or `templates/special_navigation.html.twig`. Is this problem worse? I don't know.

The nice thing with the current implementation is the easy transition from PHP to Twig templates. There *is* the higher risk of name collisions (like at many other places in Contao) but on the other hand you do not have to configure anything.

----

So, either way, it boils down to having a naming convention (for file names or both file and directory names) so that templates are distinct enough but still easily usable. Yes, that's already the case but I think Twig will promote using more and smaller templates, so this will get more important.

For instance: In Symfony/Twig land some people are prefixing their templates with `_` to indicate that these are "template fragments" that aren't rendered directly but being embedded/included by other templates. You would want to make sure that even these little bits have distinct names. If they only make sense for the extension they are shipped with, they should probably include the extension name as prefix or sth.

**Comment by m-vo** [comment]
> For instance: In Symfony/Twig land some people are prefixing their templates with _ to indicate that these are "template fragments" that aren't rendered directly but being embedded/included by other templates. You would want to make sure that even these little bits have distinct names. If they only make sense for the extension they are shipped with, they should probably include the extension name as prefix or sth.

Post script to this statement: If you are using embeds/includes in an extension and you are *not* using the `@Contao/…` namespace but the distinct template name (`@Contao_FooBundle/…`) you would avoid collision but also disallow extending/overwriting it. If this is for some reason intendend (implementation detail), we might want to find a way to ignore certain templates, e.g. with a `.unmanaged` file in the directory or something.

**Comment by richardhj** [comment]
Is this _up for discussion_? We would need a solution for directory structure support. Unsure if this is due for Contao 4 or Contao 5.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to try to support a directory structure (opt-in), e.g. by adding a `.public` file or something alike. There are several problems such as namespaces, overriding templates and alike that need to be solved though.

Generally, we would like to support directory structures.

**Comment by m-vo** [comment]
see #3973
