### ISSUE TITLE
Content element HTML encode =,<, >

### ISSUE THREAD

**Issue by zonky2** [contao/contao#3501]
**Affected version(s)**

Contao 4.9.20 and Contao 4.4.57

**Description**
Content element HTML encode =,<, >
older versions did not do this

![FireShot Pro Webpage Screenshot #604 - 'Artikel Inhaltselemente I demo contao org' - demo contao org](https://user-images.githubusercontent.com/1045318/134769509-f2b59fe6-2abc-4d06-8b51-afa01d0b0c95.jpg)

Workaround: add own dca file tl_content.php with
``` 
$GLOBALS['TL_DCA']['tl_content']['fields']['html']['eval']['preserveTags'] = true;
```

**Comment by fritzmg** [comment]
~~This is already fixed in the current `4.9` branch. I could not reproduce it there at least.~~

// nvm, it is still reproducible there

**Comment by zonky2** [comment]
I have just tried this in the demo approx. 13:15h

**Comment by fritzmg** [comment]
However, if you set **Allowed HTML attributes** to `*` `*`, then only `<` gets encoded (which is expected, I think?).

**Comment by zonky2** [comment]
Nothing should be encoded in the content element HTML - IMHO

What I don't understand is that this is content and not an attribute?

**Comment by fritzmg** [comment]
> Nothing should be encoded in the content element HTML - IMHO

If you don't want anything encoded, you can set the allowed HTML attributes to `*` `*`. And not allowed HTML tags will still get encoded, that has always been the case.

**Comment by leofeyer** [comment]
This is the expected behavior. The HTML field has the `allowHtml` attribute set, so it allows HTML according to your settings.

<img width="441" alt="" src="https://user-images.githubusercontent.com/1192057/137931077-cca4405e-1cba-4a66-a789-25f23fc887f5.png">

<img width="516" alt="" src="https://user-images.githubusercontent.com/1192057/137931114-09638265-ae9e-4112-b2de-6f02f5fbc5c8.png">

Note that `<`, `>` and `=` alone are not valid HTML and are therefore encoded.
