### ISSUE TITLE
Contao 4.12.1 Dutch language missing in backend

### ISSUE THREAD

**Issue by sietsevandreven** [contao/contao#3511]
**Affected version(s)**
Contao 4.12.1

Dutch language is selectable in user settings, but the necessary  files are missing under core-bundle -> src -> Resources -> contao-> languages -> nl

**Comment by leofeyer** [comment]
Unfortunately, the translation is no longer included in Contao 4.12, because no one has been translating the new strings and the completion rate has dropped below 95%. It seems that we have forgotten to remove two files, though.

https://github.com/contao/contao/tree/4.12/core-bundle/src/Resources/contao/languages/nl

**Comment by richardhj** [comment]
Maybe @sietsevandreven can provide missing translations to reach the 95 % threshold again?

**Comment by sietsevandreven** [comment]
@richardhj   I downloaded the EN files from 4.12 and the NL files from 4.11. Compared these and added missing lines. What do I do next? My only experience with Github is posting issues.

**Comment by fritzmg** [comment]
In order to contribute to the Dutch translation of Contao you need to register on [transifex](https://www.transifex.com/signup/) and then request to join the translation team for the [`core-bundle`](https://www.transifex.com/contao/core-bundle/) for example for the Dutch language (and ideally for the other bundles as well).
