### ISSUE TITLE
Contao 4.12 Slovenian language missing in back end

### ISSUE THREAD

**Issue by matejjurancic** [contao/contao#3570]
**Affected version(s)**

Contao 4.12

**Description**

Slovenian language is missing from Back end language options in User Profile. [Completion rate in Transifex](https://www.transifex.com/contao/core-bundle/languages/) is 96.24% or am I looking at the wrong stats?

**Comment by aschempp** [comment]
maybe it was no 96.24% when the current Contao version was released. It should be bundled again in the next build if the completition rate is above 95%.

**Comment by aschempp** [comment]
Also, I'm not exactly sure how this works, but maybe the completition rate for the Contao 4.12 files alone are not above 95%. If you find some time, it would be great if you could contribute to the translation to make sure it's bundled again in the next build 🙃

**Comment by matejjurancic** [comment]
I actually added some missing translations right after 4.12.0 was released and also after 4.12.1. Completion rate was over 95% after each update. So, perhaps I should check somewhere else for 4.12 files alone?

**Comment by leofeyer** [comment]
I found the problem:

<img width="650" alt="" src="https://user-images.githubusercontent.com/1192057/138108089-bf317800-1ed7-4e2d-947d-88baf0691b60.png">

You cannot actually use these values, because they include all Contao versions (currently 4.4, 4.9, 4.11 and 4.12). That is also why there are 12,193 strings in total although Contao 4.12 only has 2,502 translatable strings.

My update script calculates the completion level per Contao version and this is how the stats look like for the Slovenian translation in Contao 4.12: 2,363 of 2,502 strings have been translated, so the translation is 94,4% complete. Maybe you can translate the missing 0,6% or even the missing 5,6%, so we can ship the translation again soon?

**Comment by matejjurancic** [comment]
Ah, now I get it :) it's actually pretty obvious.
I managed to raise the completion rate to 97%, so that translation will be shipped with the next version.
