### ISSUE TITLE
veranstaltungen.xml does not validate

### ISSUE THREAD

**Issue by math-GH** [contao/contao#3572]
The RSS feed of the events does not validate:

See https://validator.w3.org/feed/check.cgi?url=https://contao.org/share/veranstaltungen.xml

![grafik](https://user-images.githubusercontent.com/1645099/136590596-1f7edaae-310d-4b85-9ddd-275ca30bdcdd.png)

**Comment by math-GH** [comment]
Same issue with the English event RSS feed:
https://contao.org/share/events.xml

the other feeds (news and security) are fine.

**Comment by netzarbeiter** [comment]
This events aren't repeated events (Contao 4.12.2).

![contao](https://user-images.githubusercontent.com/1942550/136593250-e21b6bed-5c51-488b-8512-2b7d052b40f5.png)

**Comment by fritzmg** [comment]
True, it's not because of repeated events. It's just that the calendar and news bundle use the event or news detail URL for the `<guid>` - which for these events for example will always be the same, because all these events always have the same URL target.

**Comment by leofeyer** [comment]
To solve this, we obviously cannot use URLs as GUIDs anymore, so we have to come up with an alternative identifier. 

https://validator.w3.org/feed/docs/error/InvalidPermalink.html

@contao/developers What would you prefer?

**Comment by fritzmg** [comment]
> @contao/developers What would you prefer?

[UUIDs for everything](https://github.com/contao/contao/issues/402#issuecomment-473822996) 🙃

**Comment by ausi** [comment]
I think I would add a sequence number as hash to the duplicate URLs like:

```xml
<guid>https://contao.org/de/news/contao-calls-zukuenftig-in-slack.html#1</guid>
…
<guid>https://contao.org/de/news/contao-calls-zukuenftig-in-slack.html#2</guid>
…
<guid>https://contao.org/de/news/contao-calls-zukuenftig-in-slack.html#3</guid>
```

**Comment by math-GH** [comment]
what about to use the database ID of the news/calendar item?

**Comment by SeverinGloeckle** [comment]
> what about to use the database ID of the news/calendar item?

For recurring events, the ID of the calendar event item is always the same, so we'd have identical URLs again.

I'd suggest appending the start date of the recurrence to the ID, preferably as GET parameter:

````php
<guid>https://contao.org/de/news/contao-calls-zukuenftig-in-slack.html?date=2021-10-01</guid>
…
<guid>https://contao.org/de/news/contao-calls-zukuenftig-in-slack.html?date=2021-10-21</guid>
…
<guid>https://contao.org/de/news/contao-calls-zukuenftig-in-slack.html?date=2021-11-12</guid>
````

The parameter name and date format are debatable for sure. In my opinion, using the date is more meaningful than random or sequential IDs.

~~As an additional advantage, such URLs provide the possibility to determine the specific recurrence of the event in the future (which is outside the scope of this topic).~~

~~However, one could argue that such URLs suggest that each URL points to a specific recurrence of the event – which they do in the XML-Feed `<guid>`, but not necessarily when requesting the URL content.~~

Since we are talking about the `<guid>` only, adding the start date in any form to the URL should be fine and doesn't affect the URL of the event in the `<link>` field.

**Comment by leofeyer** [comment]
> I think I would add a sequence number as hash to the duplicate URLs like:
> 
>  In my opinion, using the date is more meaningful than random or sequential IDs.

The problem with both is that the URLs are not valid, because they all generate the same site. Therefore, we should at least use `<guid isPermaLink="false">` to make it clear that the GUIDs cannot be used as permalinks.

> UUIDs for everything 🙃

Sounds like a good alternative, doesn't it?

**Comment by Toflar** [comment]
Imho what @SeverinGloeckle proposed is exactly the way to go. Those are permalinks and it's correct to point there using query parameters because techincally it is the very same resource (the news entry) but a different date.

On top of that, we should actually point to `contao-calls-zukuenftig-in-slack.html` with rel="canonical" like for any other filter parameters like e.g. filtering a product list.

**Comment by ausi** [comment]
> Imho what @SeverinGloeckle proposed is exactly the way to go.

Fully agree, but I think using a hash suffix like `#2021-10-01` instead of a query would be better. (For caching, canonical URLs and so on...).

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to check all GUIDs when generating the XML file and add `#` hashes to make duplicate URLs unique again. If the GUID is no longer the same as the `<link>` URL, we want to add `isPermaLink="false"`.
