### ISSUE TITLE
Remove javascript:history URLs

### ISSUE THREAD

**Issue by ausi** [contao/contao#3586]
From https://github.com/contao/contao/pull/3424#issuecomment-931334841

> We also want to remove all usages of `javascript:history.go(-1)` and other back links from templates (e.g. reader modules).

I think this change should go into 4.13 as it is not a bug.

**Comment by SeverinGloeckle** [comment]
Is there any alternative considered for the JavaScript links?

For typical reader modules, for example, an "Add link" option could be added within the module to configure a real link to a suitable page (e.g. a "Show all news" link).

In my opinion, this would transform a feature removal into a potential improvement.

If this sounds like a useful addition, I can get on it.

**Comment by Toflar** [comment]
We do have a link already. It's the one configured in the news archive. The problem is only if you use multiple, different reader modules. Then we don't know where you came from so the only thing we can do to "go back" is to use the JS history. Which is not the right way to go in many cases if you e.g. access the page directly from a Google result etc.
People can add their own "Go back" or "Got to list" links to a reader page. Just add an additional HTML module or content element after the reader and do whatever you need to do :)

**Comment by fritzmg** [comment]
> We do have a link already. It's the one configured in the news archive.

That's the link for the reader module, not for the list. The "Go back" link would need to point to the page where the list module is present. For which we could add a new setting for in the reader module.

**Comment by Toflar** [comment]
Which is basically the same as just adding another element :D

**Comment by asaage** [comment]
I don't see a way to handle a paginated list view without javascript (go back to page 2 or 3 when i came from there) be it with just another element or a new setting for the reader or list module.
I tried that multiple times an then settled on the standard ```javascript:history.go(-1)```

**Comment by SeverinGloeckle** [comment]
> I tried that multiple times an then settled on the standard javascript:history.go(-1)

Since it is not possible to enter JavaScript into a URL field, this will not work via the backend anymore. The solution would be adding a custom element or modifying the corresponding reader template.

> I don't see a way to handle a paginated list view without javascript (go back to page 2 or 3 when i came from there)

A link labeled as "Show all news" or "Go to news overview" can always link to the first page of a paginated set of items – as it is more of a way to "go up one level" than to "go back one step" – that's what the browser's back button is suitable for.

> Just add an additional HTML module or content element after the reader and do whatever you need to do :)

True, this would be a simple solution. However, allowing to define a link directly in the reader module would provide an easy and "proper" way for editors to add a link.

It's similar to a field like headline: You could add a headline element before the element, but it's more comfortable to define it in the element itself.

Maybe someone can add the _up for discussion_ label so this issue might be briefly addressed in the upcoming Contao call?

**Comment by Toflar** [comment]
Sure :)

**Comment by asaage** [comment]
I don't think there will be a convenient solution to this other than the ```{{link::back}}``` / ```javascript:history.go(-1)```.

1. because of the pagination (i know the browser-back-button but some cutomers might not or argue that it's more userfriendly to have it on the page)
2. "Show all news", "Go to news overview", "go up one level" is simply just not the same as "go back" - the first two are most likely accessible in the standard navigation anyway, the third one might not be suitable depending on your site structure
3. there is a possibility to mix and match multiple archives in different or a single list-module/s so the reader-module does not necessarily know where the user came from.
4. popular extensions like "news-categories" add to the complexity (I don't want to loose any category auto-item then)

What's the reasoning behind removing this anyway? Is it about the ```{{link::back}}``` insert-tag? is it about the ```href="javascript:history.go(-1)"``` or the javascript-nature of this in general?

...
I think i used ```{{env::referer}}``` decades ago to get rid of the js-links but that might not work reliable anymore because of caching, proxying and other things.

**Comment by ausi** [comment]
> What's the reasoning behind removing this anyway?

For me the reason is, that it is bad practice to mess with the browser history. If a user wants go to back in history they should use the history of the browser. For going “back to the overview” there should be a link that always works correctly (even if I got to the page directly via a search engine).

**Comment by asaage** [comment]
> reason is, that it is bad practice to mess with the browser history

I kind of feel the same but i don't think we are messing with the browser-history at all
(that would be ```history.pushState & history.replaceState``` like attaching history states to accordeons, sliders or lightboxes).

We just go back one page and since the link-text has never been “back to the overview” but "Go back" that always worked reliable and as expected. 🤷‍♂️

👉🏼 it usually keeps track of the scroll-position for free (I imagine a "back to the overview"-link would be anoying if the list-module is somewhere down the bottom of the page)

**Comment by m-vo** [comment]
For navigating back you would use your browser's back button
 It's intuitive how this works. To me, a link should not be "history context sensitive".

> 👉🏼 it usually keeps track of the scroll-position for free

Same for the back button. Btw. other things (state, frozen JS, ...) can be affected as well and these behave very differently across browsers. 🙃

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add an optional "overview page" field that will automatically generate a "to the overview" link if set.

<img width="481" alt="" src="https://user-images.githubusercontent.com/1192057/142447811-73d5c53c-4c0a-4f94-9b85-17633e0be3de.png">
