### ISSUE TITLE
Create a SystemLogger helper service

### ISSUE THREAD

**Issue by ausi** [contao/contao#3701]
https://github.com/contao/contao/pull/3458#discussion_r751436071 @fritzmg 

> On that note: since `System::log` is also deprecated - you would proabably need to change any `$this->log` or `System::log` occurrence to:
> 
> ```php
> System::getContainer()->get('logger')->log('…', ['contao' => new ContaoContext(__METHOD__, ContaoContext::GENERAL)]);
> ```
> 
> However, I personally always find this rather cumbersome and still often use just `System::log`, since it's more convenient. May be we could introduce a `SystemLogger` helper service to improve DX here? Follow up PR of course, since out of scope.

**Comment by SeverinGloeckle** [comment]
Creating and wiring the `ContaoContext` for the logger is definitely convenient!

We are using a similar service internally already which I can share in a pull request.

This service also gets the calling method for the `func` parameter via `debug_backtrace` so the developer doesn't have to specify `__METHOD__` on each call (but may optionally define it explicitly). 

Since there are quite mixed views on using `debug_backtrace` in productive code, I wonder if an automatic lookup of the calling method is worth considering for a Contao `SystemLogger`?

**Comment by leofeyer** [comment]
I don't think we should use `debug_backtrace` in production, so I vote -1 on this.

**Comment by fritzmg** [comment]
It would certainly be convenient 😬 but I also don't think it should be used.

**Comment by Toflar** [comment]
`debug_backtrace` shouldn't be too expensive per se. You just have to use the `$limit` parameter to make sure, not the whole backtrace is fetched. It should be pretty quick in that case (https://github.com/php/php-src/blob/90b7bde61507cee1c6b37f153909d72f5b203b8c/Zend/zend_builtin_functions.c#L1664).
You might want to do some measurements yourself.

**Comment by SeverinGloeckle** [comment]
The performance of `debug_backtrace` shouldn't be the issue, especially with a limit (around 2-4 frames is enough) and `DEBUG_BACKTRACE_IGNORE_ARGS`. 

It's more about the `debug` part in the function name. Sadly, I do not know about any other way to get the caller of a method in PHP (besides the stack trace in exceptions, which are not suitable in this case).

That's how our logger is currently resolving the caller for Contao's log context:

````php
private function getCallerMethod(int $depth): string
{
    $dbt    = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, $depth + 1);
    $caller = $dbt[$depth] ?? null;

    return $caller ? $caller['class'] . '::' . $caller['function'] : '';
}
````
