### ISSUE TITLE
Do not create backup if there are no migrations

### ISSUE THREAD

**Issue by aschempp** [contao/contao#3763]
**Affected version(s)**

Contao 4.13

**Description**

If I run `contao:migrate`, the command automatically created a backup even if there are no migrations and no schema changes. I think it shouldn't do that, especially because it will somewhen delete my backups as well.

/cc @Toflar @ausi

**Comment by Toflar** [comment]
That's not a bug at all. It's really a matter of taste here:

1. Always create a backup when running `contao:migrate` no matter if there are migrations or not (current behaviour)

- Advantage: Always backs up the latest changes in the database
- Disadvantage: Takes a bit more time to run even if there are no migrations

2. Only create a backup when `contao:migrate` does have migrations

- Advantage: Quick when you there's nothing to migrate
- Disadvantage: You never get a backup of the latest data when there are no migrations to run


I personally have designed it the way it is now because it was designed with deployments in mind. Every time I deploy, I need to run `contao:migrate` for the database and I always want a backup no matter if it even does migrate any data or not because I think it's a good thing to have it when you deploy a new version of an app.

**Comment by leofeyer** [comment]
> I always want a backup no matter if it even does migrate any data or not because I think it's a good thing to have it when you deploy a new version of an app.

That's true indeed. Although I also agree that not every `contao:migrate` run should create an SQL dump. Sometimes you only run it to check if the DB is up to date.

**Comment by Toflar** [comment]
Yes. Sometimes you want this, sometimes you want the other thing. The question is, what should be the default and I want to keep the current solution as the default because that covers my use case for which I have built the solution in the first place.

**Comment by Toflar** [comment]
I mean, we could implement something like `--backup=none`, `--backup=only-on-changes`, `--backup=always` but then we still have to decide which one should be the default.

**Comment by fritzmg** [comment]
> Sometimes you only run it to check if the DB is up to date.

But in that case you can use `contao:migrate --no-backup`.

**Comment by Toflar** [comment]
If you only want to check it, you would run `--dry-run` in which case no backup is created.

**Comment by leofeyer** [comment]
That sounds good. 👍

**Comment by Toflar** [comment]
What @aschempp wants is "Execute migrations if there are any and only backup if there are changes". This is currently impossible. But even if we introduced that feature, we would still have to discuss if that becomes the new default setting or if always creating a backup remains the default.

**Comment by leofeyer** [comment]
The "if there are any" part can be solved by running `contao:migrate --dry-run` before the actual run. If there are no changes, you would not run `contao:migrate` afterwards.

Not sure if there is a way to adapt this logic in Deployer?

**Comment by Toflar** [comment]
There sure is but I think @aschempp was not talking about Deployer in his case. I think his case is more about the general usage of `contao:migrate` during development.

**Comment by leofeyer** [comment]
I see.

**Comment by aschempp** [comment]
If you always want a backup on every deployment, run `contao:backup` and `contao:migrate --no-backup`. You should force the backup through the command and not "assume" migration does one for you 🤷

**Comment by Toflar** [comment]
Yeah, I'm not gonna invest even more time on this feature anyway so I guess I'll have to take what's there in the end. :)

**Comment by richardhj** [comment]
> I think it shouldn't do that, especially because it will somewhen delete my backups as well.

This sounds like you want different backup destinations.
I personally can imagine using a different folder for doing manual backups than the default folder so that "desired" backups do not get deleted.

**Comment by ausi** [comment]
I think the current version is fine as it is. With `--no-backup` and `--dry-run` there should be all options you need for a custom solution IMO.
