### ISSUE TITLE
Prevent password spraying in ModuleLogin

### ISSUE THREAD

**Issue by aschempp** [contao/contao#3821]
As discussed in Mumble on June 6th, we need to track IP addresses in a table and block them if there are too many invalid login attempts. The number should not be too low (e.g. 20).

We might also be able to use a rate limit bundle for Symfony, although we have to ensure that it only limits failed login attempts and not a large number of successful login attempts.

_Originally posted by @leofeyer in https://github.com/contao/contao/issues/1770#issuecomment-638876316_

**Comment by m-vo** [comment]
We should keep in mind that IP != user entity, especially for organizations that share a single gateway.

**Comment by bytehead** [comment]
I'll assign this to me and check what Symfony Security or possible bundles do offer here.

**Comment by SeverinGloeckle** [comment]
I had given some thought to this a few weeks ago.

As far as I know, there is no out-of-the-box solution for password spraying. However, Symfony 5.2 has introduced a [rate limiter](https://symfony.com/doc/current/rate_limiter.html) that can be used very well for this task.


From my point of view, the following points are important:
- The rate limiter works on failed authentications with one bucket per invalid password (hashed for security).
- If the authentication is successful(!), the bucket is checked - if it is empty, the authentication is invalid.
- It is not visible externally whether the authentication failed because of an incorrect password or because a limit was exceeded.

Using this method, the IP address is irrelevant.

Optimally, the rate limiter can be easily adjusted (e.g. number of tokens per bucket) and also deactivated. An allowlist would also be a good idea.

If you need support, I'm happy to help and/or provide a draft.

**Comment by aschempp** [comment]
Sorry I don't understand the concept. How does a bucket per invalid **password** help, and why is the authentication invalid if the bucket is empty but the password correct?

**Comment by SeverinGloeckle** [comment]
Let's first distinguish between two possible attacks:

- Password spraying: One (or more) common passwords are spammed across many different account names.
- Credential stuffing: A list of common combinations of usernames and passwords (or combinations that have become known through a data breach) are spammed.

Since in both cases the attacks are spread over many different accounts, the existing protection for accounts is not effective (e.g. blocking one account after 3 unsuccessful login attempts).

In the case of **password spraying**, the password can be used to detect related login attempts. For example, if the password _12345678_ has been used 5 times in a short period of time for invalid login attempts, password spraying can be detected.

In this case, it is important that the password leads to an invalid authentication when it is valid - exactly at the point when password spraying has resulted in a hit. In this context, it is important that only an invalid login attempt is visible from the outside so that the correctness of the password is not implicitly recognisable.

With **credential stuffing**, on the other hand, automatic detection is more difficult. Here, either an absolute rate limite for invalid authentications must be used (e.g. a maximum of 10 invalid attempts per minute, after which all attempts are invalid or the login option is deactivated) or it must be possible to establish a connection between the attempts in some form (IP address, request signatures, ...).

**Comment by ausi** [comment]
To keep it simple we could add rate limiting that can limit based on different keys, for example rate limits:

- Per username, a low limit like 5 attempts all 5 minutes
- Per IP address, something higher like 10 attempts per minute
- Per password, this can be pretty low too I think.

But the rate limit per password is very difficult to get right. Because it could itself be used to find out used passwords via timing attacks. So I’m not sure if we should give that a try.

**Comment by aschempp** [comment]
Thanks for the heads-up @SeverinGloeckle. If we only allow one password per bucket, wouldn't that be a problem if I mistype my username (and try again) but entered a correct password?

**Comment by SeverinGloeckle** [comment]
> If we only allow one password per bucket, wouldn't that be a problem if I mistype my username (and try again) but entered a correct password?

Since a bucket contains multiple tokens, a mistyped password is no problem. Assume a password spraying limiter based on a very strict per-password bucket with 2 tokens, adding one token per minute.

**Example 1 (mistyping a password):**
- Authentication with k.jones // pasword
	wrong password, bucket for password "pasword" now contains 1 tokens
- Authentication with k.jones // password
	correct password, bucket for password "password" still has all 2 tokens, authentication succeeds

**Example 2 (detecting password spraying):**
- Authentication with k.jones // pasword
	wrong password, bucket for password "pasword" now contains 1 tokens
- Authentication with h.lewis // pasword
	wrong password, bucket for password "pasword" now contains 0 tokens
- Authentication with j.wilson // pasword
	correct password, but bucket for password "pasword" is empty - authentication fails

In a real application, the bucket should contain a higher amount of tokens – probably around 5 to 10 – and should be [configurable](https://symfony.com/doc/current/rate_limiter.html#configuration).

> But the rate limit per password is very difficult to get right. Because it could itself be used to find out used passwords via timing attacks. So I’m not sure if we should give that a try.

As long as the authentication sends the same response for both an incorrect password as well as for hitting the rate limit, I don't see how a timing attack could detect a used password. Plus, you'd have to know the used password to hit the correct bucket.

**Comment by m-vo** [comment]
@SeverinGloeckle If I get this correctly, using buckets would also protect against denial of service attacks (i.e. noone can login anymore), right?

**Comment by SeverinGloeckle** [comment]
A per-password rate limiter provides a pretty high protection against denial of service attacks targeting the point of authentication.

However, as @ausi suggested in https://github.com/contao/contao/issues/3821#issuecomment-1003576897, there probably should be rate limiting for various events. 

A per username limit however is easy to target with a denial of service attack if you know the username (similar to the current protection logic, which is even easier to deny due to the `(A - 2) * 60 seconds` login limit).

We can try to defend such attacks by prepending an IP address limiter with an initially higher amount of tokens but a slower refill rate than the username limiter. This would block authentication attempts by one or multiple IP addresses for long running attacks before checking/blocking the username. However, IP based limits are tricky and must be both configurable and provide some way of allow list.

Two more notes:
- Since all rate limiters still hit the full application, they do not protect against generic denial of service attacks at all.
- I suggested using "buckets" as a specific (and most flexible) type of rate limiter, but both a fixed and sliding window approach would work as well for most cases. Symfony's documentation provides a nice introduction to the [three rate limit policies](https://symfony.com/doc/current/rate_limiter.html#rate-limiting-policies).

**Comment by ausi** [comment]
> > But the rate limit per password is very difficult to get right. Because it could itself be used to find out used passwords via timing attacks. So I’m not sure if we should give that a try.
> 
> As long as the authentication sends the same response for both an incorrect password as well as for hitting the rate limit, I don't see how a timing attack could detect a used password. Plus, you'd have to know the used password to hit the correct bucket.

If you hit the rate limit, the response will (potentially) be faster because no user gets fetched from the database.

Creating a new bucket (meaning an unused password) could take longer than updating an existing bucket (meaning this password was used recently).

Another problem is, that these buckets would store the (hashed) passwords. So if the server gets compromised, weak passwords could be cracked with a rainbow table attack.

Configurable rate limits for username, IP address and the whole project itself would be enough protection IMO.

**Comment by SeverinGloeckle** [comment]
> Configurable rate limits for username, IP address and the whole project itself would be enough protection IMO.

I agree. It's a good first step and already provides a fairly high level of protection - especially in combination with the already present two factor authentication.

If a specific protection against password spraying should be required, it may be added later on.

**Comment by leofeyer** [comment]
See #5368.
