### ISSUE TITLE
Asset Definition/Integration and Twig Template 

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#3834]
### Description

In previous (php/html5) templates the [assets integration (css/js)](https://docs.contao.org/manual/de/layout/templates/assets/) could be defined specifically:

```
<?php
$GLOBALS['TL_CSS'][] = 'files/myfolder/custom.css|static';
$GLOBALS['TL_JAVASCRIPT'][] = 'files/myfolder/custom.js|static';
?>
```

With Twig templates this is probably not available. 
As an alternative, an optional selection of .css/.js in connection with #3625 (New Content Element "Template") might be desirable.

**Comment by m-vo** [comment]
Long term we should avoid introducing this pattern, because that's IMHO what the response context could be used for. I do like the concept of templates being able to say "I need this resource", but we definitely need to encapsulate that. Accessing a common shared array is a big no-no (and not possible in standard Twig). :smile: 

In the short term we will probably have to add functions like `addCssResource()` and `addJavascriptResource()` that can be called like analogous to the json LD things in a `do` statement:

```twig
{% do addCssResource('files/myfolder/custom.css') %}
```

**Comment by fkaminski** [comment]
Possibly also with pendant to the [previous options](https://docs.contao.org/dev/framework/asset-management/#adding-css-javascript-assets) like |static ?

**Comment by m-vo** [comment]
This functionality was implemented in https://github.com/contao/contao/pull/4657.
