### ISSUE TITLE
Nested content elements

### ISSUE THREAD

**Issue by bezin** [contao/contao#391]
Hello there,

I struggle with the possibilities to structure content in Contao once in a while. Pages, articles an content elements are already great and give us many possibilities to structure our content. However, many times I am missing another level of detail, namely grouping or nesting content elements. 

This is partly implemented with the wrapper content elements of course, but they feel more like a workaround rather than a decent solution (for some cases). So I am looking for a more versatile and editor-friendly way to have nested content elements. I fiddled with the online demo and dev tools to illustrate my ideas: 

<img width="600" alt="sketch_dc_parent_view" src="https://user-images.githubusercontent.com/4400435/54029671-7afa1900-41a9-11e9-8ad2-12942c119e2c.png">

<img width="599" alt="sketch_dc_edit_view" src="https://user-images.githubusercontent.com/4400435/54029670-7afa1900-41a9-11e9-908b-92c7f2c16b8a.png">

Editing nested content elements (2nd screenshot) could then open in a modal window (issues ahead, see below).

[As I read in a fairly old issue](https://github.com/contao/core/issues/1247#issuecomment-374533143) the core team seems to have thought about this as well. I would like to hear what your ideas are?

I guess, wrapper elements were kind of a compromise to achieve element grouping within the constraints of the given Contao framework back when they where implemented. I also know that my sketched idea fails right away, when you would like to nest nested content elements, which is a Must requirement for a future solution in my opinion. 

 I am really looking forward to comments in any direction :-) Please treat the screenshots as what they were intended to be: As basic sketches that are totally not thought through ;-)

Cheerio

**Comment by planepix** [comment]
Hi bezin,
have a look at this bundle ( https://gitlab.com/tricksiebzehn/trk17columns ) for have a better visualisation of grids in backend.
![backend-view-bootstrap](https://user-images.githubusercontent.com/1823889/54051084-37230600-41e1-11e9-93b1-e4e71658a18d.png)

![backend-view-bootstrap2](https://user-images.githubusercontent.com/1823889/54051145-646fb400-41e1-11e9-9e80-a86d381eda90.png)
You can switch in backend to see the result for different widths

**Comment by asaage** [comment]
I think Wrapper-elements like *Accordion (Wrapper start/stop)* & *Content slider (Wrapper start/stop)*
are a pretty fine solution - i'm just **missing a generic one in the core** to just wrap elements and attach a class/id.
An Improvement would definitely be:

- auto-creation of the stop-Element
- synced un/publishing of start&stop Elements
- some kind of feedback in case the nesting got messed up (missing stop or overlapping stop/start for example)

Probably 1st could be done with a oncreate_callback 2nd and 3d with some BE-javascript.

When i think of "**Nested content elements**" i wonder what would be the usecase of nesting a *ce_text* a *ce_download* and a *ce_hyperlink* inside a *ce_image* for example? That doesn't work. How would one visualize this in the UI and what should be atomic?
You will pretty much allways need a "stupid" container/wrapper or a tailored composite/custom-Element if we don't want to add (3times) another layer parenting Contentelements.
- Page
  - Article
    -  Contentelement
- Calendar
  - Event
    -  Contentelement
- News (Archive)
  - News (Item)
    -  Contentelement

**Comment by bezin** [comment]
@planepix thanks for sharing, i did not know about this extension. However, grids are only one example…

@asaage 
> When i think of "Nested content elements" i wonder what would be the usecase of nesting a ce_text a ce_download and a ce_hyperlink inside a ce_image for example?

I guess there is no usecase for your example (or is there, anyone?) ;-) But this is not what this issue is about, because I am absolutely talking about the necessary ("stupid") container elements. For example, it would be nice to have a single slideshow element, but still be able to compose each slide of different content elements. This slideshow element would probably need to have a field ```slides``` where we store the order and the id of content elements. 

This would approve some things in my opinion that are superior to our current wrapper elements: 
A slideshow is treated as a single element, that
– can be moved around by drag and drop rather than copying & pasting around a bunch of elements with "edit all"
– un/published with one click
– referenced with insert elements or the include module. 
– is easier to grasp for editors, because they do not have to think about proper nesting of elements themselves. 

Looking forward to other comments :-)

**Comment by fritzmg** [comment]
> Hi bezin,
> have a look at this bundle ( https://gitlab.com/tricksiebzehn/trk17columns ) for have a better visualisation of grids in backend.

I like the visual concept of this extension.

**Comment by dmolineus** [comment]
I invested some time in the idea of nested content elements some time ago (see [netzmacht/contao-content-node](https://github.com/netzmacht/contao-content-node) and [contao-bootstrap/grid-element](https://github.com/contao-bootstrap/grid-element)).

**Current situation**

 * Sometimes another level wrapper element is required to organize content
 * Current wrapper elements are irritating for most users especially if they get a nested structure
 * Moving blocks gets difficult if you have many elements in a wrapper based structure

That's why I would prefer a node based content structure with following requirements.

**Content structure**

 * Each content element of a page would be a content node
 * Articles would be just special type of a content node
 * A node may contain any other content nodes
 * A node should limit which sub nodes could be added
 * A node may defined blocks where content nodes could be added (Example: Content Node Header with place for a headline and a teaser text)

**Usability**

 * Drag & drop should be easily possible to reorganize content
 * A breadcrumb could help to show just a part of the content structure
 * ...

I know which is a big step away from the content structure and it's just my personal point of view. But maybe it could implemented as a special page type besides the regular page. So the features for it could grow slowely. Maybe it could be also a chance to introduce a future version of a data container driver as it doesn't have to care about backwards compatibility.

**Comment by ngdot** [comment]
I think the first step should be improving the usability of the existing wrapper elements, before changing the current look & feel of creating content.

The above suggestions by @dmolineus @asaage & @bezin sounds great for me! 

Also the illustration from @bezin looks good for me.

In my current solution I added some bigger spacing to the wrapper elements and some colors, so it's much easier to see what is going on here :D 

![wrapper](https://user-images.githubusercontent.com/8327905/54195890-249a1c80-44c0-11e9-86e2-d4ed303607bb.jpg)

**Comment by m-vo** [comment]
I think two things are important when trying to improve on the current wrapper elements: a UI that restricts invalid configurations (e.g. no stop element but a visual nested block) and a true relation of the elements when rendering (e.g. the wrapper knows it's children), so that I could have a single wrapper template.

I like the abstract way: grouping things should be a semantic decision, how the frontend displays it (e.g. as accordion or columns or slider) is a design decision and depends on the selected theme.

**Comment by patrickjDE** [comment]
> a true relation of the elements when rendering (e.g. the wrapper knows it's children), so that I could have a single wrapper template.

This simply won't work with the current approach of start and stop elements.

I've also been experimenting with a simple way to nest arbitrary elements. It's just a rather hacky POC abusing dynamic ptables, but if anyone's interested to take a look: https://gitlab.com/patrickjDE/contao-megalements

**Comment by m-vo** [comment]
> This simply won't work with the current approach of start and stop elements

Of course it does not. But that's the point of this discussion, isn't it? 🙃

**Comment by asaage** [comment]
https://github.com/contao/contao/issues/451#issuecomment-494436980
Haven't tried it myself but contao-node might be a decent drop-in solution without start and stop elements.
