### ISSUE TITLE
Should events and other things be logically grouped or in a common namespace?

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3923]
One issue unrelated to the functionality: In my opinion, the events would be better off in their own sub-namespace (e.g. `Contao\CoreBundle\Event\Twig`, `Contao\CoreBundle\Event\Template` or similar).

Since more and more events will be added, we should start structuring the namespace rather sooner than later.

_Originally posted by @SeverinGloeckle in https://github.com/contao/contao/issues/3913#issuecomment-1010841767_

**Comment by m-vo** [comment]
As discussed on the Contao Call on 13th of january we want to use logical grouping by 'components' in the future. So rather `Twig/Event/FooEvent` than `Event/Twig/FooEvent`. This also holds true for other things like exceptions.

**Comment by SeverinGloeckle** [comment]
Not to be petty,  but in https://github.com/contao/contao/pull/3774, the added events can now be found in `Contao\CoreBundle\Filesystem\Dbafs`.

In my opinion, they should rather be located in `Contao\CoreBundle\Filesystem\Event` or `Contao\CoreBundle\Filesystem\Dbafs\Event`, whereas I would prefer `Contao\CoreBundle\Filesystem\Event`  in order to be able to quickly see the available events, at least within a component.

**Comment by m-vo** [comment]
I decided against another sub namespace because it's only two files and they already contain the word `Event` in their name. Same for the exception btw.

The events are specific to the Dbafs, so it would IMHO only make sense when moved to `Contao\CoreBundle\Filesystem\Dbafs\Event`. Personally I'd leave them where they are now.

@contao/developers any opinions?
 👍=leave like it is, 👎=change to.. (please comment)
