### ISSUE TITLE
Problem with deactivated search indexer

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#3965]
### Affected version(s)

4.13.0-RC1

### Description

After updating to Contao 4.13.0-RC1 and disabled search I got the following message in Contao Manager:

```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:

The service "contao.crawl.escargot.search_index_subscriber" has a dependency on a non-existent service "contao.search.indexer".
```

I deactivated the search in `config.yml` like this:

```
contao:
    search:
        default_indexer:
            enable: false
```

After communication on [Slack](https://contao.slack.com/archives/CK4J0KNDB/p1642586135098200) I got the hint using this deactivation settings:

```
contao:
    search:
        listener:
            index: false
            delete: false
```
Now I get no message after update.

What will be the right way?

**Comment by m-vo** [comment]
There is also `contao.localconfig.enableSearch`. We should probably take a look at this when resolving the issue and consider triggering a deprecation when using an outdated config (whichever is the right one).

**Comment by aschempp** [comment]
I don't think the legacy config works anymore, it has become obsolete with the indexer. Same as e.g. the URL suffix.

**Comment by Toflar** [comment]
I know what to do here and will provide a PR after my holidays.

**Comment by Toflar** [comment]
I don't know what information you received on Slack but it was completely wrong. Both configurations are correct and they have a completely different function.

```yaml
contao:
    search:
        default_indexer:
            enable: false
```

This disables the default serach indexer that is shipped with Contao. It's the same as if you did `contao.localconfig.enableSearch = false` in the past (which by the way still works but is deprecated). However, compared to previous versions that does not mean, that search is entirely disabled. It just means the core indexer is disabled but as we have an abstraction for that now (that's what `contao.search.indexer` is, it's a collection of indexers that forwards to all of them), there might be `n` extensions that provide their own search indexers (if you want to index to ElasticSearch or whatever).
If you disabled the `default_indexer` and no other extension provides any indexer, **then** the search is completely disabled. In other words, the `contao.search.indexer` service is removed.
In that case, it also makes no sense to have a subscriber for the crawler. This needs to removed from the container then too which has always been the case but due to service renaming in https://github.com/contao/contao/pull/3706, the bug was introduced because the service name was not correctly adjusted everywhere. This is the bugfix over at: https://github.com/contao/contao/pull/4005

This configuration

```
contao:
    search:
        listener:
            index: false
            delete: false
```

allows to configure the `kernel.response` listener. This is the one that `index`es or `delete`s from the search index on every response that is generated by Contao. This is optional. If you only want to update your search index with the crawler instead of every page load (performance reasons) you can disalbe `index`. If you also want to disable removing entries from the search index on every 404, you can also disable `delete`. 
However, if there is no search indexer (again "If you disabled the `default_indexer` and no other extension provides any indexer") the listener is removed anyway (because it makes no sense to have it, Contao optimizes everything for you!) then this configuration is completely irrelevant.

By the way: I've documented it all here https://docs.contao.org/dev/framework/search-indexing/#triggering-the-search-index

**Comment by m-vo** [comment]
>  It's the same as if you did contao.localconfig.enableSearch = false in the past (which by the way still works but is deprecated)

It seems we're not triggering deprecations for the `localconfig` config node, yet. Probably because it's a variable node. But maybe we should do this in a validate callback? Wdyt?

**Comment by Toflar** [comment]
We are, when you access it in `Config::get()`. But when setting. Sure, you can give it a try :)

**Comment by fritzmg** [comment]
> It's the same as if you did `contao.localconfig.enableSearch = false` in the past (which by the way still works but is deprecated).

This is actually not the case currently, as far as I can see. Should we may be extend the `ContaoCoreExtension` to set `contao.search.default_indexer.enable` to `false` if `contao.localconfig.enableSearch` was set to `false`?
