### ISSUE TITLE
Improve backend usergroups settings - allowed fields

### ISSUE THREAD

**Issue by planepix** [contao/contao#401]
**Description**  
As discussed at Contao Agenturtag it would be helpful to have:
1. a better grouping of allowed fields to get faster all necessary fields for individual usergrup setups
2. check if it possible to add "ce_access" ( https://github.com/terminal42/contao-ce-access ) into the core. 
So may be 3. have an option to export usergroup settings and import them into another installation

**Example**

**Comment by contaoacademy** [comment]
Maybe it would be great, if there are some default-groups for often used permissions.

**Comment by leofeyer** [comment]
There are separate tickets for no. 2 and 3, therefore we only need to discuss 1 here. How would a "better grouping" look like? The fields are grouped by table at the moment.

**Comment by m-vo** [comment]
The related issue discussed at Agenturtag was: 'Could we have a way to restrict content elements / access per page tree?'. So that it would e.g. be possible to have one tree with the common text elements and another one that only contains certain custom elements.

**Comment by leofeyer** [comment]
As discussed in Mumble on May 9th, we cannot think of a better way to group the allowed fields than grouping them by table.

Since there are separate tickets for no. 2 (see https://github.com/contao/core-bundle/pull/1560) and no. 3 (see https://github.com/contao/contao/issues/402), I am closing this ticket.
