### ISSUE TITLE
File/Folder deletion despite no session

### ISSUE THREAD

**Issue by Vec7or** [contao/contao#416]
**Affected version(s)**
Contao-Version: 4.7.2
PHP-Version: 7.2.16

**Description**
Deleting a file/folder inside the contao backend file-manager is possible despite the session being expired.

**How to reproduce**
1. Open the contao backend file-manager.
2. Wait until the backend session has timed out.
3. Delete a file/folder of your choice
4. You will be logged out since your session has expired, but once logged back in the file/folder will have been deleted.

**Expected behaviour**
The logout should take place without deleting the file/folder.

**Comment by leofeyer** [comment]
I was not able to reproduce this, but I think I know what happened:

> 3. Delete a file/folder of your choice
> 4. but once logged back in the file/folder will have been deleted.

When you are redirected to the login screen,  Contao adds the previous URL as referrer URL, so it can take you back there after you have re-logged in. This referrer URL is the URL to delete the file – and it is actually only executed after you have re-logged in.

**Please try the following to verify:**

1. Open the contao backend file-manager.
2. Wait until the backend session has timed out (or delete the `PHPSESSID` cookie).
3. Delete a file/folder of your choice (you will be logged out since your session has expired)
4. **Manually remove the `?referer=…` fragment from the URL.**
5. Log back in

Is the file still there?

**Comment by Vec7or** [comment]
You are absolutely right. I completely forgot to check the get and post parameters before opening the issue. Sorry for the inconvenience, works as expected.
