### ISSUE TITLE
News archive All items only show past items

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#419]
**Affected version(s)**
- 4.4
- 4.7

**Description**  

The news archive have the option to show all items if no period is selected. However, it only shows past items as it still limit to an end date. Shouldn't not also future event being visible?

https://github.com/contao/contao/blob/c0fc6315af73e8bef9d67e2f8ae952ac1ddda80b/news-bundle/src/Resources/contao/modules/ModuleNewsArchive.php#L142-L146

**How to reproduce**  

1. Log in to demo.contao.org
2. Create a news archive module and define fallback to "show all items"
3. Create a future news item

**Comment by fritzmg** [comment]
> Shouldn't not also future event being visible?

I see what you mean, but imho no - since it's the news _archive_ module.

**Comment by frontendschlampe** [comment]
yes ... you're right, but if I make a new news item visible in future and go to frontend preview with activated option "show hidden elements" the item will not be visible. So I have no chance to see this item without changing the date.

**Comment by fritzmg** [comment]
Well, you have, with a regular news list module ;). The news _archive_ module is only supposed to show _past_ ("archived") news, in my opinion, never future news entries.

**Comment by frontendschlampe** [comment]
> Well, you have, with a regular news list module ;). The news archive module is only supposed to show past ("archived") news, in my opinion, never future news entries.

Showing it in "normal" state I will agree, but adding news items in future is not an unusual feature. And if I use the option "show hidden/unpublished elements" I want to see all hidden/unpublished elements! In previous versions of Contao it works! After updating a client website, the client is not amused about that! ;-)

**Comment by fritzmg** [comment]
> And if I use the option "show hidden/unpublished elements" I want to see all hidden/unpublished elements!

The option to show hidden/unpublished elements in the front end preview will only affect elements, that are either unpublished or not shown due to the start or stop constraints. This concerns neither.

> In previous versions of Contao it works!

Are you sure about that? The Contao 3 news module uses the same code. Anything past the current day will not be shown.

**Comment by frontendschlampe** [comment]
> The option to show hidden/unpublished elements in the front end preview will only affect elements, that are either unpublished or not shown due to the start or stop constraints. This concerns neither.

anyway - the item has a start constraint, but a date in future, too. I want to publish I news on the 3rd of April but I have no chance to publish it, because I'm out of office. That's why I add the news today with the date of tomorrow and a start constraint for tomorrow, but I can't check it.

> Are you sure about that? The Contao 3 news module uses the same code. Anything past the current day will not be shown.

With the option "show hidden elements" in the frontend preview it works in Contao 3.

I have no problem, that the news archive don't show any future items, but I have the problem, that the frontend preview with the option "show hidden elements" also don't show it.

**Comment by fritzmg** [comment]
> With the option "show hidden elements" in the frontend preview it works in Contao 3.

With a news archive module that is set to show all items? I'll have to test this myself because the code is the same.

> I have no problem, that the news archive don't show any future items, but I have the problem, that the frontend preview with the option "show hidden elements" also don't show it.

The front end preview can only make icons visible, that are either unpublished or not shown due to start or stop constraints. It cannot show you elements that are not shown for other reasons - like a news archive not being selected in the module, or a time constraint in the news archive module, etc.

**Comment by leofeyer** [comment]
As discussed in Mumble on April 11th, the "show all" option should show all news and not just the past ones.

**Comment by leofeyer** [comment]
Fixed in 2137caa4bac8073438da0be9562a5a1c83149a71.
