### ISSUE TITLE
Open/ Close Icon consistency 

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#4247]
### Description

<img width="652" alt="OpenClose" src="https://user-images.githubusercontent.com/1622733/157196972-7fe2ec7e-d4ca-4971-b987-5f53d4511c2f.png">

During a training session, the editor pointed out that two different icons were used for the functionality of open and close.

**Comment by fritzmg** [comment]
I disagree with changing this. ▶️/🔽 and similar is most often associated with opening/closing accordions, sections and the like. And historically I think ➕/➖ was most often used for tree structures. If anything I would do it the other way around, i.e. using ▶️/🔽 for everything, imho.

**Comment by leofeyer** [comment]
I disagree as well. The icons do have the same **functionality**, however, they do not have the same **meaning**.

Nested data structures are often represented in a tree. The plus icon then **means** _there are more nested nodes under this node_. Examples:

![](https://user-images.githubusercontent.com/1192057/157210173-d5a7e274-3b54-434f-9602-b856afc6dca0.png)

In contrast, the arrow icon is usually used to hide sections with more detailed information that does not necessarily need to be read.

<details>
  <summary>Some details</summary>
  <p>More info about the details.</p>
</details>

As you can see in the live example above, the browser uses the same icon that Contao uses, too. The icon then **means** _there are more details that you could configure, but you do not necessarily have to_. It would be wrong to use a plus/minus icon in this context.

> If anything I would do it the other way around, i.e. using ▶️/🔽 for everything, imho.

I second this. Using arrows instead of the plus/minus icon seems to be quite common for nested structures as well.

![](https://user-images.githubusercontent.com/1192057/157211269-46807d35-aa4b-448f-b243-eb8845055c34.png)

**Comment by m-vo** [comment]
> Using arrows instead of the plus/minus icon seems to be quite common for nested structures as well.

True, but this is more about consistency/coherence. Having the same or a very similiar icon mean something different depending on the context is the actual problem. For Contao that is: expand or toggle / add new / copy.

(Team arrows for file trees btw. :smile:)

![image](https://user-images.githubusercontent.com/5305677/157215759-692776e0-dcca-48d9-9763-4e6de6490451.png)

**Comment by erikherbert** [comment]
https://user-images.githubusercontent.com/1622733/157220082-56e07183-140c-490e-8e2c-df2b4beb3282.mp4

(Team arrows for file trees now also 😄)

"+" means more add new

**Comment by leofeyer** [comment]
As discussed in the last Contao call, we want to use arrows instead of plus/minus icons in the future.
