### ISSUE TITLE
Add support for lazy-loading (feature)

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#433]
**Description**  
As described in this [article](https://addyosmani.com/blog/lazy-loading/) by Addy Osmani, there will soon be native support for lazy-loading in Chrome 75.

Is it possible to implement this in Contao 4.8, too?

```
<img src="celebration.jpg" loading="lazy" alt="..." />
<iframe src="video-player.html" loading="lazy"></iframe>
```

**Comment by netzarbeiter** [comment]
Not lazy-loading, but a performance boost.
https://github.com/contao/contao/pull/354

**Comment by ausi** [comment]
The lazy-loading feature is not enabled by default in Chrome 75. So there is currently no browser supporting this, see <https://caniuse.com/#feat=loading-lazy-attr>

But I agree that this is an important feature and we should probably use it once one of the major browsers supports it.

Any ideas on how we should implement it?  
Should it be a setting of the image size?  
Or just a global or a theme setting?

**Comment by leofeyer** [comment]
I'd vote for "setting of the image size".

**Comment by Toflar** [comment]
This is the spec PR: https://github.com/whatwg/html/pull/3752
I think we should wait until there‘s something official.

**Comment by obendev** [comment]
I definitely think we should implement this in Contao 4.9 LTS, since this feature will definitely come in the feature.
As ausi said before it isn't available by default, but since it is already shipped in Chrome, we can be 100% sure they are testing this feature by Chrome users.

I mean this is just a nice handy feature, no breaking change.

It would be really cool to see more of this new fancy features in Contao.

**Comment by xchs** [comment]
Some more info on this: https://web.dev/native-lazy-loading

**Comment by obendev** [comment]
It's now live in Chrome 76 https://caniuse.com/#feat=loading-lazy-attr

**Comment by ausi** [comment]
Pull request: #703
