### ISSUE TITLE
Image Studio (inline): LinkAttribute and options have no effect

### ISSUE THREAD

**Issue by mpitz** [contao/contao#4389]
### Affected version(s)

4.13.1

### Description

The way described in the documentation (https://docs.contao.org/dev/framework/image-processing/image-studio/#php-templates under **2. Inline**) does not work if you want to take usage of `options`:

```php
<?php
  // …but you can also go wild with the options.
  echo $this->figure(
    $id, [200, 200, 'proportional'], 
    [ 
      'metadata' => new Metadata([
        Metadata::VALUE_ALT => 'Contao Logo', Metadata::VALUE_CAPTION => 'Look at this CMS!'
      ]),
      'enableLightbox' => true,
      'lightboxGroupIdentifier' => 'logos',
      'lightboxSize' => '_big_size',
      'linkHref' => 'https://contao.org',
      'options' => ['attr' => ['class' => 'logo-container']],
    ]
  ); 
?>
```

If you want to use the setAttribute in the configuration array, that doesn't work either. You'll get a `NoSuchPropertyException`:
> The method "setLinkAttribute" in class "Contao\CoreBundle\Image\Studio\FigureBuilder" requires 2 arguments, but should accept only 1..

**Comment by m-vo** [comment]
> The way described in the documentation ([docs.contao.org/dev/framework/image-processing/image-studio/#php-templates](https://docs.contao.org/dev/framework/image-processing/image-studio/#php-templates) under 2. Inline) does not work if you want to take usage of options:

Your example works as intended, but you won't see anything with the default `image.html` template. Either adjust the template and merge/output the data yourself or use the core's `_figure.html.twig` Twig template, that includes this functionality, by specifying it as the last parameter: 
```php
echo $this->figure(
    $id, [200, 200, 'proportional'], 
    [/* … */],
    '@ContaoCore/Image/Studio/figure.html.twig',
); 
```

> If you want to use the setAttribute in the configuration array, that doesn't work either. You'll get a NoSuchPropertyException:

That is also intended. That's why there is a `setAttributes` function, that allows setting everything with a single argument:

```php
echo $this->figure(
    /* … */,
    [
        'enableLightbox' => true,
        'linkAttributes' => ['data-foo' => 'bar']
    ]
);
```

We could in theory improve on this, but under the hood we're using Symfony's property access for this and they - for a reason -don't support multiple or variadic arguments. So IMHO making this change is not worth it.
