### ISSUE TITLE
No forwarding with auto login

### ISSUE THREAD

**Issue by zonky2** [contao/contao#4404]
### Affected version(s)

4.9.24

### Description

When logging in, a redirect page is set and when logging in, there is also a redirect to the page. If the login is done via the auto login function, the forwarding page is not accessed and the user remains on the login page.

example:
I have `https://example.com/login` which redirects to `https://example.com/my-account` when logging in, i.e. with autologin the call to `https://example.com/login` should redirect to `my account` ... but this does not happen.

**Comment by fritzmg** [comment]
Currently the redirect settings of the login module have no effect during an auto login via remember me. We would need to implement that the login module somehow detects that a remember me login took place for the current request, so that it can execute redirects according to the redirect settings - _if_ we agree that such redirects should happen when accessing the page where the login module is included.

**Comment by aschempp** [comment]
I think this is a misunderstanding. The auto-login feature does not _log you in through the login module_, it simply logs you in on whatever page you access. Therefore there is no redirect. You don't need to open the _login.html_ page to be auto-logged in.

**Comment by fritzmg** [comment]
I think @zonky2 understood that, however, the expectation still is that if you specifically access the page where the _login module_ is present, it should redirect you, regardless of whether you actively logged in or not.

**Comment by zonky2** [comment]
_I_'ve understood this so far and could deal with it if I fell into the trap - but it's about the users who use the website!

**Comment by aschempp** [comment]
as I said, thats not how it works. With autologin, you are **already logged in** when accessing the website. So by example, assume you logged in manually to the website. You navigate around, and then go to the `https://example.com/login` page. You will not and would not expect to be redirected to a page, just because you accessed it.

**Comment by fritzmg** [comment]
Yes, I meant when you _first_ access the page via `https://example.com/login`.

**Comment by zonky2** [comment]
We could perhaps add a checkbox "Enable forwarding on auto login".
