### ISSUE TITLE
Show custom Twig templates from subfolders also in backend dropdown

### ISSUE THREAD

**Issue by andyKempf** [contao/contao#4415]
### Description

Hi there,
The Twig support is awesome, thanks again for that!

With https://github.com/contao/contao/pull/4121 it is now possible that custom Twig templates from the templates folder are displayed and selectable in the backend dropdown.

Custom Twig templates in a subfolder like /templates/project/mod_article_twig.html.twig are not displayed in the backend dropdown currently.

Is it possible to display and select also the custom Twig templates from subfolders in the dropdown?

![Bildschirmfoto 2022-03-30 um 00 39 14](https://user-images.githubusercontent.com/48767191/160719718-93efa8ca-ce96-489f-8de7-17395cb54550.png)
![Bildschirmfoto 2022-03-30 um 00 39 26](https://user-images.githubusercontent.com/48767191/160719722-4077889c-91a4-41bf-bf3b-4a6f6baecb76.png)

(My Contao version is 4.13.1)

Thanks again and best regards
Andi

**Comment by m-vo** [comment]
Templates in any Contao template path are found in any nesting depth:
https://github.com/contao/contao/blob/c07953c80aec738ef0b3b83b9db51cbcf1068c3b/core-bundle/src/Twig/Loader/TemplateLocator.php#L98-L118

Templates in the global template directory (`/templates`) aren't. That's because any sub directory is effectively a valid theme prefix. 

In Contao 5 you'll get the opportunity to completely reorganize your templates, because there we support directories in template names (`content_element/text/special_text`).

**Comment by andyKempf** [comment]
Hi @m-vo,
Ah, I see! Thank you for your feedback! ;-)
