### ISSUE TITLE
RSS feed does not deliver well formed xml

### ISSUE THREAD

**Issue by bwl21** [contao/contao#4439]
### Affected version(s)

4.9.27

### Description

there are situations where contao delivers xml with minimized attributes

```
This page contains the following errors:
error on line 1 at column 6993: Opening and ending tag mismatch: source line 1 and picture
Below is a rendering of the page up to the first error.
```

I could fix it for my installation in `picture_default.html5:5` by adding an end tag to `<source>`

maybe this should be fixed in the core.

**Comment by fritzmg** [comment]
I can reproduce the issue, at least with Atom feeds. Reproduction:

1. Create a new RSS feed.
2. Set **Feed format** to Atom and **Export settings** to full stories.
3. Create a new news item.
4. Create a new image content element in that news item.

The generated XML feed will be invalid, since the HTML5 output is used within

```xml
<content type="xhtml">
  <div xmlns="http://www.w3.org/1999/xhtml">
    …
  </div>
</content>
```

but only XHTML is supported there - and thus things like `<img … />` or `<source … />` are invalid.

**Comment by fritzmg** [comment]
The problem is our `StringUtil::toXhtml` method. It does in fact not really convert any arbitrary HTML5 content to XHTML. It misses things like `<source />` or even attributes without values like `itemscope`, which are both not valid in XHTML.

In Atom you can provide the content also as `"html"`, I'll check if that will suit our needs so that we do not have to convert at all.

**Comment by m-vo** [comment]
We should not use this method anymore - it's already marked as deprecated by the way. :see_no_evil:

**Comment by fritzmg** [comment]
It's not marked as deprecated as far as I can see:

https://github.com/contao/contao/blob/00433ab37aad7e49fb0d0b767b15740f7c14bbcd/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L481-L488

**Comment by m-vo** [comment]
It is in 4.13: 
https://github.com/contao/contao/blob/f6d7da2f5aae5ec19e163af2cc4b4d7d420c654b/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L491

**Comment by fritzmg** [comment]
Yes, but this error happens in 4.9 and deprecating that method should not have been done in 4.13, as Contao still uses that method - even in 4.13 and 5.x. In 5.x Atom feeds are currently broken completely because of that, since the method was already removed.

In any case, if we can remove its usage in 4.9, we can start properly deprecating it in 4.9.

**Comment by bwl21** [comment]
There was not even a rationale why it should be deprecated (only IMO)

**Comment by fritzmg** [comment]
@bwl21 it should be deprecated, because it is out of date (see above). But we need to provide an alternative first.
