### ISSUE TITLE
Tables are created if driver is not set in DCA

### ISSUE THREAD

**Issue by rabauss** [contao/contao#4458]
### Affected version(s)

4.13 - maybe also 4.9?

### Description

Since Contao 4.13 tables are also created if the driver is not set in the DCA.
According to @dmolineus, this is caused by https://github.com/contao/contao/pull/4285

Example: You define additional fields in an extension for the `tl_faq` but in a project you don't install the faq bundle. Then the table `tl_faq` is also created - although the dc driver is not defined!
see also: https://github.com/hofff/contao-social-tags/issues/25

This is a BC break, isn't it?

**Comment by fritzmg** [comment]
> Example: You define additional fields in an extension for the tl_faq but in an project you don't install the faq bundle. Then the table tl_faq is also created - although the dc driver is not defined!

You mean if you have a soft dependency on `contao/faq-bundle`? Imho in that case the DCA should be extended only if the DCA is actually present. Otherwise your extension will create DCA entries for a DCA that's not actually there. Even if we change the behavior so that any DCA without a driver is ignored, I think it's wrong that your extension creates invalid `$GLOBALS['TL_DCA']` entries, as this might have more unintended side effects.

**Comment by rabauss** [comment]
Yes, you're right but the previous behaviour was that additional DC definitions were ignored or did not create a table if the main DCA file with the driver was missing

**Comment by fritzmg** [comment]
Yes, but the previous behaviour was also bugged ;) (see the previous issues).

**Comment by rabauss** [comment]
So each extension should always validate if `$GLOBALS['TL_DCA']` of the desired table is defined. That could be some refactoring for generic extensions ;-)

**Comment by fritzmg** [comment]
> So each extension should always validate if $GLOBALS['TL_DCA'] of the desired table is defined.

If it's a soft dependency, yes. Otherwise no.

**Comment by fritzmg** [comment]
Just to clarify: whether or not a driver is set did not matter before. The fact that the tables of that particular extension did not get created before was because there was no `config.sql` configuration set. And previously you were unable to create a table without a `config.sql` definition (i.e. a table without any sort of primary key or index set).

We could of course introduce a check whether a driver is set (and exists) and ignore the whole DCA otherwise as it would be invalid then.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add an `isset()` check to see if a driver has been set. If not, the DCA should be ignored when creating tables.

**Comment by bennyborn** [comment]
Joining the party since [numero2/contao-opengraph3](https://github.com/numero2/contao-opengraph3/blob/master/src/Resources/contao/dca/opengraph_fields.php) is also affected.

**Comment by aschempp** [comment]
Unfortunately, having a table with SQL keys and no driver worked just fine until now (see https://github.com/isotope/core/blob/2.7/system/modules/isotope/dca/tl_iso_product_pricetier.php for example).

As discussed with @fritzmg, we should revert the changes. Having a database table without (primary) key(s) is not a supported use case. It smells like wrong normalization to me, and even Doctrine does not support that.
https://stackoverflow.com/questions/19243990/doctrine-table-without-primary-keys
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#identifiers-primary-keys

**Comment by fritzmg** [comment]
To be clear, I think we should revert both:

* https://github.com/contao/contao/pull/4233 and
* https://github.com/contao/contao/pull/4285
