### ISSUE TITLE
It is impossible to include content elements of events and news

### ISSUE THREAD

**Issue by joehi** [contao/contao#451]
**Affected version(s)**
Contao 4.7.4

**Description**
It is not possible to include content elements which are part of news or events. It is only possible to include content elements which are not from news or events.

I have this effect on two different contao installations on two different servers and could reproduce it with the Contao online demo as well.

**How to reproduce**
Log in to the online demo. Try to include the text element (ID=321) of the first news item as an include element of the other news item. It is not possible to find the element with ID=321. Try to include the text content element (ID=88) of the first event. It is not possible either.

Add an include element to an article and now try to add one of those before mentioned content elements. They are not found.

**Comment by xchs** [comment]
This is probably a known limitation: https://github.com/contao/contao/blob/master/LIMITATIONS.md#moving-content-elements-as-non-admin-user

**Comment by joehi** [comment]
But it happens when I am logged in as admin user. And I am not trying to move or copy anything.

**Comment by asaage** [comment]
I think this is more or less a limitation of the select-picker-widget.
If you urgently need to to do that i suggest you use a 
**html-element** + **inserttag** ```{{insert_content::321}}``` or ```{{insert_content::88}}```
which does basically the same.

I guess the stylect is not suitable to add additional hierarchy (it's cluttered for me anyway most of the time). To fix this we would probably need another approach.

**Comment by leofeyer** [comment]
I also think that this is a known limitation. @contao/developers WDYT?

**Comment by Toflar** [comment]
I don't think it's a limitation at all. The content element `Include` just only provides the ones that have no parent (= `tl_article`). That's just how it works. It doesn't make sense to support anything else imho. The list would grow endlessly. Personally, I never ever use the `Include` element anyway because I can't find anything anymore.
I rather manage content at some central place and then reuse it from there (https://github.com/terminal42/contao-node).

**Comment by ausi** [comment]
Can we use the new picker here?

**Comment by Toflar** [comment]
There's no view where you can see all the content elements. You would need to switch between News and Article which you cannot. Well you could technically but still...

**Comment by leofeyer** [comment]
I agree that using the contao-node bundle or something similar is the best way to manage reusable content. Still we could improve things here:

1. Use the picker to select the include element and see if we can work around the limitation this way.
2. Otherwise at least allow to include elements of the same parent table, so you can include other news content elements in news and other event content elements in events etc.

WDYT?

**Comment by aschempp** [comment]
The picker sure will be the correct solution. But please implement a universal picker instead of just a content element picker 😂

**Comment by asaage** [comment]
I think the 2nd option (to include elements of the same parent table, so you can include other news content elements in news and other event content elements in events etc.) does not provide any improvement.
The picker sounds like the correct solution but in the process of drilling-down to find your desired content element you might get lost - whereas the current solution at least provides some kind of search.

**Comment by leofeyer** [comment]
> But please implement a universal picker instead of just a content element picker 😂

There once was a PR for that, wasn't it?

**Comment by leofeyer** [comment]
See #714.
