### ISSUE TITLE
Filtering by date isn‘t working anymore

### ISSUE THREAD

**Issue by gebi84** [contao/contao#4762]
### Affected version(s)

4.13.4

### Description

Filtering by date isn't working anymore:

for example see on https://demo.contao.org/contao
![bug](https://user-images.githubusercontent.com/805019/171264319-b0919c16-3ea2-4e5d-8b8a-d99d0cd18dc5.jpg)

When I debug this in the profiler it queries for:
`SELECT DISTINCT IF(`date`!='', FLOOR(UNIX_TIMESTAMP(FROM_UNIXTIME(`date` , '%%Y-%%m-01'))), '') AS `date` FROM tl_news WHERE pid=?
`
I think it should be without this double %

**Comment by fritzmg** [comment]
I can confirm the issue. It is indeed due to the `%` being double encoded here: https://github.com/contao/contao/blob/2ef24de0b613993e6806ce50b9333063668fa4e2/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5706-L5722

Removing the additional `%` fixes the issue. Is this a change in Doctrine 3.x? /cc @ausi

**Comment by ausi** [comment]
> Is this a change in Doctrine 3.x?

Don’t think so, probably caused by #3207 so there is no fix needed for 4.9 I guess.

> Removing the additional `%` fixes the issue.

That would be the correct fix IMO. 👍
