### ISSUE TITLE
Inconsistent deprecations

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4818]
While working on #4816, I have noticed that the deprecations are inconsistent:

**We have deprecated**

* `BackendUser::isAllowed()`
* `BackendUser::canEditFieldsOf()`
* `FrontendUser::isMemberOf()`

**But we have not deprecated**

* `BackendUser::hasAccess()`
* `User::isMemberOf()`

@contao/developers Why is that?

_Originally posted by @leofeyer in https://github.com/contao/contao/issues/4816#issuecomment-1152109114_

**Comment by aschempp** [comment]
As far as I remember that's because `hasAccess` and `isMemberOf` are still used by the `BackendAccessVoter`, but the other methods have been re-implemented.

**Comment by leofeyer** [comment]
So should we move the two methods to the `BackendAccessVoter` class then?

**Comment by Toflar** [comment]
If we move them, we have to also deprecate them in 4.13. Just as a reminder :)

**Comment by aschempp** [comment]
- `FrontendUser::isMemberOf` is deprecated since 4.12 because we have a voter for frontend groups. It is still used directly by `Backend::findSearchablePages` which is deprecated though. Look like we can deprecate it in 4.13 and remove in 5.0
- `BackendUser::hasAccess` contains some special handling for `filemounts`, and I remember there was a discussion about `pagemounts` as well. I think we should improve that in Contao 5.x and remove the method then (simply because it has no priority for 5.0)

**Comment by leofeyer** [comment]
As discussed in the Contao all, we can deprecate the `FrontendUser::isMemberOf()` method for removal in Contao 6 because we do not use it anymore in Contao 5.

The `BackendUser::hasAccess()` method has to be reworked before we can deprecate it as described by @aschempp above.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6008

> The `BackendUser::hasAccess()` method has to be reworked before we can deprecate it as described by @aschempp above.

this has been done in https://github.com/contao/contao/pull/5893
