### ISSUE TITLE
Inhaltselemente per Pfeiltasten nach dem speichern wieder pickbar machen

### ISSUE THREAD

**Issue by akroii** [contao/contao#4924]
### Affected version(s)

4.9.*, 4.13.*

### Description

Hallo,
wenn man im Contao-Backend innerhalb eines Artikels einen neues Inhaltselement hinzufügen möchte, kann man das ja schnell erledigen, indem man ein neues Inhaltselement hinzufügt und in dem Select z.B. "Auflis" eingibt und mit den Pfeiltasten dann nach unten drückt um "Auflistung" anzuwählen.

Wenn man jedoch diesen Vorgang schon einmal getaen hat und anschließend das Inhaltselement wieder wechseln möchte, lässt sich über die Pfeiltasten nicht mehr wechseln.

Schritte zum reproduzieren:
1. demo.contao.org/contao aufmachen und in einen Artikel navigieren
2. Neues Inhaltselement erstellen und speichern
3. in das eben erstellte Inhaltselement reingehen und z.b. "Down" eingeben. Dann prüfen, ob man mit den Pfeiltasten runter navigieren kann um Downloads" zu picken -> geht nicht.

![image](https://user-images.githubusercontent.com/8830861/176869825-dc2972e0-0aa5-4236-bb9d-9637e30ff71a.png)

**Comment by fritzmg** [comment]
Try the "arrow up" key instead.

**Comment by akroii** [comment]
"Arrow up" works, but "arrow down" does not work ;)

But after I pressed "arrow up" "arrow down" works well.

Would be great to make "arrow down" possible after the first encounter

**Comment by fritzmg** [comment]
Yes, it's a usability issue of the Chosen JavaScript, that I also find super annoying. 

The issue is not that "arrow down" does not work. The issue is that the currently selected element is either above or below the filtered elements and thus you need to use either "arrow up" or "arrow down" depending on your current selection. Which is not intuitive, since you don't really know whether your currently selected element is actually above or below the filtered elements.

May be we can customize the Chosen JavaScript so that it internally ignores the currently selected element, once it's outside the filtered scope?

**Comment by leofeyer** [comment]
Please re-create this issue here: https://github.com/contao-components/chosen/issues

**Comment by akroii** [comment]
[https://github.com/contao-components/chosen/issues/4](https://github.com/contao-components/chosen/issues/4)
