### ISSUE TITLE
ModuleNewsletterList requires Channels with redirect page

### ISSUE THREAD

**Issue by asaage** [contao/contao#494]
**Affected version(s)**
4.7.5 and probably older

**Description**  
```
request.CRITICAL: Uncaught PHP Exception Exception: 
"Newsletter channels without redirect page cannot be used in a newsletter list" 
at /var/www/.../vendor/contao/newsletter-bundle/src/Resources/contao/modules/ModuleNewsletterList.php line 90
```

**How to reproduce**  
Create a Newsletter channel without redirect page and use it in a Newsletter list.

The easiest way i can think of is to make the redirect page of channels a mandatory field and/or skip channels without redirect page in ModuleNewsletterList.

**Comment by leofeyer** [comment]
The target page is only required if you plan to publish the newsletters on the website, because then we need a reader page to generate the URLs. However, if you only use a channel to send newsletters via e-mail, the field is not required and therefore not mandatory by default.

@contao/developers Should we remove the exception and just skip the channel instead?

**Comment by Toflar** [comment]
No opinion here, I never use that module so I'm fine with whatever you decide :)

**Comment by ausi** [comment]
I think we should skip the channel in the frontend.

And we should probably also validate the selection of the channel in the newsletter list in the backend so that only channels with redirect pages can be selected.

**Comment by leofeyer** [comment]
Changed in 95ab03646970fcf06e5d135dadce4ef895028e79.
