### ISSUE TITLE
{{insert_module::|uncached}} not working

### ISSUE THREAD

**Issue by wschwaiger** [contao/contao#500]
**Affected version(s)**
4.4.40

**Description**
Possible duplicate to https://github.com/contao/contao/issues/48 and https://github.com/contao/contao/issues/154. This happens in combination with the Isotope Shop using a cart module in my navigation. {{insert_module::|uncached}} is used to insert the cart module into the heading of the site. When caching is enabled the number of items in the cart is not showing. Meaning that the caching is not properly working as no updates happen to the module.

**How to reproduce**
Create a cart module with isotope and use an HTML Module and the insert tag, {{insert_module::581|uncached}} with the ID of the cart Module. Turn the caching on and you'll see that the cart module is cached aswell.

**Comment by aschempp** [comment]
Isotope eCommerce is not compatible with caching modules this way. Using `{{insert_module::|uncached}}` will not _magically_ work, because most extensions (including Isotope) are not built to work if the page itself is cached.

Btw. this has changed in Contao 4.8 (as far as I can tell): pages are never cached, if your visitor has a cookie. And your visitor will always have a cookie if they have a cart.

**Comment by fritzmg** [comment]
> Btw. this has changed in Contao 4.8 (as far as I can tell): pages are never cached, if your visitor has a cookie. And your visitor will always have a cookie if they have a cart.

Unless you enable the shared cache, no?

**Comment by aschempp** [comment]
No, the shared cache is bypassed if you have a cookie. Only if you check the new checkbox, but then the cart will likely not show up on that page.
