### ISSUE TITLE
Ignore picker context in version edit url

### ISSUE THREAD

**Issue by rabauss** [contao/contao#5120]
### Description

While analyzing a problem with a custom edit url for the versioning I realized that my problem is the picker context.
Someone wanted to edit a entity with a picker context containing `%C` which will cause an error here:
https://github.com/contao/contao/blob/87b3a7cf676461608c08146678c046bd5debf4d8/core-bundle/contao/classes/Versions.php#L743

But then I saw that the picker context is not ignored in the core, too.
Wouldn't it make sense to do something like this after the query string parsing?
https://github.com/contao/contao/blob/87b3a7cf676461608c08146678c046bd5debf4d8/core-bundle/contao/classes/Versions.php#L749
```php
unset($pairs['picker'], $pairs['popup']);
```

**Comment by leofeyer** [comment]
Is this really a feature? And if not, which Contao versions are affected?

**Comment by rabauss** [comment]
Well, maybe it's a bug?
The picker context is not ignored in any contao version.

But the easy unset in the `pairs` is only available in the Contao 4.13+
https://github.com/contao/contao/blob/12c7f37523f4f4bfedaaccb1b322ade711dab52c/core-bundle/src/Resources/contao/classes/Versions.php#L780-L809
Because the parsing of the `QUERY_STRING` into `$pairs` is not available in 4.9
https://github.com/contao/contao/blob/1646dbc68cf15f3998dd052b2b55892b58c55afa/core-bundle/src/Resources/contao/classes/Versions.php#L768-L793

And for my initial problem with the existing edit URL with `%C` I changed the edit url in my custom extension. I'm not sure if we find a better solution for 
https://github.com/contao/contao/blob/12c7f37523f4f4bfedaaccb1b322ade711dab52c/core-bundle/src/Resources/contao/classes/Versions.php#L777

**Comment by leofeyer** [comment]
I think storing an URL with a picker context is wrong in the first place. Even if we would unset the `picker` and `popup` pairs, a custom edit URL added with `setEditUrl()` would still break if it had `%C` in it.

https://github.com/contao/contao/blob/b1455051078bee153bcfdd7af1b26651c42e6e78/core-bundle/src/Resources/contao/classes/Versions.php#L769-L772

**Comment by leofeyer** [comment]
As discussed in the Contao call, we should use another placeholder (preferably `{id}`) instead of `%s`. We also found out that the router converts `%s` to `%25s` and it is a pure coincidence that `%25s` is a valid `sprintf()` format. 😄 

<del>So to remain backwards compatible, we should do `str_replace(['{id}', '%25s'], $this->intPid, $this->strEditUrl)`.</del>

We have also discovered that we could pass the ID directly instead of using `sprintf()`, so to remain backwards compatible, we should do `str_replace(['%s', '%25s'], $this->intPid, $this->strEditUrl)`.
