### ISSUE TITLE
Allow preview links longer than 30 days

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#5184]
### Affected version(s)

4.13

### Description

While discussing #5099, we asked us how much of a security layer the 30 days limit really is and whether there might be use cases for long running preview links. The SQL query could then be simplified to `DELETE FROM tl_preview_link WHERE expiresAt>UNIX_TIMESTAMP(NOW())`.

**Comment by OMOSde** [comment]
I would be in favor of removing the limit. We often have projects with customer access to the preview that take much longer than 30 days.

Sending new preview links to the customer is always problematic because they quickly get confused with the links.

Alternatively, extending the preview links might be an option, but then they should not be removed when they expire.

The intervals could be adjusted well (without a limit) via DCA.

Translated with www.DeepL.com/Translator (free version)

**Comment by ausi** [comment]
With #5454 it is now possible to specify an arbitrary “Valid until” date.
