### ISSUE TITLE
DATABASE_URL in .env.local instead of .env

### ISSUE THREAD

**Issue by ausi** [contao/contao#5209]
In https://github.com/contao/contao/pull/5066#pullrequestreview-1055496311 @fritzmg wrote:

> As pointed out in Slack, `.env` should never be populated with any credentials, only with default values for the application. See [symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local](https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local)

But the manager currently store the `DATABASE_URL` in .env instead of .env.local should we change this here too? https://github.com/contao/contao/blob/e7ee456282da3f0b821001ac2c571fa793dd32b7/manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php#L49

**Comment by Toflar** [comment]
I think it wasn't done on purpose because if you're using the Manager you likely do not commit anything to any VCS. Because if you did, why would you use the Manager. But of course, there should not be any difference so I think writing into `.env.local` is correct. However, afaik, this file is only loaded if `.env` also exists. So we might need to write an empty `.env` file if it's not there yet.

**Comment by aschempp** [comment]
it was done on purpose for exactly that reason: if you don't use the manager, you don't need a .env.local.

**Comment by fkaminski** [comment]
I would prefer this (.env.local) approach. The installation via console creates both an .env and an .env.local too (the latter also with the APP_SECRET). It would also be easier for the documentation if the procedure is implemented uniformly throughout: 
In the sense of : Write access data into the .env.local

**Comment by fkaminski** [comment]
But in the end, it's probably just important to document/communicate the approach consistently

**Comment by fritzmg** [comment]
> I think it wasn't done on purpose because if you're using the Manager you likely do not commit anything to any VCS. 

Why would you find this not likely? Judging by my community experience this is definitely how people use Contao.

And it does not matter whether you use the Contao Manager or not. You should never store any important credentials in the `.env`.

**Comment by Toflar** [comment]
I think the point @aschempp is trying to make is that if you do not commit your `.env`, there's no need for a `.env.local`. 

Symfony just reads `.env` and if it does exist, it will override it with `.env.local`. Which means, if `.env` does not exist in the first place `.env.local` doesn't work either. You cannot have just `.env.local`. Either you have `.env` or you have both, `.env` and `.env.local`.

But I agree that the Manager should write to `.env.local` too. But in order to make it work, it has to create an empty `.env` if this does not exist yet.

**Comment by fritzmg** [comment]
> But in the end, it's probably just important to document/communicate the approach consistently

I disagree, Contao should never do anything that goes against standards, especially when it comes to security.

Accidental leakage of credentials through committing them to a repository is a common security hole. And there is no reason why we should increase the chance of that happening. There is no advantage to letting the Contao Manager store the credentials in the .env,only disadvantages.

**Comment by fritzmg** [comment]
> But I agree that the Manager should write to .env.local too. But in order to make it work, it has to create an empty .env if this does not exist yet.

That's easy enough to do (see the existing implementation).

**Comment by Toflar** [comment]
Sure, nobody said it's not easy :D

**Comment by fritzmg** [comment]
> if you don't use the manager, you don't need a .env.local.

How did you come to this assumption? Pretty much all our projects use the Contao Manager (to use with trakked) and all of them are versioned.

Again, the usage of the Contao Manager has no bearing whatsoever on whether you version your project and it has no bearing on whether live credentials should be automatically stored in the .env.local or not (they should always be).

**Comment by Toflar** [comment]
I don't know whom you're discussing with. I already wrote about 5 times that I agree that the Manager should be adjusted. This is here is done for me.

**Comment by fritzmg** [comment]
@Toflar @aschempp seems to still disagree - or at least we do not know if he agrees now?

**Comment by ausi** [comment]
Agree, we should adjust the manager-bundle to work the same way as the contao-setup works for `APP_SECRET`.

Because this is already possible in Contao 4.9 I guess we have to fix it there too, right? https://github.com/contao/contao/blob/c02b2bd415302dadd0bb2af8efce47af5547ded3/manager-bundle/src/ContaoManager/ApiCommand/SetDotEnvCommand.php#L53

**Comment by ausi** [comment]
Closed in favor of #5212

**Comment by fritzmg** [comment]
> Because this is already possible in Contao 4.9 I guess we have to fix it there too, right?

We could introduce a `--local` option. Then there are no BC breaks.

**Comment by ausi** [comment]
> > Because this is already possible in Contao 4.9 I guess we have to fix it there too, right?
> 
> We could introduce a `--local` option. Then there are no BC breaks.

Not sure I understand what you mean, the mentioned `SetDotEnvCommand` is used by the manager only, so an option for BC should not be needed there I think.

**Comment by fritzmg** [comment]
Anyone can use that command and if they (for whatever reason) rely on it dumping to .env it would be bad if it by default now dumps to .env.local

Other applications like Magento provide a similar command which also have an option to write to env rather than the global config. So I think it makes sense for our command to have such an option as well in any case.
