### ISSUE TITLE
Misleading message in "SYSTEM -> Settings" in fresh Contao 5 installation

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5210]
### Affected version(s)

5.0.1

### Description

After installing Contao 5.0.1 via the new Contao Manager v1.6.0, entering SYSTEM -> Settings shows this warning on top of the screen:

`The file "system/config/localconfig.php" is not writeable and can therefore not be updated!`

This is because the directory system/config does not exist at this time.

If this is the intended behaviour in Contao 5 the message should either be removed or say something different.

As a second note the "E-mail address of the system administrator*" is empty (which is not the case in Contao 4.13).

**Comment by fritzmg** [comment]
I have seen this error message also in all previous Contao versions, it might not be specific to 5. The check whether the localconfig is writable is likely somehow flawed and can lead to false negatives.

**Comment by fritzmg** [comment]
I can confirm that this error occurs in Contao 5.0 though. The current implementation assumes, that the `system/config/localconfig.php` is always there, with at least `installPassword` and `licenseAccepted` (which will be created when first running the Contao Install Tool). However, since the removal of the Install Tool this file will be always missing by default and thus only when you save the back end settings for the first time it will be created.
