### ISSUE TITLE
Allow creating modern templates from within the back end

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#5223]
### Affected version(s)

5.0.1

### Description

At the moment it is not possible to create a template in the back end that can be picked in the content element afterwards.  I have to create the Twig templates with the appropriate structure by hand.

![Bildschirmfoto 2022-08-25 um 16 10 42](https://user-images.githubusercontent.com/1942550/186688052-1d3152f9-54aa-49a4-840b-c747f314b7b7.png)

**Comment by m-vo** [comment]
I think we need a more sophisticated solution here that we should discuss first. In my point of view, the template contents should not be copied like before but extended or used from the original template. This is different from the current workflow and IMHO also makes the functionality a bit less important than before.

Nevertheless, some things to consider:
* If this is a convenience function, should you also be able to create variant templates (`content_element/text/foo`)? 
* You should probably only be able to select directories as a target that are namespace roots (`.twig-root`).
* It should maybe be possible to select if you want to extend/use vs overwrite the content. We could also think about generating a comment with some instructions inside the file - e.g. telling you which blocks are available and so on. Probably based on a `backend/template_skeleton.html.twig` or something. Inception :smile:.
* We could add a second global action (e.g. `Derive template`) for this and rename the existing one `Add template (legacy)` instead of creating one complicated screen that does it all. Or can someone think of a simple enough UI for this?

Based on the complexity I'd consider this a feature for 5.1 to be honest.

**Comment by ausi** [comment]
I think a simple solution as a bug fix for 5.0 would be great. 
Creating the file with just the `{% extends … %}` line would be enough IMO.

All the other great features could come with 5.1 then I think.

**Comment by m-vo** [comment]
As dicussed in the Contao call on 22th of September, we might want to conditionally show other options like a field for custom variants with JS (depending on if its a modern fragment template) and handle them as well.

**Comment by m-vo** [comment]
Comment by @mlwebworker in #5635:
> Ich wollte ein Template headline.html.twig im Backend als Varianten-Template sofort im Zielverzeichnis headline [templates/content_element/headline] ablegen. Dabei entsteht dann leider folgende Struktur:
templates/content_element/headline/content_element/headline.html.twig
Für das Anlegen im Ordner Templates finde ich das automatische hinzusetzen des notwendigen Ordners content_element sehr sinnvoll, im Unterordner sollte das aber wenn möglich nicht erfolgen.

**Comment by m-vo** [comment]
Another point made by @mlwebworker in #5636:
> Contao-Version 5
Wenn ein Legacy Templates nicht aktiviert ist in der config.php dann sollte dieses in der Auswahl für ein neues Template im Backend entweder gar nicht zur Verfügung stehen oder nicht ausgewählt werden können.

**Comment by m-vo** [comment]
This issue will be fixed by #7587 and followup PRs.
