### ISSUE TITLE
log period also valid for var/logs

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#5258]
### Description

Actually the logfiles under `var/logs` are rotating after 10 files. This number of files we can adjust, but the problem is, that there could be any data from more than 7 days, if the website is not visited a few days or weeks or …

That's why it's better, if they will be deleted after 7 days like the system log of Contao.

**Comment by fritzmg** [comment]
Just add this to your crontab:

```
0 0 * * * find /path/to/var/logs/* -mtime +7 -exec rm {} \;
```

**Comment by kroerig** [comment]
not every hosting supports cron jobs.

**Comment by fritzmg** [comment]
> not every hosting supports cron jobs.

Only with cron jobs you will be able to make sure that logs are deleted after a period of time.

**Comment by leofeyer** [comment]
So you basically want to change `max_files: 10` to `max_files: 7` here?

https://github.com/contao/contao/blob/b1455051078bee153bcfdd7af1b26651c42e6e78/manager-bundle/src/Resources/skeleton/config/config_prod.yml#L19-L23

That would be fine with me.

**Comment by fritzmg** [comment]
That won't have the same effect. If there are no log entries for several months, you will still have log entries from several months ago.

**Comment by leofeyer** [comment]
Even if you have a cron job that calls `https://domain.com/_contao/cron` regularly?

**Comment by fritzmg** [comment]
Yes. A new log file will only be created, if there is something to log. So if nothing gets logged for months, then also no log file will get rotated - and thus you end up with old log files.

**Comment by Toflar** [comment]
We could have a cronjob that writes a log entry `Triggering daily log rotation.`.

I also think we might want to discuss having a minutely cronjob a system requirement for the future. Contao's become a big application and we not only have GDPR requirements to consider but people also expect Contao to be fast. Both requirements can only be fulfilled with a reliable background process which only real cronjobs can provide.

It would also solve other issues. E.g. updating the search index takes quite some time now which slows down the front end. We already have workarounds because of that which actually **reduce** the accuracy of our relevance calculation just because we want to make sure, we don't take too long. And if we want to continue to innovate and make the search experience even better, it will probably take even more time. If we could rely on having a real cronjob, we could improve Contao in such a way that this is done in the background.

We should at least discuss implications at our developers meeting.

**Comment by m-vo** [comment]
> I also think we might want to discuss having a minutely cronjob a system requirement for the future.

I think I'd also favor this. We could output a warning message in the back end if the last cron command was triggered more than say 15min ago and include some instructions or a reference to the docs on how to fix this. IMHO this might be the better UX in regards of cron jobs after all.

**Comment by leofeyer** [comment]
As discussed in the Contao call, the logs do not include personal information that has to be removed after 7 days, therefore we can and want to leave the `max_files: 10` setting.

If Contao should really write personal information into a log file, we should mask the entries accordingly.
