### ISSUE TITLE
Contao backend feature 'Wiederherstellen' is broken although tl_undo contains entries

### ISSUE THREAD

**Issue by masudewucse** [contao/contao#5449]
### Affected version(s)

4.13.8

### Description

Hello,
Once I try to access 'Wiederherstellen' in Contao backend : (/contao?do=undo&ref=xyz) 
It always
![error](https://user-images.githubusercontent.com/7643261/198577338-35d14c1b-8940-484f-a666-1f5a157b8dde.png)
 triggers the following error: 
`Contao\CoreBundle\EventListener\DataContainer\Undo\LabelListener::getTemplateData(): Argument #3 ($originalRow) must be of type array, null given, called in /var/www/www.akademie-sport-gesundheit.de/html/vendor/contao/core-bundle/src/EventListener/DataContainer/Undo/LabelListener.php on line 52`

The problem is from the vendor and thought to inform you and probably you have the solution to this. 

Note: The DB table 'tl_undo' contains entries

**Comment by bezin** [comment]
@masudewucse Could you check if all rows in `tl_undo` have a serialized array in `data`?

**Comment by masudewucse** [comment]
@bezin  Yes they all are serialized arrays. 
Some are a:0:{} and once I manually delete these (a:0:{}) the problem is getting fixed!

**Comment by bezin** [comment]
Well this is interesting as it means, there is no data to be restored. Which datasets have you deleted? Is it pages, articles or from other core tables, or custom or extension tables?

**Comment by masudewucse** [comment]
@bezin I am deleting it from the tl_undo table:
![Screenshot from 2022-10-31 15-28-06](https://user-images.githubusercontent.com/7643261/199032337-d394da52-d741-41e9-893e-82c214c14138.png)

**Comment by bezin** [comment]
That is odd. The page was deleted, but the data was not saved. Can you reproduce under which circumstances this happens? Because I don't know about a situation where this is supposed to happen (I may me mistaken though).

**Comment by aschempp** [comment]
According to the code, this is not possible to happen: https://github.com/contao/contao/blob/5.x/core-bundle/contao/drivers/DC_Table.php#L1598
But it does, I have the same issue, but on `tl_content`. Same as in the screenshot above, the `data` row contains an empty array. I've confirmed that there are three `ondelete_callback`s but none of them modify the `tl_undo` table after it is added by DC_Table.
FYI the `tl_undo.preview` column is null, which looks like the `RecordPreviewListener` did not run, otherwise the preview would always be a string.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to close this issue until there is a reproducible setup that we can use to debug the issue.
