### ISSUE TITLE
Individual Template: Presets in template file

### ISSUE THREAD

**Issue by JensB74** [contao/contao#5484]
### Description

The custom template module reminds me a lot of Rocksolid's Custom Content Elements.
Maybe it's possible to preset the key/value settings already in the template. Maybe even with different field types like select, text, radio, etc.
It would then be a simpler version of Rocksolid's Custom Content Elements.
And it would also be easier for users to understand if they only saw the variable name (key) and had to enter or select their value.

Or have I misunderstood the principle of the field?
Maybe you can use both in parallel and work with your own keys and values, depending on the preselection, or with predefined ones.

**Comment by m-vo** [comment]
> Maybe it's possible to preset the key/value settings already in the template. Maybe even with different field types like select, text, radio, etc.

IMHO there is no point in doing this. If you need a custom element, create a fragment controller (+ DCA definition for the palette/fields). See https://docs.contao.org/dev/getting-started/content-elements-modules/.

**Comment by JensB74** [comment]
Yes this is surely a way, but if "you" are not a programmer, the way above could be a way easier IMHO. ;)

**Comment by m-vo** [comment]
> Yes this is surely a way, but if "you" are not a programmer, the way above could be a way easier IMHO. ;)

You yourself did compare it to rocksolid custom elements, where you need to create PHP files in order to create elements?

**Comment by JensB74** [comment]
yes and I have my problems with the module, hence the suggestion to change the individual template

**Comment by m-vo** [comment]
You would need to have a config somewhere that defines how the UI should look/behave. The DCA _is_ this config. (And the controller file to output the data can basically be empty as the abstract base class already adds all data to the context.)

I don't think we'll have a UI for this in the near future. Maybe we can further improve the current workflow, so that you can for instance define everything in one file. Please note, that the way the Rocksolid custom elements are doing it (storing stuff related to config in the template directory), was just a workaround and we won't ever do this. :smile: No hard feelings.
