### ISSUE TITLE
No possibility to deactivate admin email, if "reg_activate" option is disabled in registration module

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#5523]
### Description

Currently, there is no possibility to deactivate the info emails about user registration to the system admin, if the "reg_activate" option is disabled. 

In my current project, I wrote an own activation email logic via `createNewUser` Hook. I need the possibility to deactivate the admin emails.

**Comment by fritzmg** [comment]
I think the plan is to incorporate the notification center into the core in the long run anyway.

In the mean time you could do the same thing that the notification center does: dynamically enabling `reg_activate` within the `createNewUser` hook so that the core does not send any email on its own: https://github.com/terminal42/contao-notification_center/blob/3415b79f545840817b70d9d02f5042a40b082fed/library/NotificationCenter/ContaoHelper.php#L59-L60

**Comment by theDyingMountain** [comment]
@fritzmg thx for the info and the tip with the `reg_active` option. It works for my case now.
