### ISSUE TITLE
Problem with database migration 4.13 to 5.0.6

### ISSUE THREAD

**Issue by wallenium** [contao/contao#5531]
### Affected version(s)

5.0.6

### Description

The database migration tool detects 171 issues with the database. Once I try to update/solve them, there is an issue with the hash, and I do not know why. Is there any way to debug this issue?

I am not sure where the is a different hash. Maybe I did sth wrong during upgrade?

`{"type":"error","message":"Specified hash \"b1cedf3304853bf5b2a5ac9deafa1ed2f0745cdd19efc0cede627f70cf2ef52a\" does not match the actual hash \"4492cdb6d057a47af96bb29efe736c3f2205d11b9f3af9c28154f4b909281132\"","code":0,"file":"\/home\/www\/xxxxxxx.de\/contao\/vendor\/contao\/core-bundle\/src\/Command\/MigrateCommand.php","line":355,"trace":"#0 \/home\/www\/xxxxxxx.de\/contao\/vendor\/contao\/core-bundle\/src\/Command\/MigrateCommand.php(197): Contao\\CoreBundle\\Command\\MigrateCommand->executeSchemaDiff(false, true, false, 'b1cedf3304853bf...')\n#1 \/home\/www\/xxxxxxx.de\/contao\/vendor\/contao\/core-bundle\/src\/Command\/MigrateCommand.php(94): Contao\\CoreBundle\\Command\\MigrateCommand->executeCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))\n#2 \/home\/www\/xxxxxxx.de\/contao\/vendor\/symfony\/console\/Command\/Command.php(308): Contao\\CoreBundle\\Command\\MigrateCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#3 \/home\/www\/xxxxxxx.de\/contao\/vendor\/symfony\/console\/Application.php(1032): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#4 \/home\/www\/xxxxxxx.de\/contao\/vendor\/symfony\/framework-bundle\/Console\/Application.php(94): Symfony\\Component\\Console\\Application->doRunCommand(Object(Contao\\CoreBundle\\Command\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#5 \/home\/www\/xxxxxxx.de\/contao\/vendor\/symfony\/console\/Application.php(301): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand(Object(Contao\\CoreBundle\\Command\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#6 \/home\/www\/xxxxxxx.de\/contao\/vendor\/symfony\/framework-bundle\/Console\/Application.php(80): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 \/home\/www\/xxxxxxx.de\/contao\/vendor\/symfony\/console\/Application.php(171): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/home\/www\/xxxxxxx.de\/contao\/vendor\/contao\/manager-bundle\/bin\/contao-console(38): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput))\n#9 {main}"}
`

**Comment by m-vo** [comment]
Please provide some more background about how to reproduce the problem otherwise it's hard to guess.

**Comment by wallenium** [comment]
On my upgraded system, I need to log into contao manager. system check is passing. PHP 8.1 working well. The previous 4.13 worked w/o an problem.
then go to maintenance,Database Migrations - 171 pending schema updates
Start update. All updates fail with a Red Cross, I then check the database-migration.out.log and this one contains the errors.

Not sure where the hash are stored, if I borked them during update...

**Comment by aschempp** [comment]
the hash is something the command line tools generate on the fly based on your database configuration. The hash should not change as long as the necessary database changes do not change, and are an intentional measure to prevent you from executing changes that you don't see in the Contao Manager.

However, I cannot really explain why this is happening. Do you still have access to that broken system? Could you check the output of running the following command:
`path/to/your/php vendor/bin/contao-console contao:migrate --no-interaction --format=ndjson --dry-run`

It should give you JSON output including a hash. If you run the command again, does the hash change?

**Comment by aleksblendwerk** [comment]
I found this issue because I am dealing with the same problem when updating from 4.4 to 4.13.

@aschempp I ran the given command multiple times and it indeed results in different files and hashes.

After a quick file comparison it seems to me that the SQL statements in each file are effectively the same but whenever there are several `DROP INDEX` statements targeting the same table, the statements are in a different order, e.g.

Excerpt from File 1:

```
    "DROP INDEX email ON tl_user",
    "DROP INDEX username ON tl_user",
```

Excerpt from File 2:

```
    "DROP INDEX username ON tl_user",
    "DROP INDEX email ON tl_user",
```

This might be the reason for the different hashes...
