### ISSUE TITLE
Customized, renamed templates in template subfolder are not found in RSS feeds

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#5552]
### Affected version(s)

4.9 und 4.13

### Description

Werden in Nachrichten angepasste, umbenannte Templates aus Unterordnern von Templates benutzt, dann werden diese in RSS-Feeds (Exporteinstellung: Ganze Beiträge) nicht gefunden und führen zum Fehler `Could not find template "xyz"` .
Dieser Fehler tritt in Contao 4.9 nicht bei RSCE auf, aber bei umbenannten Core-Templates (z.B.ce_text_mein_template.html5). Laut @ausi wird das in Contao 4.9 für die RSCE abgefangen.
In Contao 4.13 tritt der Fehler dann sowohl für Core-Elemente als auch für die RSCE-Elements auf, weil die Elemente des Feeds im Frontend-Kontext laufen.
Das Problem lässt sich relativ einfach umgehen in dem die entsprechenden Templates in den Rootfolder verschoben werden.
Es sollte diskutiert werden, ob das eine Known Limitation ist oder behoben werden sollte.

Siehe dazu auch https://contao.slack.com/archives/CLTUNH78X/p1670324486656609

**Comment by fritzmg** [comment]
While we do set some context while rendering RSS feeds, there is still a lot missing. Most importantly, everything that `PageRegular::prepare` does is missing currently, which includes setting the `templateGroup` for the current page, according to the theme - and thus theme templates cannot be found when rendering RSS feeds in Contao 4.

There are probably (ugly) ways to fix this though I wonder if we should just see this as a known limitation for Contao 4 (when using RSS feeds which output the detailed content rather than just the teaser). In Contao 5 this should be fixed due to the RSS feed page type.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add `templateGroup` to the fake request to fix this specific use case.
