### ISSUE TITLE
BE > Contao Manager shortcut localhost

### ISSUE THREAD

**Issue by biowebfr** [contao/contao#5560]
### Affected version(s)

4.13.14

### Description

The contao manager shortcut do not include subdirectory when localhost

![image](https://user-images.githubusercontent.com/46192868/206456851-a9c8e535-6199-4177-89ea-7d168a52f5db.png)

Should be http://localhost/directory/public/contao-manager.phar.php

**Comment by CMSworker** [comment]
I guess this is not a bug. Contao is not ment to be called with a "installation subdirectory" in the URL.

"Set the document root of the installation via the admin panel of the hosting provider to this subfolder"
https://docs.contao.org/manual/en/installation/system-requirements/#hosting-configuration

As for localhost: Let's say you want to install Contao in `C:/... /htdocs/contao-subdirectory/`

The document root of your URL should first be set to `C:/... /htdocs/contao-subdirectory/web/`
(or since 4.12 to `C:/... /htdocs/contao-subdirectory/public/`)

For example **myinstallation.localhost** points to `C:/... /htdocs/contao-subdirectory/web/`

The configuration for **myinstallation.localhost** has to be done in your system.

Example for XAMPP: https://docs.contao.org/manual/en/guides/local-installation/xampp/#a-own-vhost-configuration

As for your example:
This is wrong: `localhost/directory/public/contao-manager.phar.php`
It should be this: `myinstallation.localhost/contao-manager.phar.php`

_// EDIT:_
I might be wrong, it is possible to install/call Contao with a subdirectory in the URL.
The wrong link to Contao Manager is a known restriction. Note the red warning box in the docs:
"Within Contao’s own linking (e.g.: starting the Contao Manager from the backend etc.) you will still get error messages, because they assume a »correct« environment."
https://docs.contao.org/manual/en/guides/local-installation/xampp/#contao-calls-without-own-vhost

**Comment by ausi** [comment]
> Contao is not ment to be called with a "installation subdirectory" in the URL.

I think we explicitly decided to support that, at least for `localhost`.

**Comment by fritzmg** [comment]
Yes, it is still supported for localhost.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6006
