### ISSUE TITLE
Add "webp" to the valid image types

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#557]
I think we should re-discuss our decision not to add "webp" to the valid image types by default. The feature will work for the majority of users, so we should not force people to overwrite the `contao.image.valid_extensions` settings – especially because they will have to re-adjust the setting if we change it in the future.

If we really want to hide the options when WEBP is not supported, we should use feature detection.

**Comment by ausi** [comment]
Should we use feature detection to add `webp` to the `contao.image.valid_extensions` configuration?

Or should we add `webp` by default and only hide the formats-setting based on feature detection?

**Comment by leofeyer** [comment]
The latter IMHO. This way the admin can still disable WEBP images completely.

**Comment by Toflar** [comment]
I agree with @leofeyer. Enabling and disabling explicitly is needed.
Also, the check in the image size should include both. So feature detection but also check if `webp` is present as a valid extension. Otherwise an admin disables `webp` because they explicitly do not want to have support but one can still choose it in the image size settings. That feels strange to me.

**Comment by leofeyer** [comment]
So how do we detect this feature? 😄

**Comment by ausi** [comment]
I will create a PR

**Comment by ausi** [comment]
> I will create a PR

#560

**Comment by Toflar** [comment]
Closing in favor of #560
