### ISSUE TITLE
Improve twig template inheritance for backend page

### ISSUE THREAD

**Issue by rabauss** [contao/contao#5657]
### Description

If you extend the template `@ContaoCore/Backend/be_page.html.twig` (https://github.com/contao/contao/blob/4.9/core-bundle/src/Resources/views/Backend/be_page.html.twig) in an extension for contao 4.13 you need to refactor it for contao 5 support.

Unfortunately, this template does not exist anymore in contao 5. what would be the suggested steps to support both versions 4.13 and 5 in your extension?

see also: https://contao.slack.com/archives/CK4J0KNDB/p1660217560759099

/cc @m-vo

**Comment by fritzmg** [comment]
See also https://github.com/contao/docs/pull/1120

> what would be the suggested steps to support both versions 4.13 and 5 in your extension?

You have to extend from `@Contao/be_main` (see the example in the PR)

**Comment by xprojects-de** [comment]
I would also like it if there is a kind of "be_page" in 4.13/5.x.
Otherwise you always have to create a wrapper container to support flex layout if you only extend from "@Contao/be_main". (see screenshots).

Or am I doing something wrong?
![Bildschirm­foto 2023-01-09 um 19 47 24](https://user-images.githubusercontent.com/55982921/211386080-d53cdeb7-a2c7-4513-bb86-f96d8ac36d08.png)
![Bildschirm­foto 2023-01-09 um 19 52 29](https://user-images.githubusercontent.com/55982921/211386092-204d8f08-5642-43b5-8039-507efc7178d4.png)

**Comment by rabauss** [comment]
Okay, you have to extend the block `main_content` and not `main`
Attention: The headline needs to be set via parameter and cannot be extended because the block `main_headline` does not exist! This is wrong in the docs PR!
see my changes in my extension: https://github.com/bwein-net/contao-database-backup/commit/eae5049f828676f0fe77a9e39cd3bdfaf121b910

Unfortunately, in the `AbstractBackendController` my backend changes with the hook `outputBackendTemplate` from my backend customizer (https://github.com/bwein-net/contao-backend-customizer/blob/41b9e3eb0be9e83f000c9f7c56096045c288d8c3/src/EventListener/OutputBackendTemplateListener.php#L32-L40) are not set anymore😢

**Comment by m-vo** [comment]
Let's discuss how to improve things in #5660. If the solution turns out to be simple enough, we can maybe discuss if this is something that can be backported to 4.13 solving the original issue (not for Contao 4.9, though - my hopes are very low with that).
