### ISSUE TITLE
HTML in the content element tables does not work anymore

### ISSUE THREAD

**Issue by stefansl** [contao/contao#5688]
### Affected version(s)

5.0.8

### Description

Contao allows HTML in the table content element: 
https://github.com/contao/contao/blob/98c98f05cb65d551e1bef1d005cbaef693122819/core-bundle/contao/dca/tl_content.php#L331

but disallows it in the template:
https://github.com/contao/contao/blob/98c98f05cb65d551e1bef1d005cbaef693122819/core-bundle/contao/templates/_new/component/_table.html.twig#L127

This is confusing for Contao 4 users, because raw HTML was allowed in the past.

**Comment by m-vo** [comment]
As already discussed on Slack, I don't think raw HTML should be allowed here. We should document the change instead. People that **really** need it, can adjust the template.

**Comment by fritzmg** [comment]
imho the question is whether we should output `raw` by default for all fields where we already have `'allowHtml'=>true`. If not, then may be we should remove `'allowHtml'=>true` everywhere? Note that you will still need to do both: setting `'allowHtml'=>true` and adjusting the template, if you want to allow HTML.

**Comment by m-vo** [comment]
>  Note that you will still need to do both: setting 'allowHtml'=>true and adjusting the template, if you want to allow HTML.

Well, these are two different things. If HTML should be output "as is", can **only** be decided in the template (basically an output encoding principle, because only then you know the context the data will live in). 

You can have input filtering, though, to make a more pleasant experience in the back end. So an option named `allowHtml` might still make sense, as it would make the user aware of whether a certain input (here HTML) is intended in this field or not.

Currently, with input encoding, the option is security-critical and does indeed make a difference for the output. We will need to get rid of this in the future. And we should IMHO also drop the `allowHtml` option completely and - if needed as input filtering option - give it a different name to clearly communicate the difference.

**Comment by leofeyer** [comment]
This is an unnecessary BC break. If `'allowHtml'` is `true`, the content should not be encoded, as it was not in Contao 4.13. Otherwise, we should have deprecated the option in Contao 4.13 and documented the BC break accordingly.

**Comment by ausi** [comment]
> Otherwise, we should have deprecated the option in Contao 4.13

How would that work? The option `allowHtml` is already set by the core so every installation would get the deprecation then.
