### ISSUE TITLE
Redirect to last page visited is broken

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#569]
The idea behind the "redirect to last page visited" feature is that when a visitor opens a protected page without being logged in, they are redirected to the login page and then back to the page they initially wanted to open. However, the error 401 page does not store the referer, so the redirect cannot work.

**Comment by Toflar** [comment]
Sounds like `login.html?referrer=/en/protected.html` just like in the back end?

**Comment by aschempp** [comment]
Isn't that exactly what the login module does? https://github.com/contao/contao/pull/565

**Comment by leofeyer** [comment]
No.

> they are redirected to the login page and then back to the page they initially wanted to open. However, the error 401 page **does not store the referer**, so the redirect cannot work.

**Comment by aschempp** [comment]
The 401 page does not store the referrer, but the login module on that page does. So if the user submits the login information, the `_target_path` will contain the referrer. And the firewall success handler will redirect back to that page (if the user enabled `redirectBack` in the login module).

**Comment by leofeyer** [comment]
No.

* Open `my-account.html` without being logged in
* You will be redirected to `login.html`
* The `_target_path` will **not** contain `my-account.html`

**Comment by aschempp** [comment]
Sounds like https://github.com/contao/contao/pull/565 is not working then?

Did you use 2FA while testing this?

**Comment by leofeyer** [comment]
#565 relies on the referer being stored in the session, so `$this->getReferer()` can read it. However, due to the early redirect, the referer is never stored in the session.

**Comment by aschempp** [comment]
The whole `System::getReferer()` method seems related to the back end. I don't know why this was ever used in the front end modules and page. Maybe it would be fixed by simply using `Environment::get('httpReferer')` ?

**Comment by leofeyer** [comment]
Nope, the referrer management was always BE and FE.

> Maybe it would be fixed by simply using `Environment::get('httpReferer')` ?

If there are no security implications (however, I think there are), this could solve the problem. @ausi /cc

**Comment by Physiklehrer** [comment]
please fix it in 4.4 as well, see https://community.contao.org/de/showthread.php?75086-quot-Zur%C3%BCck-zur-zuletzt-besuchten-Seite-quot-nach-403-401-quot-Zugriff-verweigert-quot&p=504666#post504666

Thanks a lot!

**Comment by ausi** [comment]
Using `Environment::get('httpReferer')` will not work as expected, because if a redirect happens the browser preserves the referrer of the previous page. For example:

1. You go to `/foobar.html` and klick on a link to `/my-account.html`
2. Browser sends the request to `/my-account.html` with referrer `/foobar.html` and gets a redirect response to `/login.html` back
3. Browser sends the request to `/login.html` with referrer still set to `/foobar.html`

I think there are only two possible solutions: Either store the “last page visited” in the session again, or add a `_target_path` GET parameter to the redirect, like `/login.html?_target_path=/my-account.html`

**Comment by leofeyer** [comment]
Fixed in e6e2d8df20b0144bd3d95c492421451c7a51a2ca.
