### ISSUE TITLE
Setting Importantpart of an image changes timestamp column AND lastModified in DB

### ISSUE THREAD

**Issue by n00ybfied** [contao/contao#5751]
### Affected version(s)

4.13.*

### Description

Setting Importantpart of an image changes timestamp column AND lastModified in DB

Is this intended? I think timestamp should remain the same.

**Comment by fritzmg** [comment]
`tstamp` should change whenever you make changes to the database record - which includes the important part of the image. So this is correct.

`lastModified` was introduced for the virtual file system and is supposed to be the timestamp the actual image file was last modified. Whether it is intentional that it also changes when you change or set the important part I do not know.

**Comment by m-vo** [comment]
Setting metadata should not change the `lastModified` date.

@n00ybfied How are you changing the important part? Via the back end or are you using the filesystem or any other API?

**Comment by n00ybfied** [comment]
@m-vo you are right, I was mistaken. 

lastModified did not change, just the timestamp (must have been something else i did that changed lastModified).
I changed the important part via the filesystem.

I guess we can close this, though the behaviour is a little confusing to me. ^^

**Comment by m-vo** [comment]
Yes, that's the intended behavior. 👍

**Comment by m-vo** [comment]
> though the behaviour is a little confusing to me. ^^

The timestamp is Contao's "last modified" date. It changes whenever anything in the row changes, no matter which table/DCA.
