### ISSUE TITLE
Comment author and Blog title

### ISSUE THREAD

**Issue by pw17l008** [contao/contao#576]
**Description**  
Hi there! 

I am using the listing bundle to get a list of the newest commments in a blog, and I notices I am only able to put information regarding the commment, i.e. name, author, date, commment! I was wondering if its possible also get the headline of the blog where it was commented?
**Example**  

Say Author Tom, commented on on a blog titled "Lorem Ipsum", along with the list of comments, I would like to habe the title published so one easily see on which entry that comment was placed!

I hope you request is understand! Great work! 

Thank you and I look forward to hearing from you! :)

**Comment by aschempp** [comment]
I don't think this will easily work, because the listing module lists only one table, and the respective information is in a related table. I guess your best shot would be to have an extension developed that does what you want. Maybe such a feature could be integrated into the comments module, but I haven't used that for a long time so I can't tell you personally.

**Comment by asaage** [comment]
Not the prettiest solution but i think you could customize the listingTemplate and use ```{{news_title::*}}``` with the ```parent``` field.
