### ISSUE TITLE
Sitemap in Japanese Contao 3.5 and 4

### ISSUE THREAD

**Issue by biowebfr** [contao/contao#5771]
### Affected version(s)

4 and 3.5

### Description

Hi everyone,

I noticed that the site generates a sitemap with encoded Japanese characters.

Which causes me duplicate content on Google.

Is there a way to prevent Japanese characters from being encoded?
Or another solution?

I've the issue on contao 3.5 and 4, so if there is a solution please help me for the 3.5 version too.

Thanks in advance.

![image](https://user-images.githubusercontent.com/46192868/218087304-10cb77b8-b45c-4391-89ec-ec383f239203.png)

![image](https://user-images.githubusercontent.com/46192868/218086628-67164ac5-6f57-416a-88bd-b1e03b915da0.png)

![image](https://user-images.githubusercontent.com/46192868/218086514-858cd190-c216-4f33-9414-efbbd9cc42a0.png)

**Comment by ausi** [comment]
> I noticed that the site generates a sitemap with encoded Japanese characters.

Japanese characters have to be URL-encoded because they are not in ASCII.

> Which causes me duplicate content on Google.

How? Are there two different URLs that point to the same page?
Please note, that browsers often show the decoded version of the URL to the user, even though the URL itself is percent-encoded.

**Comment by Toflar** [comment]
@taca can you help us with that Japanese issue maybe?

**Comment by biowebfr** [comment]
> Which causes me duplicate content on Google.

sitechecker.pro alerts me about this. But I don't really trust these kind of tools.

I read that I should not use japanese characters in URLS and even Japan websites don't use those.

So I decided to use english in slugs.

After reflexion, I don't know if it's really a good practice to use japanese characters in urls.

**Comment by taca** [comment]
As @ausi said, Japanese characters in URL path are encoded such as "%E6%B3%95" (法) (and domain part in URL is diffreent).

One problem was Japanese character was encoded to several ways; UTF-8, Shift_JIS and EUC-JP, depending on Web page's character encoding.  But modern web sites use UTF-8 such as [ja.wikipedia.org](https://ja.wikipedia.org/) and it works fine, indexed in Google.

But I've never use Japanese character in URL path (page aliases in Contao) since it cause very long encoded URL (yes, browser's address bar hide them).

Anyway, I tested in locally and Contao generates correct (encoded) URL on frontend and xml sitemap and there was no duplication.

**Comment by Toflar** [comment]
Thank you so much @taca! Closing this then🙂
