### ISSUE TITLE
Manage template files with DBAFS 

### ISSUE THREAD

**Issue by zonky2** [contao/contao#586]
**Description**  

Would it be possible to manage the template files with DBAFS ?

Currently individual templates are saved with the file name - if you change the template file e.g. for a better differentiation or description, you have to select the template again in the module.

With DBAL an update of the file name would be easier.

**Comment by Toflar** [comment]
I guess you mean DBAFS (DataBase Aided FileSystem). DBAL stands for DataBaseAbstractionLayer.
That's impossible. Everything in Contao uses a template **name**. With file system support we would need to translate a UUID into a template name which means everywhere where you selected a template (module settings, page layout, content elements and thousands of extensions) we would need to store a UUID rather than the name.

**Comment by zonky2** [comment]
> I guess you mean DBAFS (DataBase Aided FileSystem). 

right!

... o.k.

**Comment by leofeyer** [comment]
Related issue: #402 (UUIDs everywhere)

**Comment by aschempp** [comment]
I don't think this is feasible either. Templates are mostly used in Code, and the code must not access the DB for that. The only thing we _could_ do is a mapper for the dropdown menus, but then again I don't see how this should work if a developer moves the file around on the server…
