### ISSUE TITLE
Fehlerhafter Link mit Inserttag {{news_url::*}}

### ISSUE THREAD

**Issue by LutzWinkler** [contao/contao#5867]
### Affected version(s)

5.1

### Description

Hallo,

wenn ich im HTML-Editor über den Menüpunkt 'Link einfügen/bearbeiten' etwas im Format `{{news_url::123}}` eingebe, sieht das in der Quellcode-Ansicht so aus:
`<p><a href="{{news_url::123|urlattr}}">Newsletter</a></p>`
Beim Anzeigen des Textes im Frontend oder einer E-Mail sieht der Link dann so aus:
`https://baseurl.com//news-leser/newsletter.html`
Hinter der BaseUrl stehen 2 statt einem Slash (baseurl.com//news... statt baseurl.com/news...)
Dadurch funktionieren die Links nicht mehr

Gruß, Lutz

**Comment by LutzWinkler** [comment]
Ergänzung:

der folgende Link mit Insert-Tags  
`<p><a href="{{news_url::123|urlattr}}">Newsletter</a></p>`
wird in einem **Artikel** wie erwartet umgewandelt:
`https://baseurl.com/news-leser/newsletter.html`

Der gleiche Link in einem **Newsletter** sieht nach dem Versand so aus:
`https://baseurl.com//news-leser/newsletter.html`
Hinter der Base-URL stehen 2 Slashes //

**Comment by asaage** [comment]
probier's mit ```{{news_url::123::absolute|urlattr}}```!

**Comment by LutzWinkler** [comment]
Daraus wird im Newsletter:
`https://baseurl.com/https://baseurl.com/news-leser/newsletter.html`

**Comment by asaage** [comment]
Hmm 🤔
Ich hab länger nichts mit Newslettern gemacht.
Kann sein, dass das nicht geht ({{insert_module::*}} usw. geht ja auch nicht).
Ansonsten evl. prüfen, ob dein Startpunkt eine Domain hat (ohne / am Ende) und ob du auf der selben Domain im BE angemeldet bist.
Wenn ich mich recht erinnere gab's auch beim NL irgendwo ein Häkchen für absolute Verweise.

**Comment by LutzWinkler** [comment]
Ich verschicke schon seit 10 Jahren Newsletter mit Contao in denen mit dem Inserttag {{news_url::xxx}} auf Newsbeiträge verwiesen wird. So ist es auch im aktuellen [Contao-Handbuch](https://docs.contao.org/manual/de/artikelverwaltung/insert-tags/) beschrieben:

> {{news_url::*}}	Dieses Tag wird mit der URL einer Nachricht ersetzt: \<a href="{{news_url::12}}">Hier klicken</a>.

Das Problem ist erst ab Contao 5.x aufgetreten. Imho ist das ein Bug

**Comment by fritzmg** [comment]
I can confirm the issue.

**Comment by fritzmg** [comment]
The issue lies within [`Controller::convertRelativeUrls`](https://github.com/contao/contao/blob/3076e2bbc8c10ddd00af52aad168b8613bbfc1f0/core-bundle/contao/library/Contao/Controller.php#L1073-L1105), which is used as a `save_callback` for `tl_newsletter.content`. It converts `{{news_url::*}}` to `https://example.com/{{news_url::*}}`.

This was not an issue when our URLs were relative to the `<base>` - but now that they are absolute URLs it introduces an additional `/`. The current detection also makes it impossible to use the new(-ish) `|absolute` flag for insert tags (this also applies to Contao 4.13).

I think the correct solution would be to replace the insert tags for `$strContent` within `Controller::convertRelativeUrls`. @contao/developers wdyt?

**Comment by fritzmg** [comment]
> I think the correct solution would be to replace the insert tags for `$strContent` within `Controller::convertRelativeUrls`. @contao/developers wdyt?

Correction: only replace `$strUrl` further down within `preg_match` (otherwise we would save the replaced state to the database).

**Comment by leofeyer** [comment]
I think we should not convert insert tags at all (see #6083).
