### ISSUE TITLE
Images: Only overwrite the metadata from the file manager (and not license or additional meta fields)

### ISSUE THREAD

**Issue by minstyle** [contao/contao#5889]
### Affected version(s)

Contao 4.13.18

### Description

The `License URL` for images in the file manager is not outputed in the frontend if the `Overwrite metadata` checkbox is selected for content element type `image`. If I remove the checkbox and do not overwrite the metadata from the file management, then the license data will be outputed in the frontend.

Also when I add a new input meta field (i.e. `License Text`) in the file manager, then the meta data will not be shown in the frontend, too.

Example:

![grafik](https://user-images.githubusercontent.com/2649562/226292353-b177e119-0a7a-4972-af89-6439df941bb2.png)

I added the additional meta field `License Text` to the file manager of Contao as described (https://docs.contao.org/dev/reference/dca/fields/#meta-wizard-fields):

```
// contao/dca/tl_files.php
$GLOBALS['TL_DCA']['tl_files']['fields']['meta']['eval']['metaFields']['license_text'] = array('type'=>'textarea', 'allowHtml'=>true);
```

![grafik](https://user-images.githubusercontent.com/2649562/226292978-1f5964a4-f03c-4418-b16d-34d2a242f9bc.png)

![grafik](https://user-images.githubusercontent.com/2649562/226293163-72ca16e4-24e0-4ef0-b64c-cdb0fc64cda0.png)

When I deactivate the checkbox "Overwrite metadata" than all meta fields of the image will be shown in the frontend:

![grafik](https://user-images.githubusercontent.com/2649562/226293475-41ba261f-3cfd-4ab6-9dca-b23113f2aa37.png)

**Comment by m-vo** [comment]
IMHO the behavior is expected, but probably not what most people want. When selecting "overwrite metadata", all existing metadata will be discarded and only those fields of the current model entry kept that match the fields in `FilesModel::getMetaFields()` (basically `$GLOBALS['TL_DCA']['tl_files']['fields']['meta']['eval']['metaFields']`).

The root issue is probably that we do not have any "tri-state" widgets at the moment, where you could differentiate between keeping/removing/overwriting the original value. Right now, it's a dilemma: If we would add a `license` field, you would need to (re)enter it every time you wanted to overwrite metadata. If we would instead always merge records, you would not be able to remove entries anymore.

I see two possible solutions here: The simple one would be to adjust the `ModelMetadataTrait` to explicitly keep the license field. The other one would be to enhance the text widget, so that it can show a placeholder text and has some mechanism to remove existing values (e.g. a button/icon that enters an insert tag `{{empty}}` or something to the text box and that special value gets handled later on).

**Comment by fritzmg** [comment]
See also https://github.com/contao/contao/issues/599
