### ISSUE TITLE
if a bundle contains image.html.twig, the news image does not work anymore

### ISSUE THREAD

**Issue by heimseiten** [contao/contao#5940]
### Affected version(s)

5.1.2

### Description

If I add a /src/Resources/contao/templates/content_element/image.html.twig to a bundle, the news image does not work anymore.

The image.html.twig only has one line of code:
{% extends "@Contao/content_element/image.html.twig" %}

Can easily be reproduced:
- Install any bundle, for instance fritzmg/contao-swiper.
- Create the directory content_element in the folder /src/Resources/contao/templates.
- Create the file image.html.twig with content: {% extends "@Contao/content_element/image.html.twig" %}
- Clear cache.
- Reload the frontend with a news with an image. The image is gone.

**Comment by m-vo** [comment]
You did not create the template `content_element/image.html.twig` but the template `image.html.twig`. As the news template calls `<?php $this->insert('image', $this->arrData); ?>` this will then render the Twig surrogate for the `image.html5` template. I'd assume it should fail hard, because if you're extending from the content element base template probably most of the needed parameters are not defined.

If you wanted to create the `content_element/image` template, then you need to add a `.twig-root` marker file to the same directory as the `content_element` directory. You can verify the result by using `debug:contao-twig image` and `debug:contao-twig content_element/image`. (You also should not use the `src/Resources/contao`  but `contao` directly in Contao 5.)

Read more about how to define a "twig root" and the general concept here: https://docs.contao.org/dev/framework/templates/architecture/#twig-root.

**Comment by heimseiten** [comment]
Thank you!!!

Know I implemented the new file structure in my bundle:
https://github.com/heimseiten/contao-inviewport-bundle

I can not see something wrong in the debug messages:
<img width="1397" alt="Bildschirmfoto 2023-04-08 um 14 20 10" src="https://user-images.githubusercontent.com/6552484/230721046-649b1154-7d8b-4317-a182-4b042bf9f51c.png">
<img width="1093" alt="Bildschirmfoto 2023-04-08 um 14 21 47" src="https://user-images.githubusercontent.com/6552484/230721048-804dc935-9544-44ff-bc83-6838c85903a3.png">

**Comment by m-vo** [comment]
See your first screenshot. Your `[…]/contao-inviewport-bundle/contao/templates/content_element/image.html.twig` is listed as `@Contao/image.html.twig`.

I see the problem now, though. Even though you correctly added the `.twig-root` file and the new structure is detected (see the second screenshot), the legacy logic *still* adds each file in any subdirectory like it did ever since. And unfortunately in this case the names collide. :see_no_evil: We probably need to address this in the `ContaoFilesystemLoaderWarmer`.

**Comment by heimseiten** [comment]
Unfortunately I do not know the ContaoFilesystemLoaderWarmer. Please let me know, if I can do something.

**Comment by m-vo** [comment]
see #5941
