### ISSUE TITLE
Add option in listing modules to not show empty list

### ISSUE THREAD

**Issue by Ernestopheles** [contao/contao#5958]
### Description

In several listing modules (events, news, ...) - if the list is empty - in FE a heading and an empty-message will be shown.

This might be wanted sometimes, and sometimes it would be preferred to not give out anything.

F.i. Eventlist: It's too honest for several clients to show an empty event-list;-)) They prefer to show nothing in this case. 

Also newslist: If you have a newslister for say 3 events to be shown in detail and behind you have a newslist for older news to be shown as short news: At the start of the lifecycle you probably do not have more than 3 news. Then you do not want to show the heading and empty-message for the short-news list.

There surely are several more usecases like this.

Maybe we could add an option to each list modul s.th. like "Show heading and empty-message if list empty?".
And evaluate that option at a central point where the template will be generated. It could also be in each separate module, but maybe not so good.

There are solutions without having this feature. But not available for everybody (as skills are needed) and taking some extra time, too.

**Comment by m-vo** [comment]
This would only make sense if most people needed to decide between showing nothing and a headline/message/whatever on a per-module basis. I doubt this is the case. 

If you prefer to render an empty list in a project, simply adjust the template. And as you said: this is opinionated, so both versions are valid.

**Comment by Ernestopheles** [comment]
Well, of course I am not the one to know or decide how many users would like to use this option. But what I see is that not seldom websites show empty lists where it wuld be more appropiate to show nothing. I suggest to set this for diskussion/poll.

**Comment by fritzmg** [comment]
> This would only make sense if most people needed to decide between showing nothing and a headline/message/whatever on a per-module basis. I doubt this is the case.

I can only speak for myself of course, but we need that all the time in our projects. The template adjustment works well enough, but ideally it should be handled by the controller, not the template - as there is no reason to actually render the template, if you don't want to actually show anything.

**Comment by Ernestopheles** [comment]
Please, leave me a hint where to change the coding, I will give it a try.
Maybe in getFrontendModule check the option configured in the module?

**Comment by aschempp** [comment]
I also think this should be solved in the template. The template is responsible for the content of the response.

**Comment by fritzmg** [comment]
Even for _empty_ responses? Besides, our fragments and legacy modules already return an empty response when applicable.

**Comment by Ernestopheles** [comment]
Do we really want Business Logic in our templates?

**Comment by m-vo** [comment]
> Do we really want Business Logic in our templates?

Well, displaying something or not isn't really business logic. And it is exactly the thing templates are build for. :slightly_smiling_face: 


> Even for empty responses? Besides, our fragments and legacy modules already return an empty response when applicable.

We do but it's not that consistent unfortuntately…

In a few occasions, the default template variables would be undefined otherwise. For example, if there is no markdown to be parsed in the `MarkdownController`, we return early. Alternatively `content` could be set to `''`, which would render an empty wrapper. Probably even better - because why would you want to hide something the editor deliberately placed?

For an empty gallery (`ImagesController`), I also think we should rather handle this in the template. Think about setting the source to "home directory" - depending on the user, there will images or not. Right now, you could not display something like "You don't have any images right now, upload some!" in the latter case.

All in all I think it is always the template's responsibility to decide whether *some alternative content* or *nothing* should be displayed in those cases. Regarding this issue, I also think we should rather make the other cases consistent (allow adjusting these kind of things in the template) than implement a new checkbox.

**Comment by Ernestopheles** [comment]
> Well, displaying something or not isn't really business logic.

Maybe there are different views upon this. I think a template should never decide anything; it is part of my applications logic if an empty list shall be shown or not and depends on the concrete context.

**Comment by aschempp** [comment]
To me, the main and irreversible advantage of having this in the template is that a user can control it. You can change the template and output a messare or output nothing. You can't change the business logic of the controller.

**Comment by Ernestopheles** [comment]
As I suggested before the User can choose: "Maybe we could add an option to each list modul s.th. like "Show heading and empty-message if list empty?".

**Comment by aschempp** [comment]
Yes, that would be possible. And if you don't want it empty, but want to change the message, you need to change the template again. I don't see a point in having two more configuration options that are a default template change to me 🤷

**Comment by Ernestopheles** [comment]
No Problem as there already is a "solution" for this. More a workaround - and might not be known or used by some. Redakteurs who are not keen with Templates für instance. But this is a minor Design questions so lets Close this.
