### ISSUE TITLE
something wrong with url-de/encoding

### ISSUE THREAD

**Issue by asaage** [contao/contao#5976]
### Affected version(s)

5+

### Description

If you use the filemanager and store a link with queryparameters in the meta-data of an image an then use the image in a content-text element the link is broken.
```https://www.yt.com/watch?v=videoid``` is becoming ```https://www.yt.com/watch?v&#61;videoid```

(it's not happening if you use "overwrite-metadata")

**Comment by ausi** [comment]
Can be fixed by disabling double_encoding in https://github.com/contao/contao/blob/49ad7b8dc7158a6d4ead6aa173489762b7f52cb4/core-bundle/src/String/HtmlAttributes.php#L408
Like so:
```
// TODO: Enable double_encoding once Contao moved from input to output encoding.
$value = htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, null, false);
```

I don’t really like that approach, but as `HtmlAttributes` will be used more and more with content from the Contao backend I don’t think we can decode the values everywhere beforehand.
