### ISSUE TITLE
Vimeo missing hash parameter for unlisted videos

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6033]
### Affected version(s)

4.13, 5.1

### Description

Vimeo has adjusted the embed code. If a video is set to unlisted, then a hash parameter must be specified in the URL.
In the current Vimeo element, there is no option to add this hash.

Parameter that looks similar to `h=5e2d1c1e6d`

See:
https://help.vimeo.com/hc/en-us/articles/12426470858001-Embedded-player-displays-This-video-does-not-exist-message

![screen-20230508_wTadDKmn](https://user-images.githubusercontent.com/23719181/236836535-4ed1c3fe-ed93-422a-8090-151b8a16fd4f.jpg)

**Comment by ausi** [comment]
How should we fix that? Adding an extra “video hash” field? Or allow setting `711959373?h=5e2d1c1e6d` as the video ID?

**Comment by fritzmg** [comment]
If we go with the former, then we also need a `save_callback` for the new field that extracts the hash from the full URL (in addition to the `save_callback` of the `vimeo` field). If we go with the latter then the existing `save_callback` for the `vimeo` field also needs to be adjusted so that extracts ID + hash and not just the ID.

**Comment by leofeyer** [comment]
I‘m for

> allow setting `711959373?h=5e2d1c1e6d` as the video ID?

**Comment by aschempp** [comment]
Closed in favor of #6144/#6147
