### ISSUE TITLE
Use an Sqlite DB for cache tags

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#606]
Since the number of cache tags is very high in Contao, purging tags can take a long time (see https://github.com/symfony/symfony/issues/32701). We should therefore consider using an Sqlite database to manage the cache tag pool.

@Toflar /cc

**Comment by leofeyer** [comment]
Based on Nicolas' explanation [here](https://github.com/symfony/symfony/issues/32701#issuecomment-514944655) and [here](https://github.com/symfony/symfony/issues/26178#issuecomment-365678036), the best thing to improve our situation is to not use the `FilesystemTagAwareAdapter` in the `Psr6Store`.

**Comment by Toflar** [comment]
Okay, so here are my findings of today's 3h debugging session:

1. Our initial attempts using the `PdoAdapter` did not work because we did not create the table. The table is automatically created by Symfony if a `TableNotFoundException` is thrown. However, that's a Doctrine specific exception and so it's only the case in Doctrine. If you use native `Pdo` it does not work. You'd need to pass the `Connection` instance in the constructor to make it work, like so:

```php
$cacheDir = $this->cacheDir ?: $this->kernel->getCacheDir().'/http_cache';

$itemsCache = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('', 0, $cacheDir);
$tagsCache =  new \Symfony\Component\Cache\Adapter\PdoAdapter(
    \Doctrine\DBAL\DriverManager::getConnection(['url' => 'sqlite:///' . $cacheDir . '/tag_versions.sqlite'])
);

$cache = new \Symfony\Component\Cache\Adapter\TagAwareAdapter($itemsCache, $tagsCache);

return new Psr6Store([
    'cache_directory' => $cacheDir,
    'cache' => $cache,
    'cache_tags_header' => TagHeaderFormatter::DEFAULT_HEADER_NAME,
]);
```

2. We initially switched to the new `FilesystemTagAwareAdapter` because of the number of files the regular `TagAwareAdapter` generated as pointed out by @xchs in https://github.com/contao/contao/issues/460. However, we found out now that the `FilesystemTagAwareAdapter` basically generates the same number of files. The difference is that it uses symlinks rather than files so it it is actually able to clean up the entries when invalidating tags (also see 3)).

3. I came back to the `TagAwareAdapter` and I debugged, how exactly that one works. So it basically provides tag support for any other cache adapter. You just give it a different cache adapter as the first argument in the constructor and it will handle tagging and tag invalidation for you. This is what we did in 4.7 (`new TagAwareAdapter(new FilesystemAdapter())`). Now the tricky thing here is to understand how it handles cache tag invalidation. So when I call `$cache->invalidateTags(['tag-1'])` it does not in fact get all the related cache entries and delete those basically because there's no such thing as fetching all items that match a certain tag. That's just not part of the Symfony Cache component. So what it does is, it creates **another cache entry** which contains the **tag version**. So in that example it will create a cache entry for `tag-1` with the value `1`. And everytime you call `$cache->invalidateTags(['tag-1'])` again, it will increase this number. When you then **fetch** the item from the cache, it compares all its assigned tags and their respective versions and if one version does not match anymore, it will invalidate itself.

In other words: The **tags themselves** are stored together with the cache item itself. The **tag versions** are stored separately. Which means that basically when we're using the `FileSystemAdapter` we'll have a cache entry for every single tag (Symfony is smart enough to not create one for version `0` so it technically only happens the first time one invalidates a certain entry but still...). You can - as you can see in 1) - have the `TagAwareAdapter` store the tag **versions** in a separate cache adapter by providing another cache adapter as second argument.

What does that mean for Contao now? Well, everytime you edit something in the back end we invalidate the respective tags which can cause quite a big number of files.

What Nicolas meant in https://github.com/symfony/symfony/issues/32701#issuecomment-514944655 is that the `TagAwareAdapter` does not suffer from the performance issue when pruning the items. However, the number of files is going to be higher compared with the `FilesystemTagAwareAdapter` because this one is actually able to purge the related cache entries when a tag is invalidated. So in fact it cleans up the system whereas the `TagAwareAdapter` does not. Or well, it does but the next time an item is **fetched** from the cache.

What options do we have? Yes, we could switch back to the `TagAwareAdapter` and in theory use sqlite to store our tag **versions** which means that we'd end up with less files stored in total. However, we have to bear in mind that we don't only use this when invalidating. Every time a cache lookup takes place, it will also have to lookup the **tag versions** to compare them and invalidate them if they don't match. So every page cache lookup also means searching the sqlite database. Whether that is faster than using the file system or not...I don't know 😄 (I mean: https://www2.sqlite.org/fasterthanfs.html ... but probably we'd still need to test how it goes).

Whether or not we use sqlite to store the tag versions, I think we should switch back to the `TagAwareAdapter`. It's better suited for our use case. Yes, it does generate more files but this is only temporary (until the respective cache items are fetched the first time). However, it does not suffer from the pruning penalty.

I'm still eager to see the performance when using sqlite, so @leofeyer: shall we do some more tests on contao.org? 😄

**Comment by Toflar** [comment]
Regarding the performance of fetching tag versions: sqlite will definitely be faster. Again, the `TagAwareAdapter` is fetching all tag versions which for the `FilesystemAdapter` means reading n files (so opening an closing n file handles). For the `PdoAdapter` and sqlite it will be just one file where it can fetch all the data from.

**Comment by Toflar** [comment]
The other question regarding performance optimization is whether or not we should use the `PhpFilesAdapter` instead of the `FilesystemAdapter` for cache **items**. In contrast to the `FilesystemAdapter` it stores the data as PHP value (`var_export()`) rather than serialized (marshalled to be technically correct) thus leveraging opcode.
Also, I think we should increase the purge threshold. So all in all, that's what I would like to test:

```php
$cacheDir = $this->cacheDir ?: $this->kernel->getCacheDir().'/http_cache';

if (PhpFilesAdapter::isSupported()) {
    $itemsCache = new PhpFilesAdapter('', 0, $cacheDir);
} else {
    $itemsCache = new FilesystemAdapter('', 0, $cacheDir);
}

$tagsCache =  new PdoAdapter(
    DriverManager::getConnection(['url' => 'sqlite:///' . $cacheDir . '/tag_versions.sqlite'])
);

return new Psr6Store([
    'cache_directory' => $cacheDir,
    'cache' => new TagAwareAdapter($itemsCache, $tagsCache),
    'cache_tags_header' => TagHeaderFormatter::DEFAULT_HEADER_NAME,
    'prune_threshold' => 5000,
]);
```

**Comment by leofeyer** [comment]
The code is now running on contao.org.

**Comment by Toflar** [comment]
PR: https://github.com/contao/contao/pull/611
