### ISSUE TITLE
Can we be sure the request scope exists?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#61]
I am referring to this: https://github.com/contao/core-bundle/blob/develop/src/ContaoCoreBundle.php#L30

@aschempp Can we be sure that the request scope exists? Check this out:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php#L49-L52

**Comment by aschempp** [comment]
I've seen that code. I think the question should be "it does not exist" though ;-)

If another Bundle adds a Container Scope "frontend" or "backend" too, it would cause problems, but I think that would be good (because the other bundle would potentially use the scope for something else).

Compared to the kernel, our bundle is the master of those scopes, where for the kernel someone else could have reasons to do the same imho.

**Comment by leofeyer** [comment]
The question is not whether to add `SCOPE_BACKEND` and `SCOPE_FRONTEND` as constants. That is a reasonable thing to do (I'd add them to the `ContaoBundleInterface` BTW).

But should we check if there is a `request` scope and add it if there is not? Otherwise it could lead to problems, because we are using `request` as parent scope.

**Comment by aschempp** [comment]
Hmm. I don't know about the check. The reworked bootstrap requires a request/route to work. The only situation where there is no request scope would be if someone does [change the `http_kernel` in the Container](https://github.com/symfony/HttpKernel/blob/master/Kernel.php#L187).
I don't think we should add the `request` scope, and not adding our scopes would be wrong too.

Regarding the constants, please wait with that. Feel free to change it to a FIXME. I do have a branch ready where there is no `ContaoBundleInterface` ;-)

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/139.
