### ISSUE TITLE
Date format causes error when saving News

### ISSUE THREAD

**Issue by xApep** [contao/contao#6133]
### Affected version(s)

4.13.9

### Description

If you set date format in Settings: d. M Y and then go to News to create one, after a save you get an error:

![image](https://github.com/contao/contao/assets/1315340/041a7f77-8ecf-48f1-8c6b-aa41e8a90950)

**Comment by fritzmg** [comment]
That's normal. As the error message says you entered an invalid date format for inputting dates.

If your goal was to change the date format for _outputting_ dates in the _front end_ then you need to set the date format that you want in the settings of the respective website root.

Btw. for security reasons you should update to the latest version.

**Comment by xApep** [comment]
@fritzmg why is then date format in Settings?

Thanks for the help thou, it works.

**Comment by fritzmg** [comment]
> @fritzmg why is then date format in Settings?

In order to be able to customize the back end input format, if you need to. For example, if you want to enter dates in the backend like this: `23.03.2023` rather than this: `2023-03-23` then you change the `dateFormat` setting to `d.m.Y`. However, as the help wizard already says, the format _must_ be unambiguous and parsable by the system.

**Comment by xApep** [comment]
@fritzmg thank you!
