### ISSUE TITLE
No forms are output when printing a page as PDF

### ISSUE THREAD

**Issue by zonky2** [contao/contao#618]
**Affected version(s)**
all versions...

**Description**  

currently no forms are output when printing a page as PDF

**How to reproduce**  

add form at page and print as pdf

**Fix**
delete
```diff
		$arrSearch = array
		(
-			'@<form.*</form>@Us',
			'@<a [^>]*href="[^"]*javascript:[^>]+>.*</a>@Us'
		);
```
https://github.com/contao/contao/blob/6742d9ef116a2c2bcc3c150188f8119f501f8cc7/core-bundle/src/Resources/contao/modules/ModuleArticle.php#L283

**Comment by leofeyer** [comment]
@contao/developers WDYT?

**Comment by aschempp** [comment]
🤷‍♂  just print from the browser if you really wanna print… in 10 years of using Contao, I have never ever used TCPDF or seen it as being useful to the visitor.

**Comment by aschempp** [comment]
Btw. I don't think we should change it. People already using the feature might assume the current situation won't change. The feature is deprecated (that's why there is `contao/tcpdf-bundle`) …

**Comment by leofeyer** [comment]
This is actually not part of the TCPDF bundle. The method cleans the text before it is passed to the  `printArticleAsPdf` hook, so it applies to all PDF export bundles.

**Comment by zonky2** [comment]
couldn't you turn it off optionally so there's no BC break?

**Comment by leofeyer** [comment]
As discussed in Mumble on August 29th, we want to remove the whole `preg_replace()` statement, so forms and JS links are printed by default. However, since forms are not rendered correctly in TCPDF (input fields cannot have a border, all invisible screen reader texts are visible, only a limited set of CSS is supported, etc.), we have to move the `preg_replace()` to the Contao TCPDF bundle.

**Comment by leofeyer** [comment]
See #1123

**Comment by zonky2** [comment]
thx!
