### ISSUE TITLE
Contao 5.2 RC1 :: Environment variable not found: "APP_SECRET".

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6199]
### Affected version(s)

5.2.0-RC1

### Description

I just tried to install Contao 5.2 RC1 via Composer.
`php composer.phar create-project contao/managed-edition contao52 "5.x-dev"`

It ends up with the following error:

```
> @php vendor/bin/contao-setup

In EnvVarProcessor.php line 187:

  Environment variable not found: "APP_SECRET".


Script @php vendor/bin/contao-setup handling the post-update-cmd event returned with error code 1
```

**Comment by fritzmg** [comment]
I can confirm the issue.

**Comment by fritzmg** [comment]
Full stack trace:

```
 $ vendor/bin/contao-setup  -v

In EnvVarProcessor.php line 187:

  [Symfony\Component\DependencyInjection\Exception\EnvNotFoundException]  
  Environment variable not found: "APP_SECRET".


Exception trace:
  at vendor\symfony\dependency-injection\EnvVarProcessor.php:187
 Symfony\Component\DependencyInjection\EnvVarProcessor->getEnv() at vendor\symfony\dependency-injection\Container.php:379
 Symfony\Component\DependencyInjection\Container->getEnv() at var\cache\prod\ContainerQA1SLKH\getContaoManager_Command_SetupService.php:23
 ContainerQA1SLKH\getContaoManager_Command_SetupService::do() at var\cache\prod\ContainerQA1SLKH\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php:651
 ContainerQA1SLKH\Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer->load() at var\cache\prod\ContainerQA1SLKH\get_ContaoManager_Command_Setup_LazyService.php:23
 ContainerQA1SLKH\get_ContaoManager_Command_Setup_LazyService::ContainerQA1SLKH\{closure}() at vendor\symfony\console\Command\LazyCommand.php:190
 Symfony\Component\Console\Command\LazyCommand->getCommand() at vendor\symfony\console\Application.php:316
 Symfony\Component\Console\Application->doRun() at vendor\symfony\framework-bundle\Console\Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor\symfony\console\Application.php:174
 Symfony\Component\Console\Application->run() at vendor\contao\manager-bundle\bin\contao-setup:44        
 include() at vendor\bin\contao-setup:120
```

**Comment by fritzmg** [comment]
This is because we removed the default `ThisTokenIsNotSoSecretChangeIt` value for the secret parameter in https://github.com/contao/contao/pull/6085 - which in turn causes the `env(APP_SECRET)` fallback parameter not to be set anymore in the container here:

https://github.com/contao/contao/blob/56cba1e9846af8c4b0a34da8f7f10b59e54efe25/manager-bundle/src/ContaoManager/Plugin.php#L208-L210

If an environment variable is not present, Symfony's `EnvVarProcessor` falls back to a parameter named `env($name)` from the container: https://github.com/symfony/symfony/blob/e0b86552954855d2402548bb9bce86cffff34aa3/src/Symfony/Component/DependencyInjection/EnvVarProcessor.php#L191-L197

**Comment by ausi** [comment]
> If an environment variable is not present, Symfony's `EnvVarProcessor` falls back to a parameter…

So we need to revert https://github.com/leofeyer/contao/commit/c933f168350e631a8ccdf9547362c05b241d61b6 I think. I thought setting it to the empty string would be the same as not setting it, see https://github.com/leofeyer/contao/pull/6#pullrequestreview-1450360533 but that’s not the case it seems.
