### ISSUE TITLE
Multiple editing of files with brackets in the file name doesn't work correctly

### ISSUE THREAD

**Issue by mwitzmann** [contao/contao#6264]
### Affected version(s)

4.13.29

### Description

Multiple editing of files with brackets in the filename via "Edit multiple" leads to the following error message:
Invalid resource files/test (2).jpg

**Comment by ausi** [comment]
I can confirm this issue. 
The error message suggests that the path is incorrectly encoded: `Invalid resource files/test &#40;2&#41;.jpg`

**Comment by leofeyer** [comment]
This is because we decode entities for `$this->intId` here:

https://github.com/contao/contao/blob/b549e71d594c8c544af9eb148c5878759acd0080/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L144

But not for `$ids` here:

https://github.com/contao/contao/blob/b549e71d594c8c544af9eb148c5878759acd0080/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L169

Changing the latter to `$ids = Input::post('IDS', true);` solved the problem for me. @ausi Are there any security concerns with this solution?

**Comment by ausi** [comment]
I need to investigate this further, especially in combination with the following lines: https://github.com/contao/contao/blob/b549e71d594c8c544af9eb148c5878759acd0080/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L173-L174
