### ISSUE TITLE
Image attributes partial override

### ISSUE THREAD

**Issue by futura-web** [contao/contao#6374]
Is it possible to override only one of the needed attributes (set in the "Dateiverwaltung", var = default_image_meta) in the image ("Metadaten überschreiben")?
I suggest to show default_image_meta every time "Metadaten überschreiben" is needed.

**Comment by leofeyer** [comment]
What exactly do you mean by "default_image_meta"?

**Comment by futura-web** [comment]
when you upload an image, you can set values for _alt_, _caption_, _title_, etc. -> default_image_meta (or _default_image_attributes_?).

**Comment by Aybee** [comment]
Would such an option fit your needs?
![bildschirmfoto am 2018-03-15 um 12 47 53](https://user-images.githubusercontent.com/1143013/37461641-4f828ccc-284f-11e8-9fef-ae227639509f.png)
Also the meta data from tl_files should be shown in an extra DIV.

**Comment by frontendschlampe** [comment]
"Fallback when empty" would be great! So the default behavior is overwrite all meta data from file system and if checked "Fallback when empty" only filled data will be overwrited.

**Comment by futura-web** [comment]
perfect!

**Comment by leofeyer** [comment]
We have made huge efforts to decrease the number of input fields when adding images in Contao 4.4 (see https://github.com/contao/core/issues/7774), therefore I'm against adding another checkbox.

**Comment by futura-web** [comment]
Can we just show existing values in the corresponding inputs as value="_Default value_"?

**Comment by Aybee** [comment]
@leofeyer So we have to put the logic into our templates or write an extension.

**Comment by leofeyer** [comment]
Maybe the initial idea from contao/contao#6369 is a good compromise? The tickets seem related anyway.

**Comment by backbone87** [comment]
a technique i use in my open graph extension is to use context dependant insert tags. the default values of the fields would change to something like `{{image::caption}}` for the caption field. This means "use the previously known caption of the current image" (e.g. the value from the filesystem metadata). If you want to overwrite the caption to be empty, you would just delete the prefilled insert tag.

**Comment by Xendiadyon** [comment]
This would be perfect for developers (who LOVE insert tags), but I expect another weird look from our customers (who don't).

Anyway, any news here (or related: contao/contao#6369) how we could proceed?

**Comment by Aybee** [comment]
I still prefer this solution https://github.com/contao/contao/issues/6374

`Fallback when empty`. The checkbox `Overwrite if empty` is not necessary if this is the default behaviour, which I recommend.

Whith this solution you can
- suppress all fields
- suppress one or more fields
- change all fields 
- change one or more fields
- still take advantag from the files meta data if you want to

Consider those CE fields as alternative meta data belonging to only this CE, not to the file itself. The checkbox then is the instruction how to handle empty fields.

What you can **not** do in one CE is e.g. 
- change Alternate text
- suppress Image title
- take Image caption from meta data

So one change, one suppress and one fallback is not possible at the same time (CE).

Prefilling the fields from meta data is dangerous because once done those values are saved in CE dataset. This will not change if meta data changes.

**Comment by fritzmg** [comment]
Closing in favor of #599 as this is the same (and original) issue.
