### ISSUE TITLE
Add data-attributes to block_searchable

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#6378]
Hello,

at the moment we can add an ID or a class to block_searchable.html5. What also would be useful is to add data attributes to it like that:

```
<div class="<?= $this->class ?> block"<?= $this->cssID ?><?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif; ?><?= $this->dataAttributes ? ' ' . $this->dataAttributes : '' ?>>
```

Would that be possible to add in a future release?

Bye

**Comment by fritzmg** [comment]
The problem is not so much the template itself - but you would also need to provide a unified way of being able to define arbitrary attributes in content elements and modules. Programmatically and via user input.

**Comment by Defcon0** [comment]
I would handle it exactly as css class and id properties, i.e. you can set this attributes in the backend (editor input) and also via adding to to `$this->dataAttributes` in a possible class inheriting from Module (as it is already for css class and id, i.e. `$this->cssID`).

**Comment by asaage** [comment]
The input itself could be done with a subpalette and a wizzard.
But the problem that i see: in most cases you would probably want those attributes not on the ```.block``` but on one of its children (a link or an image...).

**Comment by Defcon0** [comment]
Then you could override the template, no?

**Comment by asaage** [comment]
> Then you could override the template, no?

true - but then there would still be no input for it 😏

**Comment by Defcon0** [comment]
? If we would build it like cssID as it's already implemented, we would have input. And if the data attributes should be added dynamically, the dev could do that in his module programmatically.

**Comment by asaage** [comment]
I dont - know how a textfield (like cssID) would be sufficient.
Wouldn't you need something like this?:

![image](https://user-images.githubusercontent.com/4138336/39247287-43edd1f4-4899-11e8-8804-4c1d14157ae4.png)

**Comment by Defcon0** [comment]
Ah, this is what you meant ;-) I assumed that such a form of structural input is available. We implemented such a widget by the way (which also works in the frontend): https://github.com/heimrichhannot/contao-multi_column_editor

In the next weeks we'll migrate the module to a Contao 4 bundle.

But of course, we could also use multi column wizard.

**Comment by fritzmg** [comment]
In https://github.com/contao/contao/issues/4203 we have added the `HtmlAttributes` class which provides the basis for this functionality. In https://github.com/contao/contao/issues/4671 the `content_element/_base.html.twig` template was introduced which utilises this - so that you - or any extension, can now add arbitrary HTML attributes to your content elements. https://github.com/contao/contao/issues/4847 provided the same for front end modules. Furthermore in https://github.com/contao/contao/pull/7218 we added the same functionality to all PHP templates.

So in Contao 5.4+ it should be pretty easy for an extension to provide arbitrary `data-` attributes for all content elements for example.
