### ISSUE TITLE
Version management deletes page

### ISSUE THREAD

**Issue by Ainschy** [contao/contao#6426]
### Affected version(s)

5.2,  4.13

### Description

A deleted parent page ensures that the versions of a page are irretrievably deleted when a previous version is restored.

Situation:

Creates a page as a subpage in the page tree. Move the page e.g. to the root level or into another page.
Deletes the first parent page and goes back to the first entry in the version management of the created page and exits the page setting the page is removed.

The deleted parent page can be restored, the created page does not appear in the restore option.

**Comment by bezin** [comment]
I can confirm this. When reverting $child to a version where it has been a child of $parent, $child will be purged, because $parent does not exist anymore. Purged pages do not have a restore entry.

**Comment by ausi** [comment]
So when restoring a version we should check if the parent still exists, and if not just keept the current `pid` value I think.

The same issue happens in the `undo` module too though. The right solution there would probably be to check if the parent still exists on restore, and if not, add the restored entry to the “Contao clipboard” so that you can select a new parent. (Idea ©️ by someone at the Contao conference (sorry, forgot your name 🙈))

Not sure how easy it would be to implement it this way though. Maybe an alternative would be to get a select-box or a picker to select/pick the new parent.

**Comment by leofeyer** [comment]
As discussed in the call, we should never overwrite fields such as `id`, `pid`, `ptable` and `sorting` when restoring a version.
