### ISSUE TITLE
Do not allow deletion of members

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6451]
### Affected version(s)

5.2

### Description

When I give a backend user access to the "Members" menu item in the backend, the backend user only gets read access. However, this user can also delete the members.

I think that should not be so.

See screenshot:

Reproduction:
1. give user only the right to show "Members".
2. no activation of fields in tl_member

![screen-20231021_3YjO7gzL](https://github.com/contao/contao/assets/23719181/2927016c-7eb2-41cb-a66a-533f23949e69)

**Comment by ausi** [comment]
Can confirm.

The `TableAccessVoter` does not handle the delete action so if the user can edit any fields is not checked for the delete action: https://github.com/contao/contao/blob/d42a6e40f1ed9be70f3bf5972b79b885bb1b548f/core-bundle/src/Security/Voter/DataContainer/TableAccessVoter.php#L38-L45

Not sure if we just can add `DeleteAction::class => true,` there, but it seems to fix the issue.
/cc @aschempp

**Comment by ausi** [comment]
I also tested the same configuration in Contao 4.13, everything is allowed there (create, read, update, delete). But the edit mask shows no fields.

**Comment by leofeyer** [comment]
I doubt that adding `DeleteAction::class => true,` is the correct fix.

By default, if you grant access to the member module, the user is granted all CRUD operations (as it is in Contao 4.13). The icons are greyed out because they cannot edit any fields of `tl_member`, not because the operation itself is permitted.

IMHO, this is not a bug at all.

**Comment by fritzmg** [comment]
Yes, there are no operation permissions for `tl_member` (like there are for `tl_files` or `tl_news_archive` etc.). This would be a new feature.

**Comment by leofeyer** [comment]
Exactly.

**Comment by ausi** [comment]
But isn’t it inconsistent now? Why is duplication not allowed?

**Comment by leofeyer** [comment]
That‘s a valid question. @aschempp @Toflar /cc

**Comment by ausi** [comment]
Currently create and update are not allowed if there is no permission for `USER_CAN_EDIT_FIELDS_OF_TABLE`. IMO it would be consistent to also disallow deletions in this case, leaving only the read action.

**Comment by aschempp** [comment]
If you cannot update any field of the table, you cannot copy a record (because in CRUD/REST view, this would be a READ of the old and WRITE of the new (to fields you're not allowed to)). However, DELETE is a separate operation, it's also a separate REST request. It's not related to the fields at all.

**Comment by ausi** [comment]
> If you cannot update any field of the table, you cannot copy a record…

I don’t think that is how CRUD works. For copying a record I need the `R` and `C` from CRUD, not the `U`.

So we either have to allow copy, delete and read for `!USER_CAN_EDIT_FIELDS_OF_TABLE` or we only allow read which is what I would prefer.

**Comment by contaoacademy** [comment]
Since no one has noticed it yet, maybe my use case is just not usual.

From the user's point of view, a solution like in the file management would certainly be the easiest to understand. So I can define whether someone has the right to delete members or not. Independent of the other options.

**Comment by aschempp** [comment]
> I don’t think that is how CRUD works. For copying a record I need the R and C from CRUD, not the U.

You're right. But since you're not allowed to write to any field, you cannot **C**reate records. That's what I meant. Calling `DELETE .../resource` is not related to writing to any field imho.

**Comment by leofeyer** [comment]
As discussed in the call, 

1. The `TableAccessVoter` should only deny a POST request if it tries to write to a field that is excluded and not allowed. Otherwise it should abstain.
2. The button should not be greyed out if the user is allowed to edit but there are no fields. If a user stumbles across an empty form, we want to display a hint why the field is empty and what they need to do to solve the problem.
3. We generally want to add `CUD` (without `R`) permissions to all tables.

This is a simplified mockup of how no. 3 could look like:

![](https://github.com/contao/contao/assets/1192057/2fe91da3-d500-423b-8d0d-c04cce62e416)

Note: We want to implement all three things at once.
