### ISSUE TITLE
Inconsistent permission constants

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6470]
### Affected version(s)

4.13, 5.*

### Description

While working on #6469, I realized that the permission constants are inconsistent.

* `USER_CAN_EDIT_CALENDAR` → `contao_user.calendars`
* `USER_CAN_EDIT_CATEGORY` → `contao_user.faqs`
* `USER_CAN_EDIT_ARCHIVE` → `contao_user.news`
* `USER_CAN_EDIT_CHANNEL` → `contao_user.newsletters`

But in the core, we named these constants `CAN_ACCESS` instead of `CAN_EDIT`:

* `USER_CAN_ACCESS_FORM` → `contao_user.forms`

I think that the constant in the core bundle should be called `USER_CAN_EDIT_FORM`, because "can access" sounds like "is allowed to access the form module" to me and that is already covered by the `USER_CAN_ACCESS_MODULE` permission.

@contao/developers WDYT?

**Comment by aschempp** [comment]
The only difference I can spot is that for the mentioned calendars and feeds, theres a CREATE and DELETE permission as well. That's not the case for theme modules. The term _access_ probably originates from `BackendUser::hasAccess`.

I'm not sure using `ACCESS` instead of `EDIT` is more consistent. How can I `CREATE` and `DELETE` forms but not `ACCESS` forms?

Also, be aware these permissions are somewhat legacy since they existed before the permission system. It might be better to deprecate the permission constants completely at some point and have the DCA voter use the user information directly.

**Comment by leofeyer** [comment]
As discussed in the call, we want to add a `USER_CAN_EDIT_FORM` constant and deprecate the old one.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6545
