### ISSUE TITLE
Fix broken language file cache

### ISSUE THREAD

**Issue by ausi** [contao/contao#6520]
### Affected version(s)

4.13

### Description

We should backport the following part of https://github.com/contao/contao/pull/6518 as it causes a pretty nasty bug.

```
} catch (\OutOfBoundsException) {
    continue;
}
```

**Comment by fritzmg** [comment]
Reproduction:

1. Only require `contao/manager-bundle` (i.e. don't use the news, newsletter, comments or events bundle) [1].
2. Add the following translation:
    ```xml
    <!-- contao/languages/en/tl_content.xlf -->
    <?xml version="1.0" encoding="UTF-8"?>
    <xliff version="1.1">
      <file datatype="php" original="src/Resources/contao/languages/en/tl_content.php" source-language="en">
        <body>
          <trans-unit id="tl_content.lorem.ipsum.dolor.sit.amet">
            <source>Foobar</source>
          </trans-unit>
        </body>
      </file>
    </xliff>
    ```
3. Execute `vendor/bin/contao-console cache:clear --no-warmup --env=prod && vendor/bin/contao-console cache:warmup --env=prod`

`var/cache/prod/contao/languages/en/tl_content.php` will be missing.

[1] The reason is that in these bundles a `System::loadLanguageFile('tl_content')` call within the DCA files will lead to an uncaught `OutOfBoundsException`, even when building the cache.
