### ISSUE TITLE
Email addresses in text content elements are not obfuscated anymore

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6573]
### Affected version(s)

5.2.x

### Description

Normally email addresses are automatically obfuscated in text content elements. i.e. instead of `email@example.com` the email address is saved as `&#101;&#x6D;&#97;&#x69;&#108;&#x40;&#101;&#x78;&#97;&#x6D;&#112;&#x6C;&#101;&#x2E;&#99;&#x6F;&#109;`

However, in Contao 5.2 this does not happen anymore.

**Comment by ameotoko** [comment]
Do you mean `{{email::info@example.com}}` insert tags? Those are working fine for me in `5.2.6`

**Comment by fritzmg** [comment]
No, this issue is about email addresses entered in the text content element (without the insert tag).

**Comment by ausi** [comment]
The following line is probably missing in the new fragment controller: https://github.com/contao/contao/blob/b8750af5a1a7c680f27f64649c15649e468d6f3d/core-bundle/contao/elements/ContentText.php#L36

**Comment by Toflar** [comment]
I'd prefer a twig filter for that though. Wouldn't that be more flexible?

**Comment by fritzmg** [comment]
Definitely. This would allow it to be used in other places as well, and not just restricted to the `text` content element.

**Comment by ausi** [comment]
Should we add a general twig filter that allows using any insert tag filter?
Because there is already an `|encode_email` filter for insert tags.

**Comment by Toflar** [comment]
You mean a general `|contao_filter('currency_format')` for example?

**Comment by leofeyer** [comment]
> The following line is probably missing in the new fragment controller:

Fixed in #6585.

> I'd prefer a twig filter for that though. Wouldn't that be more flexible?

<del>We should make this a feature request that we can track independently of this issue.</del> As briefly discussed with @ausi, the Twig filter is our desired fix. Most likely, `|contao_filter('encode_email')` would already work, but maybe a dedicated `|encode_email` filter would be better.

**Comment by m-vo** [comment]
+1 for a filter.  We should definitively move this out of the controller again. Currently everything that looks like an email but was for example some JS/alpine/code/… will possibly be broken after it was passed through `StringUtil::encodeEmail()` and you cannot do anything against it.

Btw. is using entities for the email address still useful nowadays? Low hanging fruit? Otherwise we could still implement the filter but leave it out of the default template.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add an `|encode_email` Twig filter and apply it where the old elements used `StringUtil::encodeEmail()`.
