### ISSUE TITLE
Missing line break before custom <head> tags in generated html source code

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6749]
### Affected version(s)

5.3.0-RC1

### Description

This is probably just a cosmetic thing but when custom <head> tags are defined in a page layout there is no linebreak before the first line of the custom tags when looking at the generated html source code (see screenshot).

![image](https://github.com/contao/contao/assets/60215157/76ef8fa3-de5c-4dce-a260-c60c4a37ae94)

**Comment by leofeyer** [comment]
Since you opened about 5 issues regarding the "aesthetics of the generated HTML source code" today, let me just point out that I don‘t care at all and that you are probably wasting your time. I think it is important that templates are clearly structured, so people can work with them. If that produces some additional whitespace characters or line breaks in the generated HTML code, I don‘t mind at all.

**Comment by jochi44** [comment]
OK, got it.
As 5.3 is the next LTS I was testing extra carefully.
Doesn't seem to be desired.
I'm closing this issue.

**Comment by jochi44** [comment]
Closing this.
