### ISSUE TITLE
Order of id and classes in generated html output

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6750]
### Affected version(s)

5.3.0-RC1

### Description

The output of any defined IDs or css classes of generated elements is not constant regarding the “ordering”.

Example:
<body>					id first, css classes afterwards
article <div>				css classes first, id afterwards
(most of the) content elements		id first, css classes afterwards
but e.g. content element “download”	css classes first, id afterwards

Technically speaking, the order is completely irrelevant.
It's more an aesthetic thing.

**Comment by m-vo** [comment]
> Technically speaking, the order is completely irrelevant.

That's why I would not care at all. :slightly_smiling_face: 

Technically, we could make our `HtmlAttributes` output things sorted in some way. But that is the only place I would change things (if any). The order would otherwise get scrambled up anyways when reusing/extending templates due to the distinct order of them being executed.

**Comment by jochi44** [comment]
OK, got it.
As 5.3 is the next LTS I was testing extra carefully.
I'm closing this issue.
