### ISSUE TITLE
"Two pages with the same alias" does not work for the news module any more

### ISSUE THREAD

**Issue by Physiklehrer** [contao/contao#6865]
### Affected version(s)

4.13, 5.x

### Description

https://contao.org/en/news/contao-4_13_0 > "Two pages with the same alias". This is not working any more for the news module.

Reproduction on [Online-Demo](https://demo.contao.org/):

1. Rename site alias "news-detail" to "news" and set "Require an item" to active
2. Rename site alias "events-detail" to "events" and set "Require an item" to active

Now go to https://demo.contao.org/news.html and try to open one of the news entries, e.g. https://demo.contao.org/news/new-contao-versions-in-short-intervalls.html. You will get "An error occurred".

For the event module (Nr. 2 for comparison) everything works fine.

**Comment by fritzmg** [comment]
You also need to increase the routing priority of the reader page. Did you do this?

**Comment by Physiklehrer** [comment]
Yes, no effect unfortunately. One of the updates in 2023 broke it, before it was ok.

**Comment by leofeyer** [comment]
I can confirm the issue in the online demo.

`[2024-02-07T10:18:03.738226+01:00] request.CRITICAL: Uncaught PHP Exception Contao\CoreBundle\Exception\RouteParametersException: "Unable to generate route for page ID 8. The page requires an item but none was given." at PageUrlGenerator.php line 105 {"exception":"[object] (Contao\\CoreBundle\\Exception\\RouteParametersException(code: 0): Unable to generate route for page ID 8. The page requires an item but none was given. at /home/www/releases/54/vendor/contao/core-bundle/src/Routing/PageUrlGenerator.php:105)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\InvalidParameterException(code: 0): Parameter \"parameters\" for route \"tl_page.8\" must match \"/.+?\" (\"\" given) to generate a corresponding URL. at /home/www/releases/54/vendor/symfony/routing/Generator/UrlGenerator.php:182)"} []`

@Physiklehrer Which Contao version do you use?

**Comment by fritzmg** [comment]
I can reproduce the issue in the Online Demo.

I can reproduce the issue in my local `contao/contao-demo` instance.

I cannot reproduce the issue locally in Contao 5.2.x-dev (I tried with and without an URL suffix, in case that would have an influence) 🤔 

I cannot reproduce the issue locally in Contao 4.13.x-dev either (also with or without URL suffix, with legacy routing disabled).

**Comment by Physiklehrer** [comment]
The error came up with a minor update between Contao 4.13.32 and 4.13.35. Disabling and enabling legacy routing solved the problem with 4.13.36 (thanks for the tip!).

**Comment by leofeyer** [comment]
We have investigated the problem further and found out that it is caused by the news archive menu module in the left column. This is due to the configuration in the Contao demo, because the news archive menu with a reader page is used on both the news and the news reader page.

If you want to keep the current configuration, you cannot enable _Require item_ in the page settings. Otherwise, you could select another redirect page in the _News archive menu_ module:

<img width="456" alt="" src="https://github.com/contao/contao/assets/1192057/e436b35b-7101-41d4-9237-f8bae25c1812">

Since this is not a bug in Contao, I am closing this issue now. But pinging @sascha-mueller in case he wants to adjust the online demo.
