### ISSUE TITLE
Query parameters in deny list are not ignored by the HTTP cache

### ISSUE THREAD

**Issue by lukasbableck** [contao/contao#6908]
### Affected version(s)

4.13.37, 5.2.10, 5.3.0

### Description

If a URL is called with a query parameter that is in the [deny list](https://github.com/contao/contao/blob/5.3/core-bundle/src/EventListener/HttpCache/StripQueryParametersSubscriber.php#L22), it is still cached separately in the HTTP cache and not the cached version without parameters is delivered.

**Example**
1st request: https://example.com (Contao-Cache: miss/store => OK)
2nd request: https://example.com (Contao-Cache: fresh => OK, cache works)
3rd request: https://example.com?gclid=123 (Contao-Cache: miss/store => not OK! Should be fresh, as the cache entry from the first request should be sent to the client)
4th request: https://example.com?gclid=123 (Contao-Cache: fresh => OK again, but in theory wrong cache entry)

I have already checked the function [filterQueryParams](https://github.com/contao/contao/blob/5.3/core-bundle/src/EventListener/HttpCache/StripQueryParametersSubscriber.php#L89), the regex is ok and the parameter is correctly removed from $request->query if present.

The problem occurs in all current Contao versions (4.13.37, 5.2.10 and 5.3.0) without any installed extensions.

**Comment by fritzmg** [comment]
I can confirm the issue.

While our `StripQueryParametersSubscriber` executes 

https://github.com/contao/contao/blob/970a1ed0b65dc2613a95b726a00f5fb60700418e/core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php#L140

this won't actually have any effect at all, since our cache storage will use `Request::getUri()` which builds the query string using `$this->server->get('QUERY_STRING')` and not from its internal representation.

* [Psr6Store.php#L326](https://github.com/Toflar/psr6-symfony-http-cache-store/blob/9b3eb5b5f449a886b3ce202ddf3705e3d2ac79c9/src/Psr6Store.php#L326)
* [Request.php#L1068-L1070](https://github.com/symfony/symfony/blob/ed7d7aad4d63bc9b8d51d67c831794284e802ba2/src/Symfony/Component/HttpFoundation/Request.php#L1068-L1070)
* [Request.php#L1150](https://github.com/symfony/symfony/blob/ed7d7aad4d63bc9b8d51d67c831794284e802ba2/src/Symfony/Component/HttpFoundation/Request.php#L1150)

I guess our `StripQueryParametersSubscriber` will need to adjust the actual `ServerBag` instead (or additionally).
