### ISSUE TITLE
Templates mit "-" im Dateinamen nicht mehr erkannt/auswählbar

### ISSUE THREAD

**Issue by tuxenberger** [contao/contao#725]
Betrifft Contao ab 4.8.1

Laut Spooky werden nur noch Templatenamen mit "_" erkannt, TEmplates mit "-" werden im Backend in der Liste nicht mehr angezeigt und sind damit nach einem Update und der Bearbeitung eines Elements oder Artikels auf das Default Template zurückgeworfen.

Da einige meiner Projekte ein "-" im Templatenamen haben und auch einige Kauftemplates diese Namensvergabe haben ist das ein ziemliches Problem, was nur mit einigem Arbeitsaufwand wieder gerade zu kriegen ist (Projekt mit mehr als 5.000 Elementen)

Welchen Grund hat der Wegfall der Unterstützung des Bindestrichs?

Siehe auch https://community.contao.org/de/showthread.php?75906-Templates-nach-Update-nicht-mehr-ausw%C3%A4hlbar

**Comment by aschempp** [comment]
Kannst du bitte testen ob das Problem mit dem 4.8-branch behoben ist?

**Comment by tuxenberger** [comment]
Bin leider etwas unwissen was das angeht. Sorry :-/

**Comment by exscorp** [comment]
Contao 4.8.2

das "Problem" wurde nicht behoben. 
Kann es an dem "Picker" liegen, den mir werden zwei verschiedene Selectfelder angeboten.

In dem Beispiel wurde das Navigationsmenü genommen. 
In meinem Templateordner liegen folgende Dateien:

- nav_default.html5
- nav_default_test.html5
- nav_default-test.html5

- mod_navigation.html5
- mod_navigation_test.html5
- mod_navigation-test.html5

Beim **Navigationstemplate** bekomme ich ein normales Selectfeld und kann alle Templates auswählen.

Beim **Individuellen Template** bekomme ich ein chosen Selectfeld und mir wird nur das "mod_navigation_test.html5" Template angezeigt. Der globale Standardtemplate wird auch nicht angezeigt.

![template-auswahl](https://user-images.githubusercontent.com/3008649/64412527-d1c8a880-d08f-11e9-83cf-b151be520456.png)

**Comment by tuxenberger** [comment]
Das ist die aktuelle Version die ich habe -  4.8.2 ist installiert.

**Comment by tuxenberger** [comment]
Ich bearbeite einen Artikel und möchte diesen mit einem Template versehen. Im Ordner liegt sowohl ein Template mit der Bezeichnung "mod_article_hero.html5" wie auch "mod_article-hero.html5". Es wird nur "mod_article_hero.html5" in der Liste angezeigt.

![Bildschirmfoto 2019-09-06 um 10 21 52](https://user-images.githubusercontent.com/10707430/64412866-a8f4e300-d090-11e9-8741-c8c01048fa81.png)
![Bildschirmfoto 2019-09-06 um 10 22 27](https://user-images.githubusercontent.com/10707430/64412867-a98d7980-d090-11e9-8cc4-0974128a9db3.png)

**Comment by fritzmg** [comment]
@leofeyer imho we should revert the changes to the template grouping. I don't think that there can be a solution that works for every use case.

**Comment by leofeyer** [comment]
I disagree. The new logic works fine, we have just changed how the method is called:

**Contao 4.4**

https://github.com/contao/contao/blob/066e2821eb175c56d8492d86501d17c840a7f25a/core-bundle/src/Resources/contao/dca/tl_article.php#L697-L700

**Contao 4.8**

https://github.com/contao/contao/blob/28e40514419b8b8cdf2d02a75a7754005934529c/core-bundle/src/Resources/contao/dca/tl_article.php#L661-L664

This is actually a bugfix, because the "custom template" drop-down menu is not supposed to show the original template.

**Contao 4.4**

<img width="652" alt="" src="https://user-images.githubusercontent.com/1192057/64436633-0c006d00-d0c5-11e9-9f38-71a52e2aa86c.png">

**Contao 4.8**

<img width="599" alt="" src="https://user-images.githubusercontent.com/1192057/64436644-13c01180-d0c5-11e9-8129-061063ff00d2.png">

We could adjust the [glob pattern](https://github.com/contao/contao/blob/28e40514419b8b8cdf2d02a75a7754005934529c/core-bundle/src/Resources/contao/library/Contao/Controller.php#L122) to also support hyphens, however, using hyphens in custom templates only worked accidentally, because the glob pattern happened to return them. We have, however, never recommended or documented using hyphens in template names.

> und auch einige Kauftemplates diese Namensvergabe haben

@tuxenberger What themes exactly?

**Comment by tuxenberger** [comment]
@leofeyer https://themes.contao.org/de/index/contao-business-light.html

**Comment by leofeyer** [comment]
See #731 for a possible fix.
