### ISSUE TITLE
Drag’n’Drop in File Manager broken

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#7284]
### Affected version(s)

5.3.9

### Description

When using Drag’n’Drop  in the File Manager the filename tooltip is drifts quite far aways from the actual mouse cursor position: 

![image](https://github.com/contao/contao/assets/226890/e7110d56-baf4-44ea-94ff-6a2d19fc3199)

**Comment by zoglo** [comment]
Just a guess but that's most likely the getOffsetParent getting a wrong parent element due to some newly added stacking-context such as position: relative somewhere.

**Comment by zoglo** [comment]
As already guessed, this issue happens due to getOffsetParent getting the nearest parent with a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context).

The class `tl_file` did get a position: relative, thus the parent offset being wrong:
![image](https://github.com/contao/contao/assets/55794780/315c5e42-bb60-4ba0-8cce-8b0104f10338)

This could either be fixed by removing `position: relative` or rewriting the JS that gets the offset.
Unsure what the `position: relative` does right now.

**Comment by leofeyer** [comment]
@aschempp has added it in #6303:

<img width="798" alt="" src="https://github.com/contao/contao/assets/1192057/4b612ff1-a4fe-4ae0-a0dc-4a353d626a22">

**Comment by leofeyer** [comment]
It seems that it is only required on the `.tl_file_list` element, so maybe this can be fixed easily.
