### ISSUE TITLE
deleting select options causes weird symbols to appear

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#732]
__Reproduction:__

1. Log into the Contao Demo.
2. Go to _Form generator_ » _Contact_ and edit the `salutation` field.
3. Delete the _second_ option (`mr`).

Weird symbols will appear in the upper left corner of the browser window:

![screenshot_2018-08-10 form generator contact fields edit field id 15 - contao open source cms](https://user-images.githubusercontent.com/4970961/43955513-d480b046-9ca0-11e8-90c2-fa2a947a1c6c.png)

However, I cannot reproduce it all of the time.

**Comment by fritzmg** [comment]
Still reproducible in Contao 4.9.3.

**Comment by rabauss** [comment]
I've done some analysis on this issue as it's related to https://github.com/heimrichhannot/contao-multi-column-editor-bundle/issues/14

What is happening here?
1. You click delete without waiting to see the delayed tooltip for the delete button
2. The row is removed including the delete button
3. The tooltip for the delete button is displayed without title because the button is not in the DOM anymore
4. The empty tooltip is not repositioned from the top left corner because x and y of the `event.page` are `0` here:
https://github.com/contao/contao/blob/6cdb7fce22c393ba19e0ca3b9237398b9bbba050/core-bundle/src/Resources/public/mootao.js#L148

The best solution would be to hide or stop the tooltip initiation of the delete button before removing the row (2.)
How can I hide or stop init of `Tips.Contao` manually? I need that for the related issue above, too!

By the way there is another problem with the initiation of the tooltip for new rows of the option wizard - there is missing something like `Backend.addInteractiveHelp();` while adding the row! Because new rows don't have tooltips for the actions.

**Comment by rabauss** [comment]
The only solution I have now found for myself would be this:
Hide all `.tip-wrap` containers immediately and due to the delayed tooltip, you should do this again after `1000ms`

```js
document.querySelectorAll('.tip-wrap').forEach(function (tip) {
    tip.setStyle('display', 'none');
});
```

We cannot refer to the tooltip as these are initiated anonymous here 😞:
https://github.com/contao/contao/blob/9107f939c444a31ff26252179497222b9e31424d/core-bundle/src/Resources/public/core.js#L1279

Maybe I will start a PR in the next days 🚀
