### ISSUE TITLE
Datepicker is adding a doublespace between the date and time in "datim" fields.

### ISSUE THREAD

**Issue by bright-cloud-studio** [contao/contao#7321]
### Affected version(s)

5.3.11

### Description

When using a "Datim" Datepicker field to select the date and time, the final value returned by Datepicker is adding a double space between the date and time. The values entered into the Settings page for "Date and time format" won't stop this from happening. This causes the fields to fail their validation, as the returned value from Datepicker won't match the format entered into Settings.

You can recreate this by using any "Datim" Datepicker fields that are default in Contao, the "Activate on" field in Member Group for example.

I tested this on a Contao 4.13.35 site and Datepicker works as expected there. Contao 5.3.11 is the only Contao 5 version I've been able to check.

**Comment by zoglo** [comment]
^ this was discussed on Slack and tested in the official demo:

The time format that was used in the global settings was `m/d/y g:i`

**Comment by fritzmg** [comment]
As already mentioned in Slack: if your goal was to change the date and time format of the _front end_ you should do that in the settings of your respective website root. While the system settings act as a fallback for that, you should not change the date format there to an ambiguous format, otherwise it breaks date and time string parsing. There is also a warning for that for that reason.

**Comment by zoglo** [comment]
![image](https://github.com/contao/contao/assets/55794780/3169d85f-5f8b-4f16-bca7-629668fea3d6)
^ Just look at this, doesn't make sense and isn't an error in contao😄

**Comment by leofeyer** [comment]
The double space is caused by the `%l` format code, which pads single-digit numbers with a space, just like `%H` pads single-digit numbers with a `0`.

<img width="304" alt="" src="https://github.com/contao/contao/assets/1192057/be6ade75-5ea5-4f72-9db3-109fc877ea09">

I don‘t think that `strftime` has a format code for hours that does not pad single-digit numbers at all.

**Comment by leofeyer** [comment]
This is a problem, because we translate the [PHP format code](https://www.php.net/manual/en/datetime.format.php) `g` (12-hour format of an hour without leading zeros) to the [strftime format code](https://man7.org/linux/man-pages/man3/strftime.3.html) `%l` (12-hour format of an hour; single digits are preceded by a blank) here:

https://github.com/contao/contao/blob/b54906a6db7f4a497b787cb21bbc2ed65d3b2a8a/core-bundle/contao/library/Contao/Date.php#L458-L460

And that obviously does not work.

**Comment by fritzmg** [comment]
Yes, but we do not need to fix this. There is no point in changing the system time format to `g` - otherwise you cannot distinguish between 12:00 and 00:00 anymore etc. (at least in the way how it's used here).

**Comment by leofeyer** [comment]
There is a pretty simply fix: We adjust the MooTools `Date.format()` function.

https://github.com/contao-components/mootools/blob/048bdd9264156f9b66175fddc4531694bfd5ce1b/js/mootools-more.js#L853

We already did this for the `e` and `n` cases and we can do the same now for `l`. Using `return d.get('hr');` instead of `return pad((d.get('hr') % 12) || 12, 2, ' ');` solves the problem.

**Comment by leofeyer** [comment]
See https://github.com/contao-components/mootools/pull/3
