### ISSUE TITLE
Simultaneous edit mishap

### ISSUE THREAD

**Issue by m-vo** [contao/contao#7413]
### Affected version(s)

5.4

### Description

Assume you're editing the same element in two browsers. When trying to save the externally modified element, a JS error will appear: `Form responses must redirect to another location`. 

(Probably because we're sending the wrong response code in that case for Turbo to pick it up correctly.)

**Comment by fritzmg** [comment]
This happens because the `be_conflict` is rendered, right?

**Comment by fritzmg** [comment]
Hm, not sure how to fix this. Setting a `422` or `500` response status won't be enough, as Turbo still expects the form to be present in the response - which it won't be. Putting `<meta name="turbo-visit-control" content="reload">` into `be_conflict` will not have an effect here either. It is basically the same problem as https://github.com/contao/contao/issues/7377 as Turbo cannot handle cases where `POST` requests without a redirect response will cause different content to be rendered by the server. And unfortunately in this case we cannot disable turbo on the form - otherwise it defeats the purpose.

We would need to redirect to a new `/contao/conflict` route, with appropriate query parameter instead I think. Which is may be sensible anyway? Rather than directly rendering out of `DC_Table` with a `RedirectResponseException`. Might be difficult though, as we won't have the `$objVersion` object anymore to show the proposed changes.

**Comment by fritzmg** [comment]
Or we put the form into a `<turbo-frame>`, then `<meta name="turbo-visit-control" content="reload">` for `be_conflict` should work …
