### ISSUE TITLE
SERP preview not working in newly added news articles

### ISSUE THREAD

**Issue by LIVID-Media** [contao/contao#7554]
### Affected version(s)

5.4.*

### Description

When I add a news article, the SERP preview does not work. Even after saving, the preview is not updated. Only when you leave the article and edit it again, the SERP preview begins to work as usual. The bug is reproducible in the Contao demo.

**Comment by fritzmg** [comment]
I can confirm the issue.

**Comment by aschempp** [comment]
This only happens in Contao 5.4?

**Comment by fritzmg** [comment]
Yes, it works correctly in 5.3.

**Comment by leofeyer** [comment]
Another Turbo issue?

**Comment by zoglo** [comment]
Most likely :')

**Comment by leofeyer** [comment]
I was not able to reproduce this with Contao 5.4 at 3c65f28c9b374075d17ae0fa58a8f9d6f36ab7e8. I added a new news article and started typing a title and alias and the SERP widget updated accordingly 🤔

**Comment by fritzmg** [comment]
Something else is broken in `5.4.x-dev` currently. Turbo does not seem to work at all.

**Comment by leofeyer** [comment]
I cannot reproduce it in the online demo, either (Contao 5.4.4).

**Comment by fritzmg** [comment]
The issue is reproducible with https://github.com/contao/contao/pull/7737

**Comment by leofeyer** [comment]
Okay, now I can reproduce it, too. So how do we fix it? I don't want to rewrite the script to a Stimulus controller 🙈

**Comment by fritzmg** [comment]
I don't mind doing that 😉  - but I will have a look at the problem first.

**Comment by fritzmg** [comment]
The problem is fairly simple/silly, though unexpected for me. In our `be_*` templates we have the following:

https://github.com/contao/contao/blob/e1e2bfaaed49c4db92884096070d6c0257fc7a35/core-bundle/contao/templates/backend/be_main.html5#L23

This outputs:

```html
<script>var Contao={…}</script>
```

Our `backend.js` then imports `mootao.js` - which adds additional properties to the global `Contao` object, like `Contao.SerpPreview`. This works fine for a normal (non-Turbo) request.

However, when a page is rendered with Turbo Drive

```html
<script>var Contao={…}</script>
```

is executed again - but `backend.js` will not be. Thus the global `Contao` object is overwritten with just the initial values - and `Contao.SerpPreview` will be gone.

This is unexpected because I thought Turbo won't execute anything from the `<head>` at all, not even inline `<script>`s, but that is not the case (a good thing though - otherwise the values in `Contao` won't update).

`Contao.SerpPreview` is the only property that is dynamically added to the global `Contao` object as far as I can see, so as a quickfix we could move it to its own global variable?

// I may have a better idea

**Comment by fritzmg** [comment]
Unfortunately ultimately we do need to rewrite it as a Stimulus controller. Even if we fix overwriting the global `Contao` variable, the following error will occur if you create a news, go back and then create a news again:

```
Uncaught TypeError: serpTitle is null
    initialize mootao.js:368
```

This is because the HTML from the previewous news edit mask will be gone - but the event listeners registered by the serp widget will still exist.
