### ISSUE TITLE
Hinweistext für Felder Anzeigen ab und Anzeigen bis

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#756]
Bei den Feldern `Anzeigen ab` und `Anzeigen bis` bei Seiten, Artikeln, Inhaltselementen etc. lautet der Hinweistext am Beispiel von Seiten:

> Die Seite erst ab diesem Tag auf der Webseite anzeigen.
> Die Seite nur bis zu diesem Tag auf der Webseite anzeigen.

Es kann bzw. muss jedoch nicht nur ein Tag sondern auch eine Uhrzeit eingegeben werden, daher schlage ich vor "Tag" durch "Zeitpunkt" zu ersetzen:

> Die Seite erst ab diesem Zeitpunkt auf der Webseite anzeigen.
> Die Seite nur bis zu diesem Zeitpunkt auf der Webseite anzeigen.

**Comment by leofeyer** [comment]
As suggested by @blairwinans (thank you for your help here), we want to change the help text as follows:

> If you want to prevent the page from showing on the website [before|after] a certain date/time, you can enter it here. Otherwise leave the field blank.

Since this change affects multiple labels (pages, articles, content elements, events, news etc.), I would prefer to make it only in Contao 4.9, so non-English users do not suddenly lose several labels in a patch release.

**Comment by aschempp** [comment]
Is that really a problem if you push the changes to Transifex a few days before the release? I also di have similar things with the Contao Manager and simply skip merging the lines when synching with Transifex, so the old labels remain until they are correctly translated.
