### ISSUE TITLE
Canonical URLs are incorrectly generated

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#7606]
### Affected version(s)

4.13.49

### Description

I have a multilingual website with several page trees. If I now manually select another page from another page tree in the page structure, the URL is generated incorrectly.
The prefix is also added to the URL. (See screenshot)

![screen-20241007_sURaup2h](https://github.com/user-attachments/assets/ac887bfc-4519-438c-8db6-7944593939b5)

**Comment by fritzmg** [comment]
I can confirm the issue.

I think the issue is, that the picker only returns `{{link_url::9}}` - but for the canonical URL it needs to be `{{link_url::9|absolute}}`.

**Comment by ausi** [comment]
I think we need to use the correct base URL here: https://github.com/contao/contao/blob/d84a67a014443086c6149668172c7649f016e69e/core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php#L104

In Contao 5 this is probaly not an issue because `{{link_url::9}}` would already return a URL that starts with a `/`. However we should fix it there too as other insert tags might still output URLs that are relative to the base href.
