### ISSUE TITLE
deprecation of contao/contao

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#81]
This package has recently been deprecated. Am I right in assuming that as from now on you are supposed to add each individual contao bundle to your `composer.json` (depending on which bundles you actually need)? The `contao/standard-edition` still uses `contao/contao`: https://github.com/contao/standard-edition/blob/4.3.2/composer.json#L21 - however in the `release/4.4.0` branch it does indeed use the bundles individually: https://github.com/contao/standard-edition/blob/release/4.4.0/composer.json

**Comment by leofeyer** [comment]
The basic idea behind deprecating the meta packages `contao-components/all` and `contao/contao` is to reduce dependency conflicts when you need to require an unstable version of a package.

I am actually not sure about deprecating `contao/contao` though. It sure is convenient if you want to add Contao to an existing Symfony application, however, nobody does that currently (but uses the standard edition instead).

@contao/developers What do think?

**Comment by Toflar** [comment]
The standard edition is a starting point and you won't be using anything from it as soon as your project is launched (except for checking what has changed when updating ;-)). To me the `contao-components/all` package makes no sense really. It's required by the `core-bundle` anyway because it couldn't work otherwise. We could as well just specify all the components needed in the `core-bundle`.
The `contao/contao` meta package is nice if you want to install all "core" bundles. But this use case is very rare, I'd say. Even in 3.5 I almost always disabled at least one of them (faq or newsletter mostly). So imho we can deprecate both.

**Comment by fritzmg** [comment]
I also think both packages can be deprecated. While `contao/contao` may be convenient, I doubt there are many use cases for it.

**Comment by leofeyer** [comment]
Another thing to consider if we do not deprecate the meta package:

```json
    "require": {
        "contao/calendar-bundle": "^4.3.2",
        "contao/comments-bundle": "~4.3",
        "contao/core-bundle": "^4.3.1",
        "contao/faq-bundle": "~4.3",
        "contao/installation-bundle": "^1.2.1",
        "contao/listing-bundle": "~4.3",
        "contao/news-bundle": "~4.3",
        "contao/newsletter-bundle": "~4.3"
    },
```

Once Contao 4.4 has been released, `"contao/contao": "~4.3"` will install Contao 4.4. Shouldn't the `composer.json` rather be:

```json
    "require": {
        "contao/calendar-bundle": "4.3.* >=4.3.2",
        "contao/comments-bundle": "4.3.*",
        "contao/core-bundle": "4.3.*",
        "contao/faq-bundle": "4.3.*",
        "contao/installation-bundle": "1.2.* >=1.2.1",
        "contao/listing-bundle": "4.3.*",
        "contao/news-bundle": "4.3.*",
        "contao/newsletter-bundle": "4.3.*"
    },
```

Then again, `"symfony/symfony": "~3.0"` also installs Symfony 3.2.

**Comment by aschempp** [comment]
I totally agree with @Toflar. On every Contao 4 installation I have, I did not install all existing extensions, so I always had to manually change `contao/contao` to the respective bundles. It would be way easier to just drop what I don't want.

I actually don't *care* about `contao-components/all` because noone is ever affected by it. It just makes the `contao/core-bundle` composer.json much smaller, but I don't think that's worth it…

**Comment by leofeyer** [comment]
Ok, then we'll leave both deprecated and remove them at some point in the future.
