### ISSUE TITLE
URL-Suffix / wird bei Fehler 404 an URL angefügt

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#822]
Wenn in Contao 4.4.44 als URL-Suffix `/` konfiguriert ist, erfolgt bei einem Fehler 404 zunächst eine Umleitung mit dem Status-Code 301, bei der das URL-Suffix an die URL angefügt wird, bevor dann die Fehlerseite angezeigt wird. Beispielsweise wird von `example.com/test` zu `example.com/test/` oder von `example.com/test.jpg` zu `example.com/test.jpg/` umgeleitet.

**Comment by fritzmg** [comment]
That is imho correct behavior.

**Comment by Mynyx** [comment]
Why?

**Comment by leofeyer** [comment]
Are you sure that the redirect is done by Contao and not by the web server?

**Comment by andreheeke** [comment]
I can't confirm that. We always configure Contao without the .html suffix and no additional slash is appended there when a 404 error page is called. Tested in version 4.4 and 4.8.

**Comment by Mynyx** [comment]
@andreheeke Without the `.html` suffix or with `/` suffix?

**Comment by andreheeke** [comment]
@Mynyx We're not setting any suffix.  If you set a simple slash as a suffix, it will of course be appended at the end when you call a 404 error page.

**Comment by Mynyx** [comment]
> Are you sure that the redirect is done by Contao and not by the web server?

Yes, the redirect only occurs if the suffix `/` is configured in Contao version 4.4. It does neither occur when another suffix is configured nor Contao 3.5 or 4.8 is used.

**Comment by leofeyer** [comment]
> If you set a simple slash as a suffix, it will of course be appended at the end

That is how I see it, too.

**Comment by ausi** [comment]
I think this is a bug. `example.com/test.jpg` should not be redirected to `example.com/test.jpg/` if `/` is configured as the suffix. Same as it doesn’t get redirected to `example.com/test.jpg.html` with `.html` as the suffix.

**Comment by leofeyer** [comment]
It is only a bug if `example.com/test.jpg` points to an existing file. Then, of course, the slash should not be appended. But according to the initial description, the problem occurs on the error 404 page, which means that `test.jpg` is passed to the application and treated as a regular URL – therefore it is correct to append the URL suffix IMHO.

**Comment by Mynyx** [comment]
The standard behaviour of a Apache webserver with static files is, that ``test`` ist only redirected to ``test/`` if this directory exists, otherwise the 404 page is shown directly. And never a redirect from ``example.com/test.jpg`` to ``example.com/test.jpg/`` will happen.

**Comment by ausi** [comment]
> the problem occurs on the error 404 page, which means that `test.jpg` is passed to the application and treated as a regular URL – therefore it is correct to append the URL suffix IMHO.

I don’t see why it should be correct to add the suffix. If the page does not exist the server should answer with status code 404, not a redirect. And why should the suffix only be added if it is set to `/` and not for `.html`?

**Comment by leofeyer** [comment]
Hm, I guess you are right. 🤔

**Comment by leofeyer** [comment]
I have debugged this issue and the redirect comes from the Symfony route  matcher.

If `/` is used as URL suffix, the path of the `contao_frontend` route will be `/{_locale}/{alias}/`. Later on, this path is converted into a regex ending with `/$`.

The `PhpMatcherDumper` then converts this regex from `/$` into `/?$` on lines [254–257](https://github.com/symfony/symfony/blob/b104760cdfb99e0eda921e4c670f84f3b4b9b063/src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php#L254-L257), which makes the trailing slash optional:

```php
if ($supportsTrailingSlash && $pos = strpos($regex, '/$')) {
    $regex = substr($regex, 0, $pos).'/?$'.substr($regex, $pos + 2);
    $hasTrailingSlash = true;
}
```

The `PhpMatcherDumper` then adds the following code to the Symfony cache in lines [312–314](https://github.com/symfony/symfony/blob/b104760cdfb99e0eda921e4c670f84f3b4b9b063/src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php#L312-L314):

```php
$code .= <<<EOF
if ('/' === substr(\$pathinfo, -1)) {
    // no-op
} elseif ('GET' !== \$canonicalMethod) {
    goto $gotoname;
} else {
    return array_replace(\$ret, \$this->redirect(\$rawPathinfo.'/', '$name'));
}
EOF;
```

Our request matches the `else` condition and therefore returns a redirect response to `$rawPathinfo.'/'`, which is where the trailing slash is appended.

**Conclusion**

Routing has changed massively in Symfony 4.2, so we have to check if the issue occurs in Contao 4.8 at all. If not, I think this might be a known limitation in Contao 4.4 (because Contao 4.4 is only compatible with Symfony 3).

**Edit**: The issue does not occur in Contao 4.8.
