### ISSUE TITLE
Delete the accordion Wrapper stop if the Wrapper start gets deleted

### ISSUE THREAD

**Issue by Aybee** [contao/contao#833]
**Description**  
Contao 4.4.40 (muss Kunde noch auf Update hinweisen)

Ich war gerade in ner Seite von mir und wunderte mich, warum das Layout zerschossen ist. Da hat der Kunde wohl Artikel kopiert und dann einige Akkordeon **Umschlag Anfang** gelöscht und die **Umschlag Ende** vergessen. Hat einiges an Zeit gekostet, bis ich das herausgefunden habe, hatte den Fehler erstmal bei mir gesucht.

**Kann man dies automatisieren**, dass das Pendant des Akkordeon Umschlags gelöscht wird? Ich meine mich zu erinnern, dass einige Erweiterungen, oder sogar Contao dies bereits gemacht hatte.

**Comment by m-vo** [comment]
Imho brauchen wir echte Wrapper-Elemente (die einen Kind-Context haben).

**Comment by asaage** [comment]
https://github.com/contao/contao/issues/391

**Comment by aschempp** [comment]
Maybe we should consider using an ODM for the `tl_content` table 🙈  🛠

**Comment by leofeyer** [comment]
See #391.

**Comment by fritzmg** [comment]
This isn't really part of the nested content elements idea is it?

**Comment by leofeyer** [comment]
Getting rid of the wrapper elements is the main idea behind nested content elements. 😄 

```
Container (main)
    - Headline
    - Text
    - Slider
        - Container
            - Image
            - Text
        - Container
            - Image
            - Text
    - Text
```

**Comment by fritzmg** [comment]
Yes, getting rid of them... but this issue is about their current implementation and whether Contao should automatically delete the start or stop element, if one or the other gets deleted. I think `semantic_html5` already does this for example.

**Comment by leofeyer** [comment]
I don't think this will work reliably. Start and stop elements can be nested, so how do you determine which one to delete?

**Comment by fritzmg** [comment]
When you create a start element, the stop element is automatically created. The automatically created element can save a reference to its start element. Then when either element is deleted, the other element can be deleted as well.

Of course this could still lead to erroneous mark-up, since you can move the start and stop elements anywhere you like. This could be solved by #391 - but again: this is a more general issue _independent_ from this one.

If you delete the start __and__ stop element when deleting either, then you at least remove the possibility of unmatched open or close tags in your mark-up.

**Comment by leofeyer** [comment]
As I said, I doubt that this would work **reliably** without nested content elements. But go ahead and give it a shot. I will happily merge a working pull request.

**Comment by m-vo** [comment]
Disallowing the stop element to be removed individually sure is an improvement. Imho doing nestings like this must be prevented as well: `<x><y></x></y>` in order to have an intuitive UI in this case. But that's a bit harder, especially with drag&drop...
