### ISSUE TITLE
Try using the FilesystemTagAwareAdapter again

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#845]
**Description**  

Symfony has improved the `FilesystemTagAwareAdapter` class in https://github.com/symfony/symfony/pull/33921, therefore we might want to remove the following line once we have upgraded to Symfony 4.4:

https://github.com/contao/contao/blob/2635f5a043c1308fd3fe1352b4b9de7665206cc8/manager-bundle/src/HttpKernel/ContaoCache.php#L83

**Comment by Toflar** [comment]
I just tried this and the purge performance has indeed been fixed but the problem with the number of files remains the same. The tags are still stored as symlinks and thus causing the number of files in `http_cache` to grow above 2000 for like 10 pages easily.
Compared to the `TagAwareAdapter` the `FilesystemTagAwareAdapter` is definitely faster which is because it only needs 1 round trip instead of 2. So the RTT is of course smaller for the `FilesystemTagAwareAdapter`.

**Comment by leofeyer** [comment]
Then we should probably stick to the `TagAwareAdapter` class, because a regular website with a couple of news entries might have about 100 pages, which would result in 20.000 files.

@contao/developers WDYT?

**Comment by Toflar** [comment]
Well the calculation is of course not as simple as that but yes, it will be many files.

**Comment by leofeyer** [comment]
As discussed in Mumble on December 19th, we want to stick to the `TagAwareAdapter`.
