### ISSUE TITLE
(TL_Maintanance) X is not an executable class

### ISSUE THREAD

**Issue by Sioweb** [contao/contao#89]
**Affected version(s)** 4.6.x

**Description**  

I try to run a new Maintenance Task and i get error `sioweb.glossar.rebuild is not an executable class`. It seams that the interface \executable is not available in other namespaces. 

**How to reproduce**

Add follow lines to foreach-loop in ModuleMaintenance.php

	$cls = get_class($this->$callback);
	print_r(class_implements(get_class($this->$callback)));

This prints out empty array.

services

    services:
        sioweb.glossar.rebuild:
            class: Sioweb\Glossar\Services\Rebuild
            public: true

config

    array_insert($GLOBALS['TL_MAINTENANCE'],1,array(
        'sioweb.glossar.rebuild'
    ));

class:

    use \executable;
    class Rebuild implements  executable

Is there a trick to implement this interface?

**Comment by Sioweb** [comment]
How i would fix it:

- Add directory `/src/contao/core-bundle/Interfaces`
- add interfaces as file, for example Executable.php
- add Namespace \Contao\CoreBundle\Interfaces;
- update \executable in all executable Classes to \Contao\CoreBundle\Interfaces\Executable;
- update in mine classes too
- change row 48 in ModuleMaintenance.php to `if (!$this->$callback instanceof \Contao\CoreBundle\Interfaces\Executable)`

I tryed this on localhost and it worket. Should i create a Pull Request for it?

**Comment by leofeyer** [comment]
> It seams that the interface \executable is not available in other namespaces.

Why should it? It is already available in the global namespace. Just add `implements \executable` in your maintenance class.

**Comment by Sioweb** [comment]
No it isnt. As i wrote, its not available in my namespace, and ModuleMaintenance do not find the interface.

Follow lines into the foreach of ModuleMaintanance will print an empty result. It finds my class but not your interface. I testet it with an own testinterface and it was found.

```
$cls = get_class($this->$callback);
print_r(class_implements(get_class($this->$callback)));
```

**Comment by Sioweb** [comment]
Here is my class https://gist.github.com/Sioweb/573f9fe0a15271b4674ccb88828d1139
See Line 32

**Comment by ausi** [comment]
The `src/Resources/contao/helper/interface.php` gets loaded when the Contao framework is initialized, but the Service `sioweb.glossar.rebuild` gets loaded earlier.

Normally this would result in an error like `ClassNotFoundException: Attempted to load interface "executable" from the global namespace.`. But due to some magic inside `Symfony\Component\Config\Resource\ClassExistenceResource::isFresh()` the error gets ignored and the class is loaded without the interface.

I’m not sure how this can happen and if this is a PHP or a Symfony bug, but adding the following line in the `app_dev.php` before `$kernel->handle(…)` results in a `ClassNotFoundException` as expected:

```
var_dump((new \ReflectionClass('Sioweb\Glossar\Services\Rebuild'))->getInterfaces());
```

but the same line directly after `$kernel->handle(…)` just prints `array(0) { }` without an error.

We could probably fix this by loading the `interface.php` via Composer autoloading instead.

But we should probably also debug how `Symfony\Component\Config\Resource\ClassExistenceResource::isFresh()` can load a class with a missing interface.

**Comment by ausi** [comment]
The incomplete autoloading seems to be a PHP bug: <https://bugs.php.net/bug.php?id=76980>

But nevertheless we should register the *interface.php* file in the Composer autoload configuration IMO.

**Comment by Sioweb** [comment]
Danke dir für deine Recherche!

Ich löse das vorübergehend in meinem Modul mit Composer:

```
"autoload": {
    ...
    "files": [
        "../../contao/core-bundle/src/Resources/contao/helper/interface.php"
    ]
    ...
}
```

Dann funktioniert alles wie gedacht: `class Rebuild implements \executable`

**Comment by ausi** [comment]
@Sioweb Wouldn’t this result in an error like `Cannot declare interface …, because the name is already in use in …` because *interface.php* gets included twice now, first by Composer and second by `ContaoFramework::initialize()`?

**Comment by Sioweb** [comment]
Ah strange, it worked until i cleared my cache. So its no solution. Sry

Well i think the only working solution will be to write my own maintanance handling/backendsite for this module, no? Because it should be compatible with contao 4.4. 

Or do u see a way to handle this?

**Comment by leofeyer** [comment]
Changed in 1ca15389d0fda866dec2f86fcbc967070048efce.
