### ISSUE TITLE
New inserttag {{insert_news::ID}}

### ISSUE THREAD

**Issue by seaneble** [contao/contao#956]
The [manual](https://contao.org/de/manual/3.3/managing-content.html#include-elemente) lists some include inserttags which can be used on the following levels:
- Content elements
- Forms
- Modules
- Articles

The first three of these are individual data types, whereas the article is itself a collection of content elements. But Contao also includes other content element collections like news, events etc. for which no inserttag exisits.

I would like to see such an inserttag for other collection types as well, especially for news. It would be especially handy for newsletters (as already mentioned way back in contao/core#1510). It seems (from that old ticket) that there used to be such an inserttag, but I cannot find any reference to it other than that.
Also, the new tag would help to standardize this particular subset of tags (as previously done for the link inserttags).

**Comment by leofeyer** [comment]
The "insert_article" insert tag works, because the article module does not need special configuration. It is always available and does not need to be created and configured beforehand.

Let's assume there was an `{{insert_news::ID}}` tag – which template would we use? And which image size? And how would we overwrite the comments template? We would probably end up with something like `{{insert_news::42?template=event_full&image_size=2&cssClass=foo}}`. Is this really something that you want to work with?

**Comment by seaneble** [comment]
I really have no idea why I opened this issue anymore. I see the complications. And as only two people seem to have been interested in this in all these years, let’s just close it.
